-- Apply only after loading and reviewing REVIEW_REQUIRED rows.
BEGIN;
ALTER TABLE operations ADD CONSTRAINT operations_company_fk FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE operations ADD CONSTRAINT operations_campaign_source_fk FOREIGN KEY (source_campaign_id) REFERENCES campaign_definitions(id);
ALTER TABLE operations ADD CONSTRAINT operations_company_normalized_name_uq UNIQUE (company_id, normalized_name);
ALTER TABLE users ADD CONSTRAINT users_person_fk FOREIGN KEY (person_id) REFERENCES people(id);
ALTER TABLE teams ADD CONSTRAINT teams_operation_fk FOREIGN KEY (operation_id) REFERENCES operations(id);
ALTER TABLE teams ADD CONSTRAINT teams_supervisor_fk FOREIGN KEY (supervisor_id) REFERENCES users(id);
ALTER TABLE assignments ADD CONSTRAINT assignments_person_fk FOREIGN KEY (person_id) REFERENCES people(id);
ALTER TABLE assignments ADD CONSTRAINT assignments_operation_fk FOREIGN KEY (operation_id) REFERENCES operations(id);
ALTER TABLE assignments ADD CONSTRAINT assignments_team_fk FOREIGN KEY (team_id) REFERENCES teams(id);
ALTER TABLE assignments ADD CONSTRAINT assignments_supervisor_fk FOREIGN KEY (supervisor_id) REFERENCES users(id);
ALTER TABLE operation_supervisors ADD CONSTRAINT operation_supervisors_operation_fk FOREIGN KEY (operation_id) REFERENCES operations(id);
ALTER TABLE operation_supervisors ADD CONSTRAINT operation_supervisors_user_fk FOREIGN KEY (supervisor_id) REFERENCES users(id);
ALTER TABLE operation_supervisors ADD CONSTRAINT operation_supervisors_period_uq UNIQUE (operation_id, supervisor_id, start_at);
ALTER TABLE staffing_movements ADD CONSTRAINT staffing_movements_person_fk FOREIGN KEY (person_id) REFERENCES people(id);
ALTER TABLE staffing_movements ADD CONSTRAINT staffing_movements_assignment_fk FOREIGN KEY (assignment_id) REFERENCES assignments(id);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_person_fk FOREIGN KEY (person_id) REFERENCES people(id);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_evaluator_fk FOREIGN KEY (evaluator_user_id) REFERENCES users(id);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_supervisor_fk FOREIGN KEY (supervisor_user_id) REFERENCES users(id);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_operation_fk FOREIGN KEY (operation_id) REFERENCES operations(id);
ALTER TABLE evaluation_items ADD CONSTRAINT evaluation_items_evaluation_fk FOREIGN KEY (evaluation_id) REFERENCES evaluations(id);
ALTER TABLE evaluation_items ADD CONSTRAINT evaluation_items_ordinal_uq UNIQUE (evaluation_id, ordinal);
ALTER TABLE evaluation_media ADD CONSTRAINT evaluation_media_evaluation_fk FOREIGN KEY (evaluation_id) REFERENCES evaluations(id);
ALTER TABLE feedback ADD CONSTRAINT feedback_evaluation_fk FOREIGN KEY (evaluation_id) REFERENCES evaluations(id);
ALTER TABLE feedback ADD CONSTRAINT feedback_person_fk FOREIGN KEY (person_id) REFERENCES people(id);
ALTER TABLE feedback ADD CONSTRAINT feedback_supervisor_fk FOREIGN KEY (supervisor_user_id) REFERENCES users(id);
ALTER TABLE feedback ADD CONSTRAINT feedback_evaluator_fk FOREIGN KEY (evaluator_user_id) REFERENCES users(id);
ALTER TABLE development_assignments ADD CONSTRAINT development_assignments_capsule_fk FOREIGN KEY (capsule_id) REFERENCES development_capsules(id);
ALTER TABLE development_assignments ADD CONSTRAINT development_assignments_person_fk FOREIGN KEY (person_id) REFERENCES people(id);
ALTER TABLE legacy_sessions ADD CONSTRAINT legacy_sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id);
CREATE UNIQUE INDEX companies_normalized_name_uq ON companies(normalized_name);
CREATE INDEX assignments_person_active_idx ON assignments(person_id, active);
CREATE INDEX assignments_operation_active_idx ON assignments(operation_id, active);
CREATE INDEX evaluations_person_date_idx ON evaluations(person_id, evaluated_at);
CREATE INDEX evaluations_operation_date_idx ON evaluations(operation_id, evaluated_at);
CREATE INDEX feedback_evaluation_idx ON feedback(evaluation_id);
CREATE INDEX staffing_movements_person_date_idx ON staffing_movements(person_id, effective_at);
COMMIT;
