import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, BookOpen, CheckSquare, Eye, MessageSquare, Users } from 'lucide-react';
import { developmentApi } from '../../api/sharedRepository';
import { useApp } from '../../context/AppContext';
import type { Evaluation } from '../../types';

type Feedback = { feedback_id:string; evaluation_id:string; advisor_id:string; status:string; created_at:string; updated_at:string };
type Capsule = { id:string; title:string; gap?:string; status:string; createdAt?:string };
type Assignment = { capsuleId:string; status:string };
const auth = () => ({ Authorization:`Bearer ${sessionStorage.getItem('CONTACT_CENTER_AUTH_TOKEN') || ''}` });
const score = (item:Evaluation) => item.evaluationType === 'QUALITY' ? (item.technicalScore ?? item.scoreTotal ?? 0) : (item.scoreTotal ?? 0);
const label = (value:string) => value.replaceAll('_',' ').toLowerCase().replace(/^./, c => c.toUpperCase());

const useMonitorRecords = () => {
  const [feedbacks,setFeedbacks]=useState<Feedback[]>([]), [capsules,setCapsules]=useState<Capsule[]>([]), [assignments,setAssignments]=useState<Assignment[]>([]);
  useEffect(()=>{ void Promise.all([
    fetch('/api/feedbacks',{headers:auth()}).then(r=>r.ok?r.json():{feedbacks:[]}),
    developmentApi.capsules().catch(()=>({capsules:[]})), developmentApi.assignments().catch(()=>({assignments:[]})),
  ]).then(([f,c,a])=>{setFeedbacks(f.feedbacks||[]);setCapsules(c.capsules||[]);setAssignments(a.assignments||[]);}); },[]);
  return {feedbacks,capsules,assignments};
};

const Metric=({icon,label:valueLabel,value}:{icon:React.ReactNode;label:string;value:string|number})=><article className="cm-card p-4"><div className="flex items-center gap-3 text-[var(--cm-primary)]">{icon}<span className="text-xs font-bold text-[var(--cm-text-secondary)]">{valueLabel}</span></div><strong className="mt-2 block text-2xl">{value}</strong></article>;

export const MonitorResultsView:React.FC<{onSelectEvaluation:(evaluation:Evaluation)=>void}>=({onSelectEvaluation})=>{
  const {evaluations:all,advisors,campaigns}=useApp();
  const [advisorId,setAdvisorId]=useState(''),[campaignId,setCampaignId]=useState(''),[result,setResult]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const items=useMemo(()=>all.filter(e=>(!advisorId||e.advisorId===advisorId)&&(!campaignId||e.campaignId===campaignId)&&(!from||e.date>=from)&&(!to||e.date<=to)&&(!result||(result==='APROBADO'?score(e)>=75:score(e)<75))),[all,advisorId,campaignId,from,to,result]);
  const average=items.length?Math.round(items.reduce((n,e)=>n+score(e),0)/items.length):0;
  const uniqueAdvisors=new Set(items.map(e=>e.advisorId)).size;
  const ordered=[...items].sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const bands=[['Alto (90–100)',items.filter(e=>score(e)>=90).length],['Esperado (75–89)',items.filter(e=>score(e)>=75&&score(e)<90).length],['Bajo (0–74)',items.filter(e=>score(e)<75).length]] as const;
  return <main className="cm-workspace min-h-full p-5 lg:p-8"><header className="cm-page-heading"><p className="cm-eyebrow">MONITOR</p><h1 className="text-2xl font-bold">Resultados</h1><p className="mt-1 text-sm text-[var(--cm-text-secondary)]">Resultados de los asesores evaluados por ti.</p></header>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={<CheckSquare className="h-5 w-5"/>} label="Evaluaciones" value={items.length}/><Metric icon={<BarChart3 className="h-5 w-5"/>} label="Resultado promedio" value={`${average}%`}/><Metric icon={<Users className="h-5 w-5"/>} label="Asesores evaluados" value={uniqueAdvisors}/></div>
    <section className="cm-card mt-4 grid gap-3 p-4 md:grid-cols-5"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="cm-input p-2"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="cm-input p-2"/><select value={advisorId} onChange={e=>setAdvisorId(e.target.value)} className="cm-select p-2"><option value="">Todos los asesores</option>{advisors.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={campaignId} onChange={e=>setCampaignId(e.target.value)} className="cm-select p-2"><option value="">Todas las campañas</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={result} onChange={e=>setResult(e.target.value)} className="cm-select p-2"><option value="">Todo resultado</option><option value="APROBADO">Aprobado</option><option value="REPROBADO">Reprobado</option></select></section>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="cm-card p-5"><h2 className="font-bold">Evolución de resultados</h2><div className="mt-5 flex h-44 items-end gap-2 overflow-x-auto border-b border-[var(--cm-border)]">{ordered.slice(-16).map(e=><div key={e.id} className="flex min-w-8 flex-1 flex-col items-center justify-end gap-1" title={`${e.date}: ${score(e)}%`}><span className="text-[10px]">{score(e)}%</span><i className="block w-full max-w-10 rounded-t bg-[var(--cm-primary)]" style={{height:`${Math.max(4,score(e))}%`}}/></div>)}</div></section><section className="cm-card p-5"><h2 className="font-bold">Distribución de cumplimiento</h2><div className="mt-5 space-y-5">{bands.map(([name,total])=><div key={name}><div className="flex justify-between text-xs"><span>{name}</span><b>{total}</b></div><div className="mt-2 h-2 rounded bg-[var(--cm-surface-elevated)]"><span className="block h-full rounded bg-[var(--cm-primary)]" style={{width:`${items.length?total/items.length*100:0}%`}}/></div></div>)}</div></section></div>
    <EvaluationTable title="Evaluaciones recientes" items={[...items].sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)).slice(0,20)} advisors={advisors} campaigns={campaigns} onSelect={onSelectEvaluation}/>
  </main>;
};

export const MonitorProgressView:React.FC<{onSelectEvaluation:(evaluation:Evaluation)=>void;onNavigate:(section:'feedback'|'development')=>void}>=({onSelectEvaluation,onNavigate})=>{
  const {evaluations:all,advisors,campaigns}=useApp(); const {feedbacks,capsules,assignments}=useMonitorRecords();
  const [period,setPeriod]=useState('MONTH'),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const bounds=useMemo(()=>{const now=new Date(),today=now.toISOString().slice(0,10);if(period==='TODAY')return[today,today];if(period==='WEEK'){const d=new Date(now);d.setDate(d.getDate()-((d.getDay()+6)%7));return[d.toISOString().slice(0,10),today];}if(period==='MONTH')return[`${today.slice(0,7)}-01`,today];return[from,to];},[period,from,to]);
  const within=(date?:string)=>Boolean(date)&&(!bounds[0]||date!.slice(0,10)>=bounds[0])&&(!bounds[1]||date!.slice(0,10)<=bounds[1]);
  const evaluations=all.filter(e=>within(e.date)), periodFeedbacks=feedbacks.filter(f=>within(f.created_at)), periodCapsules=capsules.filter(c=>within(c.createdAt));
  return <main className="cm-workspace min-h-full p-5 lg:p-8"><header className="cm-page-heading"><p className="cm-eyebrow">MONITOR</p><h1 className="text-2xl font-bold">Mis avances</h1><p className="mt-1 text-sm text-[var(--cm-text-secondary)]">Tu actividad se filtra automáticamente por tu usuario.</p></header>
    <section className="cm-card mt-5 flex flex-wrap gap-3 p-4"><select value={period} onChange={e=>setPeriod(e.target.value)} className="cm-select min-w-44 p-2"><option value="TODAY">Hoy</option><option value="WEEK">Esta semana</option><option value="MONTH">Este mes</option><option value="CUSTOM">Rango personalizado</option></select>{period==='CUSTOM'&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="cm-input p-2"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="cm-input p-2"/></>}</section>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={<CheckSquare className="h-5 w-5"/>} label="Evaluaciones realizadas" value={all.length}/><Metric icon={<MessageSquare className="h-5 w-5"/>} label="Feedbacks generados" value={feedbacks.length}/><Metric icon={<BookOpen className="h-5 w-5"/>} label="Cápsulas creadas" value={capsules.length}/><Metric icon={<Users className="h-5 w-5"/>} label="Asesores evaluados" value={new Set(all.map(e=>e.advisorId)).size}/><Metric icon={<MessageSquare className="h-5 w-5"/>} label="Feedbacks pendientes" value={feedbacks.filter(f=>f.status==='PENDIENTE').length}/><Metric icon={<BarChart3 className="h-5 w-5"/>} label="Evaluaciones del período" value={evaluations.length}/></div>
    <EvaluationTable title="Mis evaluaciones" items={evaluations} advisors={advisors} campaigns={campaigns} onSelect={onSelectEvaluation}/>
    <section className="cm-card mt-4 overflow-hidden"><header className="border-b border-[var(--cm-border)] p-4"><h2 className="font-bold">Mis feedbacks</h2></header><div className="overflow-x-auto"><table className="cm-table min-w-[700px] text-left text-xs"><thead><tr><th>Fecha</th><th>Asesor</th><th>Evaluación</th><th>Estado</th><th>Última actualización</th><th>Acción</th></tr></thead><tbody>{periodFeedbacks.map(f=><tr key={f.feedback_id}><td>{f.created_at.slice(0,10)}</td><td>{advisors.find(a=>a.id===f.advisor_id)?.name||'—'}</td><td>{f.evaluation_id}</td><td><span className="cm-badge">{label(f.status)}</span></td><td>{f.updated_at.slice(0,16).replace('T',' ')}</td><td><button onClick={()=>onNavigate('feedback')} className="cm-button-secondary px-2 py-1"><Eye className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></section>
    <section className="cm-card mt-4 overflow-hidden"><header className="border-b border-[var(--cm-border)] p-4"><h2 className="font-bold">Mis cápsulas</h2></header><div className="overflow-x-auto"><table className="cm-table min-w-[700px] text-left text-xs"><thead><tr><th>Fecha</th><th>Nombre</th><th>Tema</th><th>Estado</th><th>Asignaciones</th><th>Completados</th><th>Acción</th></tr></thead><tbody>{periodCapsules.map(c=>{const own=assignments.filter(a=>a.capsuleId===c.id);return <tr key={c.id}><td>{c.createdAt?.slice(0,10)||'—'}</td><td>{c.title}</td><td>{c.gap||'—'}</td><td><span className="cm-badge">{label(c.status)}</span></td><td>{own.length}</td><td>{own.filter(a=>a.status==='COMPLETADA').length}</td><td><button onClick={()=>onNavigate('development')} className="cm-button-secondary px-2 py-1"><Eye className="h-4 w-4"/></button></td></tr>})}</tbody></table></div></section>
  </main>;
};

const EvaluationTable=({title,items,advisors,campaigns,onSelect}:{title:string;items:Evaluation[];advisors:any[];campaigns:any[];onSelect:(e:Evaluation)=>void})=><section className="cm-card mt-4 overflow-hidden"><header className="border-b border-[var(--cm-border)] p-4"><h2 className="font-bold">{title}</h2></header><div className="overflow-x-auto"><table className="cm-table min-w-[780px] text-left text-xs"><thead><tr><th>Fecha</th><th>Hora</th><th>Asesor</th><th>Campaña</th><th>Resultado</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.time}</td><td>{advisors.find(a=>a.id===e.advisorId)?.name||'—'}</td><td>{campaigns.find(c=>c.id===e.campaignId)?.name||'—'}</td><td><b className="text-[var(--cm-primary)]">{score(e)}%</b></td><td><span className="cm-badge">{e.qualityStatus==='DRAFT'?'Borrador':'Finalizada'}</span></td><td><button onClick={()=>onSelect(e)} className="cm-button-secondary px-2 py-1"><Eye className="h-4 w-4"/> Ver detalle</button></td></tr>)}</tbody></table></div></section>;
