import React,{useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useApp} from '../../context/AppContext';
import {ImportAdvisorsModal} from './ImportAdvisorsModal';
import {CampaignManagerModal} from './CampaignManagerModal';
import {Download,FileSpreadsheet,Pencil,Plus,X} from 'lucide-react';

interface Props { onSelectAdvisor:(id:string)=>void; onOpenNewAdvisor:()=>void; }
const nameParts=(name:string)=>{const p=name.trim().split(/\s+/);return {first:p[0]||'—',last:p.slice(1).join(' ')||'—'};};
const operationLabel=(operation:any,campaigns:any[])=>campaigns.find(c=>c.id===operation?.campaignId)?.name||operation?.name||'—';

export const AdvisorsList:React.FC<Props>=({onSelectAdvisor,onOpenNewAdvisor})=>{
 const {currentUser,advisors,users,campaigns,companies,operations,updateAdvisor}=useApp();
 const [query,setQuery]=useState(''),[companyId,setCompanyId]=useState(''),[operationId,setOperationId]=useState(''),[supervisorId,setSupervisorId]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<any>(null),[importOpen,setImportOpen]=useState(false),[campaignsOpen,setCampaignsOpen]=useState(false),[bulk,setBulk]=useState<'SUPERVISOR'|'OPERATION'|null>(null),[bulkSupervisor,setBulkSupervisor]=useState(''),[bulkOperation,setBulkOperation]=useState('');
 const canManage=['ADMINISTRADOR','CONSULTOR'].includes(currentUser.role);
 const activeCompanies=companies.filter(c=>c.status==='ACTIVA');
 const selectedOperation=operations.find(o=>o.id===operationId);
 const availableOperations=operations.filter(o=>o.status==='ACTIVA'&&(!companyId||o.companyId===companyId));
 const supervisors=users.filter(u=>u.status==='ACTIVO'&&['SUPERVISOR','FORMADOR','ADMINISTRADOR','CONSULTOR'].includes(u.role));
 const operationSupervisors=(id:string)=>supervisors.filter(u=>['ADMINISTRADOR','CONSULTOR'].includes(u.role)||advisors.some(a=>a.operationId===id&&a.supervisorId===u.id));
 const rows=useMemo(()=>advisors.filter(a=>{const op=operations.find(o=>o.id===a.operationId)||operations.find(o=>o.id===`op_legacy_${a.campaignId}`);const text=`${a.name} ${a.supervisor||users.find(u=>u.id===a.supervisorId)?.name||''}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(!companyId||op?.companyId===companyId)&&(!operationId||a.operationId===operationId)&&(!supervisorId||a.supervisorId===supervisorId);}),[advisors,operations,query,companyId,operationId,supervisorId,users]);
 const counts:Record<string,number>={total:advisors.length,unsupervised:advisors.filter(a=>!a.supervisorId).length,...Object.fromEntries(['TECHCENTER','TALENT UP','KONECTADOS'].map(name=>[name,advisors.filter(a=>companies.find(c=>c.id===operations.find(o=>o.id===a.operationId)?.companyId)?.name===name).length]))};
 const exportRows=()=>{const body=['Nombre,Apellido,Supervisor,Empresa,Campaña',...rows.map(a=>{const op=operations.find(o=>o.id===a.operationId);return [nameParts(a.name).first,nameParts(a.name).last,users.find(u=>u.id===a.supervisorId)?.name||a.supervisor||'',companies.find(c=>c.id===op?.companyId)?.name||'',operationLabel(op,campaigns)].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',');})].join('\n');const url=URL.createObjectURL(new Blob([body],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='dotacion.csv';link.click();URL.revokeObjectURL(url);};
 const applyUpdate=(advisor:any,operation:string,supervisor:string)=>{const op=operations.find(o=>o.id===operation);if(!op)return;updateAdvisor(advisor.id,{operationId:op.id,campaignId:op.campaignId,supervisorId:supervisor,teamId:''});};
 const openEdit=(advisor:any,operation:any)=>{const parts=nameParts(advisor.name);setEditing({...advisor,firstName:parts.first==='—'?'':parts.first,lastName:parts.last==='—'?'':parts.last,operationId:advisor.operationId||operation?.id||''});};
 const saveEdit=()=>{if(!editing)return;const name=`${editing.firstName||''} ${editing.lastName||''}`.trim();if(!name||!editing.operationId)return;const op=operations.find(item=>item.id===editing.operationId);if(!op)return;updateAdvisor(editing.id,{name,operationId:op.id,campaignId:op.campaignId,supervisorId:editing.supervisorId,teamId:''});setEditing(null);};
 const applyBulk=()=>{if(!selected.length)return;const op=bulk==='OPERATION'?bulkOperation:'';if(bulk==='OPERATION'&&!op)return;if(bulk==='SUPERVISOR'&&!bulkSupervisor)return;selected.forEach(id=>{const a=advisors.find(x=>x.id===id);if(a)applyUpdate(a,op||a.operationId||`op_legacy_${a.campaignId}`,bulk==='SUPERVISOR'?bulkSupervisor:bulkSupervisor);});setSelected([]);setBulk(null);};
 if(currentUser.role==='ASESOR')return <div className="cm-workspace p-6"><div className="cm-card p-6 text-sm">No tienes acceso administrativo a Dotación.</div></div>;
 return <div className="cm-workspace flex-1 overflow-y-auto"><div className="mx-auto w-full max-w-7xl space-y-4 p-4 sm:p-6"><header><h2 className="font-heading text-xl font-bold">Dotación</h2><p className="mt-1 text-xs text-[var(--cm-text-secondary)]">Gestión de colaboradores y asignaciones operativas.</p></header>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Total colaboradores',counts.total],['Techcenter',counts.TECHCENTER||0],['Talent UP',counts['TALENT UP']||0],['Konectados',counts.KONECTADOS||0],['Sin supervisor',counts.unsupervised]].map(([label,value])=><div key={String(label)} className="cm-card p-4"><span className="text-xs text-[var(--cm-text-secondary)]">{label}</span><b className="mt-1 block text-2xl font-kpi">{value}</b></div>)}</section>
 <section className="cm-card grid gap-2 p-3 md:grid-cols-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre o apellido" className="cm-input px-3 py-2"/><select value={companyId} onChange={e=>{setCompanyId(e.target.value);setOperationId('');setSupervisorId('')}} className="cm-select px-3 py-2"><option value="">Todas las empresas</option>{activeCompanies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={operationId} onChange={e=>setOperationId(e.target.value)} className="cm-select px-3 py-2"><option value="">Todas las campañas</option>{availableOperations.map(o=><option key={o.id} value={o.id}>{operationLabel(o,campaigns)}</option>)}</select><select value={supervisorId} onChange={e=>setSupervisorId(e.target.value)} className="cm-select px-3 py-2"><option value="">Todos los supervisores</option>{supervisors.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></section>
 <div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs text-[var(--cm-text-secondary)]">{rows.length} colaboradores</div><div className="flex flex-wrap gap-2">{currentUser.role==='ADMINISTRADOR'&&<button onClick={()=>setCampaignsOpen(true)} className="cm-button-secondary px-3 py-2 text-xs">Gestionar campañas</button>}<button onClick={exportRows} className="cm-button-secondary inline-flex items-center gap-1 px-3 py-2 text-xs"><Download className="h-4 w-4"/>Exportar</button>{canManage&&<><button onClick={()=>setImportOpen(true)} className="cm-button-secondary inline-flex items-center gap-1 px-3 py-2 text-xs"><FileSpreadsheet className="h-4 w-4"/>Importar</button><button onClick={onOpenNewAdvisor} className="cm-button-primary inline-flex items-center gap-1 px-3 py-2 text-xs"><Plus className="h-4 w-4"/>Agregar colaborador</button></>}</div></div>
 {selected.length>0&&canManage&&<div className="cm-card flex flex-wrap items-center gap-2 p-3 text-xs"><b>{selected.length} seleccionados</b><button onClick={()=>setBulk('SUPERVISOR')} className="cm-button-secondary px-3 py-1.5">Cambiar supervisor</button><button onClick={()=>setBulk('OPERATION')} className="cm-button-secondary px-3 py-1.5">Cambiar empresa/campaña</button><button onClick={()=>setSelected([])} className="ml-auto text-[var(--cm-text-secondary)]">Limpiar</button></div>}
 <section className="cm-card overflow-hidden"><div className="overflow-x-auto"><table className="cm-table min-w-[800px] text-left text-xs"><thead><tr><th><input type="checkbox" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(a=>a.id):[])}/></th><th>Nombre</th><th>Apellido</th><th>Supervisor</th><th>Empresa</th><th>Campaña</th><th>Acciones</th></tr></thead><tbody>{rows.map(a=>{const op=operations.find(o=>o.id===a.operationId)||operations.find(o=>o.id===`op_legacy_${a.campaignId}`);const p=nameParts(a.name);const legacy=op?.legacy||op?.companyId==='company_legacy';return <tr key={a.id}><td><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,a.id]:s.filter(id=>id!==a.id))}/></td><td className="font-semibold">{p.first}</td><td>{p.last}</td><td>{users.find(u=>u.id===a.supervisorId)?.name||a.supervisor||'Sin supervisor'}</td><td>{legacy?<span className="cm-badge">Sin empresa</span>:companies.find(c=>c.id===op?.companyId)?.name||<span className="cm-badge">Sin empresa</span>}</td><td>{operationLabel(op,campaigns)}</td><td className="whitespace-nowrap">{canManage?<button onClick={()=>openEdit(a,op)} className="inline-flex items-center gap-1 font-semibold text-[var(--cm-primary)]"><Pencil className="h-3.5 w-3.5"/>Editar</button>:<span className="text-[var(--cm-text-secondary)]">Solo lectura</span>}</td></tr>;})}{!rows.length&&<tr><td colSpan={7} className="p-8 text-center text-[var(--cm-text-secondary)]">No hay colaboradores para los filtros seleccionados.</td></tr>}</tbody></table></div></section></div>
 {editing&&<RosterModal title="Editar colaborador" onClose={()=>setEditing(null)}><div className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Nombre<input value={editing.firstName||''} onChange={e=>setEditing({...editing,firstName:e.target.value})} className="cm-input mt-1 w-full px-3 py-2"/></label><label className="text-xs font-semibold">Apellido<input value={editing.lastName||''} onChange={e=>setEditing({...editing,lastName:e.target.value})} className="cm-input mt-1 w-full px-3 py-2"/></label></div><OperationSelect companyId={operations.find(o=>o.id===editing.operationId)?.companyId||''} operationId={editing.operationId||''} companies={activeCompanies} operations={operations} campaigns={campaigns} onChange={id=>setEditing({...editing,operationId:id})}/><SupervisorSelect value={editing.supervisorId||''} users={supervisors} onChange={id=>setEditing({...editing,supervisorId:id})}/><div className="mt-2 flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="cm-button-secondary px-4 py-2">Cancelar</button><button disabled={!editing.firstName?.trim()||!editing.lastName?.trim()||!editing.operationId} onClick={saveEdit} className="cm-button-primary px-4 py-2">Guardar cambios</button></div></div></RosterModal>}
 {bulk&&<RosterModal title={bulk==='SUPERVISOR'?'Cambiar supervisor':'Cambiar empresa/campaña'} onClose={()=>setBulk(null)}><p className="mb-3 text-sm">{selected.length} colaboradores seleccionados</p>{bulk==='OPERATION'&&<OperationSelect companyId={operations.find(o=>o.id===bulkOperation)?.companyId||''} operationId={bulkOperation} companies={activeCompanies} operations={operations} campaigns={campaigns} onChange={setBulkOperation}/>}<SupervisorSelect value={bulkSupervisor} users={bulk==='OPERATION'?operationSupervisors(bulkOperation):supervisors} onChange={setBulkSupervisor}/><button onClick={applyBulk} className="cm-button-primary mt-4 ml-auto block px-4 py-2">Confirmar cambio</button></RosterModal>}
 {importOpen&&<ImportAdvisorsModal onClose={()=>setImportOpen(false)}/>} {campaignsOpen&&<CampaignManagerModal onClose={()=>setCampaignsOpen(false)}/>}</div>;
};
const RosterModal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=>createPortal(<div role="dialog" aria-modal="true" className="fixed inset-0 z-[250] flex items-center justify-center overflow-y-auto bg-slate-950/70 p-4 backdrop-blur-sm"><div className="cm-modal my-auto w-full max-w-lg p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">{title}</h3><button onClick={onClose} aria-label="Cerrar"><X className="h-5 w-5"/></button></div>{children}</div></div>,document.body);
const OperationSelect=({companyId,operationId,companies,operations,campaigns,onChange}:{companyId:string;operationId:string;companies:any[];operations:any[];campaigns:any[];onChange:(id:string)=>void})=>{const [company,setCompany]=useState(companyId);const available=operations.filter(o=>o.status==='ACTIVA'&&o.companyId===company);return <><label className="text-xs font-semibold">Empresa<select value={company} onChange={e=>{setCompany(e.target.value);onChange('')}} className="cm-select mt-1 w-full px-2 py-2"><option value="">Seleccionar</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-semibold">Campaña<select value={operationId} disabled={!company} onChange={e=>onChange(e.target.value)} className="cm-select mt-1 w-full px-2 py-2"><option value="">Seleccionar</option>{available.map(o=><option key={o.id} value={o.id}>{operationLabel(o,campaigns)}</option>)}</select></label></>};
const SupervisorSelect=({value,users,onChange}:{value:string;users:any[];onChange:(id:string)=>void})=><label className="mt-3 block text-xs font-semibold">Supervisor<select required value={value} onChange={e=>onChange(e.target.value)} className="cm-select mt-1 w-full px-2 py-2"><option value="">Seleccionar</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>;
