import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { CheckCircle2, ClipboardCheck, Plus, X } from 'lucide-react';
import { calibrationsApi } from '../../api/sharedRepository';
import { useApp } from '../../context/AppContext';
import type { Calibration, ComplianceStatus, Evaluation } from '../../types';
import { AudioPlayer } from '../common/AudioPlayer';

const label:Record<string,string>={PENDIENTE:'Pendiente',EN_CURSO:'En curso',COMPLETADA:'Completada',VENCIDA:'Vencida',RESPONDIDA:'Respondida'};
export const CalibrationsView:React.FC=()=>{
 const {currentUser,evaluations,users,campaigns}=useApp(); const [items,setItems]=useState<Calibration[]>([]); const [createOpen,setCreateOpen]=useState(false); const [responding,setResponding]=useState<Calibration|null>(null); const [evaluationId,setEvaluationId]=useState(''); const [title,setTitle]=useState(''); const [dueAt,setDueAt]=useState(''); const [supervisorIds,setSupervisorIds]=useState<string[]>([]); const [answers,setAnswers]=useState<Record<string,ComplianceStatus>>({}); const [busy,setBusy]=useState(false);
 const canCreate=['ADMINISTRADOR','CONSULTOR'].includes(currentUser.role); const supervisors=users.filter(user=>user.role==='SUPERVISOR'&&user.status==='ACTIVO'); const qualityEvaluations=evaluations.filter(item=>item.evaluationType==='QUALITY');
 const reload=()=>calibrationsApi.list().then(data=>setItems(data.calibrations));useEffect(()=>{void reload();},[]);
 const metrics=useMemo(()=>{const participants=items.flatMap(item=>item.participants||[]);const responded=participants.filter(item=>item.status==='RESPONDIDA');return{global:responded.length?Math.round(responded.reduce((sum,item)=>sum+(item.agreement||0),0)/responded.length):null,sent:participants.length,responded:responded.length,pending:participants.filter(item=>item.status==='PENDIENTE').length,expired:participants.filter(item=>item.status==='VENCIDA').length};},[items]);
 const bySupervisor=supervisors.map(supervisor=>{const rows=items.flatMap(item=>item.participants||[]).filter(row=>row.supervisorId===supervisor.id&&row.agreement!==undefined);return{name:supervisor.name,agreement:rows.length?Math.round(rows.reduce((sum,row)=>sum+(row.agreement||0),0)/rows.length):null};});
 const discrepancies=useMemo(()=>{const map:Record<string,{label:string,total:number,different:number}>={};for(const calibration of items){for(const participant of calibration.participants||[]){if(!participant.answers||!calibration.officialAnswers)continue;for(const [id,answer] of Object.entries(participant.answers)){const row=map[id]||={label:calibration.attributeLabels?.[id]||id,total:0,different:0};row.total++;if(answer!==calibration.officialAnswers[id])row.different++;}}}return Object.values(map).sort((a,b)=>b.different-a.different).slice(0,5);},[items]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();const evaluation=qualityEvaluations.find(item=>item.id===evaluationId);if(!evaluation)return;setBusy(true);try{await calibrationsApi.create({title:title||`Calibración ${evaluation.callId}`,dueAt,evaluation,supervisorIds});setCreateOpen(false);setEvaluationId('');setSupervisorIds([]);await reload();}finally{setBusy(false);}};
 const submit=async()=>{if(!responding)return;setBusy(true);try{await calibrationsApi.respond(responding.id,answers);setResponding(null);setAnswers({});await reload();}finally{setBusy(false);}};
 return <main className="cm-workspace flex-1 overflow-y-auto p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5"><header className="cm-page-heading flex items-center justify-between"><div><p className="cm-eyebrow">CONSISTENCIA DE EVALUACIÓN</p><h1 className="text-xl font-bold">Calibraciones</h1><p className="text-xs text-[var(--cm-text-secondary)]">Evaluación ciega y agreement por atributo.</p></div>{canCreate&&<button onClick={()=>setCreateOpen(true)} className="cm-button-primary px-4 py-2 text-xs"><Plus className="h-4 w-4"/>Nueva calibración</button>}</header>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Agreement global',metrics.global===null?'—':`${metrics.global}%`],['Invitaciones',metrics.sent],['Respondidas',metrics.responded],['Pendientes',metrics.pending],['Vencidas',metrics.expired]].map(([name,value])=><article key={name} className="cm-card p-4"><span className="text-xs text-[var(--cm-text-secondary)]">{name}</span><b className="mt-2 block text-2xl">{value}</b></article>)}</section>
 <div className="grid gap-4 lg:grid-cols-2"><section className="cm-card p-4"><h2 className="font-bold">Agreement por supervisor</h2><div className="mt-3 space-y-2">{bySupervisor.map(row=><div key={row.name} className="flex items-center justify-between rounded-lg border border-[var(--cm-border)] p-3 text-xs"><span>{row.name}</span><b>{row.agreement===null?'Sin respuestas':`${row.agreement}%`}</b></div>)}</div></section><section className="cm-card p-4"><h2 className="font-bold">Mayor discrepancia</h2><div className="mt-3 space-y-2">{discrepancies.length?discrepancies.map(row=><div key={row.label} className="flex items-center justify-between rounded-lg border border-[var(--cm-border)] p-3 text-xs"><span>{row.label}</span><b>{row.different}/{row.total}</b></div>):<p className="text-xs text-[var(--cm-text-secondary)]">Aún no hay resultados comparables.</p>}</div></section></div>
 <section className="cm-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-[var(--cm-border)]"><tr>{['Calibración','Campaña','Vencimiento','Invitaciones','Estado','Acción'].map(v=><th key={v} className="p-3">{v}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{items.map(item=>{const mine=item.participants?.find(row=>row.supervisorId===currentUser.id);return<tr key={item.id}><td className="p-3"><b>{item.title}</b><span className="block text-[var(--cm-text-secondary)]">{item.evaluationId}</span></td><td className="p-3">{campaigns.find(c=>c.id===item.campaignId)?.name||'—'}</td><td className="p-3">{item.dueAt||'—'}</td><td className="p-3">{item.participants.filter(p=>p.status==='RESPONDIDA').length}/{item.participants.length}</td><td className="p-3">{label[item.status]||item.status}</td><td className="p-3">{mine?.status==='PENDIENTE'?<button onClick={()=>setResponding(item)} className="text-[var(--cm-primary)]">Responder</button>:mine?<span>{label[mine.status]}</span>:<span>{item.status==='COMPLETADA'?'Ver resultado':'Seguimiento'}</span>}</td></tr>})}</tbody></table>{!items.length&&<p className="p-8 text-center text-sm text-[var(--cm-text-secondary)]">No hay calibraciones registradas.</p>}</div></section></div>
 {createOpen&&<Modal title="Nueva calibración" onClose={()=>setCreateOpen(false)}><form onSubmit={create} className="space-y-3"><Field label="Evaluación existente"><select required value={evaluationId} onChange={e=>setEvaluationId(e.target.value)} className="cm-select w-full"><option value="">Seleccionar evaluación validada</option>{qualityEvaluations.map(item=><option key={item.id} value={item.id}>{item.callId} · {item.date} · {item.technicalScore??item.scoreTotal}%</option>)}</select></Field><Field label="Título"><input value={title} onChange={e=>setTitle(e.target.value)} className="cm-input w-full"/></Field><Field label="Vencimiento"><input required type="date" value={dueAt} onChange={e=>setDueAt(e.target.value)} className="cm-input w-full"/></Field><Field label="Supervisores"><div className="grid gap-2 sm:grid-cols-2">{supervisors.map(user=><label key={user.id} className="flex items-center gap-2 rounded-lg border border-[var(--cm-border)] p-2"><input type="checkbox" checked={supervisorIds.includes(user.id)} onChange={e=>setSupervisorIds(current=>e.target.checked?[...current,user.id]:current.filter(id=>id!==user.id))}/>{user.name}</label>)}</div></Field><div className="flex justify-end gap-2"><button type="button" onClick={()=>setCreateOpen(false)} className="cm-button-secondary px-4 py-2">Cancelar</button><button disabled={busy||!supervisorIds.length} className="cm-button-primary px-4 py-2">Enviar invitaciones</button></div></form></Modal>}
 {responding&&<Modal title={responding.title} onClose={()=>setResponding(null)}><div className="space-y-3"><p className="text-xs text-[var(--cm-text-secondary)]">Caso {responding.caseSnapshot?.callId || responding.evaluationId} · {responding.caseSnapshot?.date}. La respuesta oficial permanecerá oculta hasta finalizar.</p>{responding.caseSnapshot?.audioUrl&&<AudioPlayer audioUrl={responding.caseSnapshot.audioUrl} audioFileName={responding.caseSnapshot.audioFileName} audioDurationSeconds={responding.caseSnapshot.audioDurationSeconds} readOnly/>}{Object.entries(responding.attributeLabels||{}).map(([id,name])=><label key={id} className="grid gap-2 rounded-lg border border-[var(--cm-border)] p-3 text-xs sm:grid-cols-[1fr_180px]"><span>{name}</span><select value={answers[id]||''} onChange={e=>setAnswers({...answers,[id]:e.target.value as ComplianceStatus})} className="cm-select"><option value="">Sin responder</option><option value="CUMPLE">Cumple</option><option value="NO_CUMPLE">No cumple</option><option value="NO_APLICA">No aplica</option></select></label>)}<div className="flex justify-end"><button disabled={busy||!Object.keys(answers).length} onClick={()=>void submit()} className="cm-button-primary px-4 py-2"><CheckCircle2 className="h-4 w-4"/>Finalizar calibración</button></div></div></Modal>}
 </main>;
};
const Modal:React.FC<{title:string;onClose:()=>void;children:React.ReactNode}>=({title,onClose,children})=>createPortal(<div className="fixed inset-0 z-[210] flex items-center justify-center overflow-y-auto bg-slate-950/65 p-4 backdrop-blur-sm"><div className="cm-modal max-h-[92vh] w-full max-w-2xl overflow-y-auto p-5"><header className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><ClipboardCheck className="h-5 w-5 text-[var(--cm-primary)]"/>{title}</h2><button onClick={onClose}><X className="h-5 w-5"/></button></header>{children}</div></div>,document.body);
const Field:React.FC<{label:string;children:React.ReactNode}>=({label,children})=><label className="block text-xs font-semibold">{label}<div className="mt-1">{children}</div></label>;
