import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Clock3, Plus, ShieldAlert, X } from 'lucide-react';
import { filesApi, qualityAlertsApi } from '../../api/sharedRepository';
import type { QualityAlert } from '../../types';
import { useApp } from '../../context/AppContext';
import { AudioPlayer } from '../common/AudioPlayer';

const statusLabel: Record<string,string> = { NUEVA:'Nueva',PENDIENTE_GESTION:'Pendiente de gestión',GESTIONADA:'Gestionada',CERRADA:'Cerrada' };
const empty = { title:'',contactNumber:'',detail:'',advisorId:'',validUntil:'',criticality:'MEDIA' as const };
export const QualityAlertsView: React.FC = () => {
  const { currentUser, advisors, campaigns, users } = useApp(); const [alerts,setAlerts]=useState<QualityAlert[]>([]); const [loading,setLoading]=useState(true); const [createOpen,setCreateOpen]=useState(false); const [manage,setManage]=useState<QualityAlert|null>(null); const [editing,setEditing]=useState<QualityAlert|null>(null); const [form,setForm]=useState(empty); const [audio,setAudio]=useState<File|null>(null); const [evidence,setEvidence]=useState<File|null>(null); const [managementDetail,setManagementDetail]=useState(''); const [busy,setBusy]=useState(false);
  const canPublish=['ADMINISTRADOR','CONSULTOR'].includes(currentUser.role); const canClose=canPublish;
  const reload=()=>qualityAlertsApi.list().then(data=>setAlerts(data.alerts)).finally(()=>setLoading(false)); useEffect(()=>{void reload();},[]);
  const advisor = advisors.find(item=>item.id===form.advisorId); const activeCampaigns=campaigns.filter(item=>item.status==='ACTIVA');
  const counts=useMemo(()=>Object.fromEntries(['NUEVA','PENDIENTE_GESTION','GESTIONADA','CERRADA'].map(status=>[status,alerts.filter(item=>item.status===status).length])),[alerts]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!advisor)return;setBusy(true);try{const audioUrl=audio?(await filesApi.upload(audio)).url:editing?.audioUrl;const payload={...form,audioUrl,supervisorId:advisor.supervisorId,campaignId:advisor.campaignId};if(editing)await qualityAlertsApi.update(editing.id,payload);else await qualityAlertsApi.create(payload);setCreateOpen(false);setEditing(null);setForm(empty);setAudio(null);await reload();}finally{setBusy(false);}};
  const submitManagement=async(status:'PENDIENTE_GESTION'|'GESTIONADA'|'CERRADA')=>{if(!manage)return;setBusy(true);try{const evidenceUrl=evidence?(await filesApi.upload(evidence)).url:manage.evidenceUrl;await qualityAlertsApi.update(manage.id,{status,feedbackPerformed:status!=='PENDIENTE_GESTION',managementDetail,evidenceUrl});setManage(null);setEvidence(null);setManagementDetail('');await reload();}finally{setBusy(false);}};
  return <main className="cm-workspace flex-1 overflow-y-auto p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5"><header className="cm-page-heading flex items-center justify-between"><div><p className="cm-eyebrow">GESTIÓN DE CALIDAD</p><h1 className="text-xl font-bold">Alertas de Calidad</h1><p className="text-xs text-[var(--cm-text-secondary)]">Publicación, gestión y cierre con trazabilidad de tiempos.</p></div>{canPublish&&<button onClick={()=>setCreateOpen(true)} className="cm-button-primary px-4 py-2 text-xs"><Plus className="h-4 w-4"/>Nueva alerta</button>}</header>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(counts).map(([status,count])=><article key={status} className="cm-card p-4"><span className="text-xs text-[var(--cm-text-secondary)]">{statusLabel[status]}</span><b className="mt-2 block text-2xl">{count}</b></article>)}</section>
  <section className="cm-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-[var(--cm-border)] text-[var(--cm-text-secondary)]"><tr>{['Alerta','Asesor / campaña','Vigencia','Criticidad','Estado','Tiempo de gestión','Acción'].map(value=><th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{alerts.map(item=><tr key={item.id}><td className="p-3"><b>{item.title}</b><span className="block text-[var(--cm-text-secondary)]">Gestión: {item.contactNumber||'—'}</span></td><td className="p-3">{advisors.find(a=>a.id===item.advisorId)?.name||'Asesor'}<span className="block text-[var(--cm-text-secondary)]">{campaigns.find(c=>c.id===item.campaignId)?.name||'Campaña'}</span></td><td className="p-3">{item.validUntil}</td><td className="p-3"><span className="cm-badge cm-badge--critical">{item.criticality}</span></td><td className="p-3">{statusLabel[item.status]}</td><td className="p-3">{item.elapsedMinutes===undefined?'Pendiente':`${item.elapsedMinutes} min`}</td><td className="p-3"><button onClick={()=>{setManage(item);setManagementDetail(item.managementDetail||'');}} className="text-[var(--cm-primary)]">Ver / gestionar</button></td></tr>)}</tbody></table>{!loading&&!alerts.length&&<p className="p-8 text-center text-sm text-[var(--cm-text-secondary)]">No hay alertas registradas.</p>}</div></section></div>
  {createOpen&&<Modal title={editing?'Editar alerta de Calidad':'Nueva alerta de Calidad'} onClose={()=>{setCreateOpen(false);setEditing(null)}}><form onSubmit={create} className="grid gap-3 sm:grid-cols-2"><Field label="Título"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="cm-input w-full"/></Field><Field label="Número de gestión/contacto"><input value={form.contactNumber} onChange={e=>setForm({...form,contactNumber:e.target.value})} className="cm-input w-full"/></Field><Field label="Asesor"><select required value={form.advisorId} onChange={e=>setForm({...form,advisorId:e.target.value})} className="cm-select w-full"><option value="">Seleccionar</option>{advisors.filter(a=>a.status==='ACTIVO').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Campaña"><div className="cm-input">{activeCampaigns.find(c=>c.id===advisor?.campaignId)?.name||'Se asigna según el asesor'}</div></Field><Field label="Vigencia"><input required type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})} className="cm-input w-full"/></Field><Field label="Criticidad"><select value={form.criticality} onChange={e=>setForm({...form,criticality:e.target.value as any})} className="cm-select w-full">{['BAJA','MEDIA','ALTA','CRITICA'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Detalle" wide><textarea required rows={4} value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})} className="cm-input w-full"/></Field><Field label="Audio" wide><input type="file" accept="audio/*,.mp3,.mpeg" onChange={e=>setAudio(e.target.files?.[0]||null)} className="text-xs"/></Field><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={()=>{setCreateOpen(false);setEditing(null)}} className="cm-button-secondary px-4 py-2">Cancelar</button><button disabled={busy} className="cm-button-primary px-4 py-2">{editing?'Guardar cambios':'Publicar alerta'}</button></div></form></Modal>}
  {manage&&<Modal title={manage.title} onClose={()=>setManage(null)}><div className="space-y-4"><p className="text-sm">{manage.detail}</p>{manage.audioUrl&&<AudioPlayer audioUrl={`/api/quality-alerts/${manage.id}/audio`} audioFileName="Audio de alerta" readOnly/>}<div className="grid gap-2 sm:grid-cols-2"><Info label="Asesor" value={advisors.find(a=>a.id===manage.advisorId)?.name||'—'}/><Info label="Supervisor" value={users.find(u=>u.id===manage.supervisorId)?.name||'—'}/><Info label="Estado" value={statusLabel[manage.status]}/><Info label="Tiempo" value={manage.elapsedMinutes===undefined?'Pendiente':`${manage.elapsedMinutes} min`}/></div>{currentUser.role==='SUPERVISOR'&&(manage.supervisorIds||[manage.supervisorId]).includes(currentUser.id)&&manage.status!=='CERRADA'&&<><Field label="Detalle del feedback"><textarea rows={4} value={managementDetail} onChange={e=>setManagementDetail(e.target.value)} className="cm-input w-full"/></Field><Field label="Evidencia / foto"><input type="file" accept="image/*" onChange={e=>setEvidence(e.target.files?.[0]||null)} className="text-xs"/></Field><div className="flex justify-end gap-2"><button disabled={busy} onClick={()=>void submitManagement('PENDIENTE_GESTION')} className="cm-button-secondary px-3 py-2">Marcar pendiente</button><button disabled={busy||!managementDetail.trim()} onClick={()=>void submitManagement('GESTIONADA')} className="cm-button-primary px-3 py-2">Registrar gestión</button></div></>}{canClose&&<div className="flex gap-2"><button onClick={()=>{setForm({title:manage.title,contactNumber:manage.contactNumber,detail:manage.detail,advisorId:manage.advisorId,validUntil:manage.validUntil,criticality:manage.criticality});setEditing(manage);setManage(null);setCreateOpen(true)}} className="cm-button-secondary px-3 py-2">Editar</button>{manage.status==='GESTIONADA'&&<button onClick={()=>void submitManagement('CERRADA')} className="cm-button-primary px-3 py-2">Cerrar alerta</button>}<button onClick={async()=>{if(confirm('¿Eliminar alerta?')){await qualityAlertsApi.remove(manage.id);setManage(null);await reload();}}} className="cm-button-secondary px-3 py-2 text-rose-400">Eliminar</button></div>}</div></Modal>}
  </main>;
};
const Modal:React.FC<{title:string;onClose:()=>void;children:React.ReactNode}>=({title,onClose,children})=><div className="fixed inset-0 z-[210] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><div className="cm-modal max-h-[92vh] w-full max-w-2xl overflow-y-auto p-5"><header className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><ShieldAlert className="h-5 w-5 text-[var(--cm-primary)]"/>{title}</h2><button onClick={onClose}><X className="h-5 w-5"/></button></header>{children}</div></div>;
const Field:React.FC<{label:string;wide?:boolean;children:React.ReactNode}>=({label,wide,children})=><label className={`text-xs font-semibold ${wide?'sm:col-span-2':''}`}>{label}<div className="mt-1">{children}</div></label>;
const Info:React.FC<{label:string;value:string}>=({label,value})=><div className="rounded-lg border border-[var(--cm-border)] p-3"><span className="block text-[10px] text-[var(--cm-text-secondary)]">{label}</span><b className="text-xs">{value}</b></div>;
