import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, Plus } from 'lucide-react';
import { filesApi, memorandumsApi, qualityAlertsApi } from '../../api/sharedRepository';
import type { Memorandum, QualityAlert } from '../../types';
import { useApp } from '../../context/AppContext';
import { AudioPlayer } from '../common/AudioPlayer';
import { Modal as BaseModal } from '../ui';

const statusLabel: Record<string,string> = { NUEVA:'Nueva',PENDIENTE_GESTION:'Pendiente de gestión',GESTIONADA:'Gestionada',CERRADA:'Cerrada' };
const empty = { title:'',contactNumber:'',detail:'',advisorId:'',validUntil:'',criticality:'MEDIA' as const };
export const QualityAlertsView: React.FC = () => {
  const { currentUser, advisors, campaigns, users } = useApp(); const [alerts,setAlerts]=useState<QualityAlert[]>([]); const [loading,setLoading]=useState(true); const [createOpen,setCreateOpen]=useState(false); const [confirmSave,setConfirmSave]=useState(false); const [confirmClose,setConfirmClose]=useState(false); const [success,setSuccess]=useState(''); const [error,setError]=useState(''); const [manage,setManage]=useState<QualityAlert|null>(null); const [editing,setEditing]=useState<QualityAlert|null>(null); const [form,setForm]=useState(empty); const [audio,setAudio]=useState<File|null>(null); const [audioPreviewUrl,setAudioPreviewUrl]=useState(''); const [audioFileName,setAudioFileName]=useState(''); const [audioFileSize,setAudioFileSize]=useState(0); const [audioDurationSeconds,setAudioDurationSeconds]=useState(0); const [audioMimeType,setAudioMimeType]=useState(''); const [audioRemoved,setAudioRemoved]=useState(false); const [evidence,setEvidence]=useState<File|null>(null); const [managementDetail,setManagementDetail]=useState(''); const [busy,setBusy]=useState(false);
  const [memorandums,setMemorandums]=useState<Memorandum[]>([]); const [memoAlert,setMemoAlert]=useState<QualityAlert|null>(null); const [memoDraft,setMemoDraft]=useState({subject:'',content:'',actionRequired:''}); const [selectedMemo,setSelectedMemo]=useState<Memorandum|null>(null); const [annulReason,setAnnulReason]=useState('');
  const canPublish=['ADMINISTRADOR','CONSULTOR'].includes(currentUser.role); const canAdminister=canPublish;
  const reloadMemos=()=>memorandumsApi.list().then(data=>setMemorandums(data.memorandums)).catch(reason=>setError(reason instanceof Error?reason.message:'No fue posible cargar los memorándums.')); useEffect(()=>{void reloadMemos();},[]);
  const createMemo=async()=>{if(!memoAlert)return;setBusy(true);setError('');try{const {memorandum}=await memorandumsApi.create(memoAlert.id,memoDraft);setMemoAlert(null);setSelectedMemo(memorandum);await reloadMemos();}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible emitir el memorándum.');}finally{setBusy(false);}};
  const annulMemo=async()=>{if(!selectedMemo)return;setBusy(true);setError('');try{const {memorandum}=await memorandumsApi.annul(selectedMemo.id,annulReason);setSelectedMemo(memorandum);setAnnulReason('');await reloadMemos();}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible anular el memorándum.');}finally{setBusy(false);}};
  const reload=()=>qualityAlertsApi.list().then(data=>setAlerts(data.alerts)).catch(reason=>setError(reason instanceof Error?reason.message:'No fue posible cargar las alertas.')).finally(()=>setLoading(false)); useEffect(()=>{void reload();},[]);
  useEffect(()=>()=>{if(audioPreviewUrl.startsWith('blob:'))URL.revokeObjectURL(audioPreviewUrl);},[audioPreviewUrl]);
  const advisor = advisors.find(item=>item.id===form.advisorId); const activeCampaigns=campaigns.filter(item=>item.status==='ACTIVA');
  const visibleAlerts=useMemo(()=>currentUser.role==='ASESOR'?alerts.filter(item=>Boolean(currentUser.advisorId)&&item.advisorId===currentUser.advisorId):alerts,[alerts,currentUser.advisorId,currentUser.role]);
  const counts=useMemo(()=>Object.fromEntries(['NUEVA','PENDIENTE_GESTION','GESTIONADA','CERRADA'].map(status=>[status,visibleAlerts.filter(item=>item.status===status).length])),[visibleAlerts]);
  const requestSave=(e:React.FormEvent)=>{e.preventDefault();setError('');if(!advisor)return setError('Selecciona un asesor válido.');setConfirmSave(true);};
  const save=async()=>{if(!advisor)return;const wasEditing=Boolean(editing);setBusy(true);setError('');try{const uploaded=audio?await filesApi.upload(audio):null;const audioUrl=uploaded?.url||(audioRemoved?'':editing?.audioUrl);const payload={...form,audioUrl,audioFileName:uploaded?.name||(audioRemoved?'':audioFileName||editing?.audioFileName),audioFileSize:Number(uploaded?.size||audioFileSize||editing?.audioFileSize||0)||undefined,audioDurationSeconds:audioDurationSeconds||editing?.audioDurationSeconds,audioMimeType:uploaded?.mimeType||audioMimeType||editing?.audioMimeType,supervisorId:advisor.supervisorId,campaignId:advisor.campaignId};if(editing)await qualityAlertsApi.update(editing.id,payload);else await qualityAlertsApi.create(payload);setConfirmSave(false);setCreateOpen(false);setEditing(null);setForm(empty);setAudio(null);setAudioPreviewUrl('');setAudioFileName('');setAudioFileSize(0);setAudioDurationSeconds(0);setAudioMimeType('');setAudioRemoved(false);setSuccess(wasEditing?'Los cambios de la alerta se guardaron correctamente.':'La alerta se guardó y publicó correctamente.');await reload();window.dispatchEvent(new Event('cm:data-changed'));}catch(reason){setConfirmSave(false);setError(reason instanceof Error?reason.message:'No fue posible guardar la alerta.');}finally{setBusy(false);}};
  const submitManagement=async(status:'PENDIENTE_GESTION'|'CERRADA')=>{if(!manage)return;setBusy(true);setError('');try{if(evidence&&!evidence.type.startsWith('image/'))throw new Error('La evidencia opcional debe ser una imagen.');const evidenceUrl=evidence?(await filesApi.upload(evidence)).url:manage.evidenceUrl;await qualityAlertsApi.update(manage.id,{status,feedbackPerformed:status==='CERRADA',managementDetail,evidenceUrl});setConfirmClose(false);setManage(null);setEvidence(null);setManagementDetail('');setSuccess(status==='CERRADA'?'La alerta se cerró correctamente con el feedback registrado.':'La alerta quedó pendiente de gestión.');await reload();window.dispatchEvent(new Event('cm:data-changed'));}catch(reason){setConfirmClose(false);setError(reason instanceof Error?reason.message:'No fue posible actualizar la alerta.');}finally{setBusy(false);}};
  return <main className="cm-workspace flex-1 overflow-y-auto p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5"><header className="cm-page-heading flex items-center justify-between"><div><p className="cm-eyebrow">GESTIÓN DE CALIDAD</p><h1 className="text-xl font-bold">Alertas de Calidad</h1><p className="text-xs text-[var(--cm-text-secondary)]">Publicación, gestión y cierre con trazabilidad de tiempos.</p></div>{canPublish&&<button onClick={()=>{setError('');setEditing(null);setForm(empty);setAudio(null);setAudioPreviewUrl('');setAudioFileName('');setAudioFileSize(0);setAudioDurationSeconds(0);setAudioMimeType('');setAudioRemoved(false);setCreateOpen(true)}} className="cm-button-primary px-4 py-2 text-xs"><Plus className="h-4 w-4"/>Nueva alerta</button>}</header>{error&&!createOpen&&<p role="alert" className="rounded-xl border border-rose-400/40 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</p>}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(counts).map(([status,count])=><article key={status} className="cm-card p-4"><span className="text-xs text-[var(--cm-text-secondary)]">{statusLabel[status]}</span><b className="mt-2 block text-2xl">{count}</b></article>)}</section>
  <section className="cm-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-[var(--cm-border)] text-[var(--cm-text-secondary)]"><tr>{['Alerta','Asesor / campaña','Vigencia','Criticidad','Estado','Tiempo de gestión','Acción'].map(value=><th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{visibleAlerts.map(item=><tr key={item.id}><td className="p-3"><b>{item.title}</b><span className="block text-[var(--cm-text-secondary)]">Gestión: {item.contactNumber||'—'}</span></td><td className="p-3">{advisors.find(a=>a.id===item.advisorId)?.name||'Asesor'}<span className="block text-[var(--cm-text-secondary)]">{campaigns.find(c=>c.id===item.campaignId)?.name||'Campaña'}</span></td><td className="p-3">{item.validUntil}</td><td className="p-3"><span className="cm-badge cm-badge--critical">{item.criticality}</span></td><td className="p-3">{statusLabel[item.status]}</td><td className="p-3">{item.elapsedMinutes===undefined?'Pendiente':`${item.elapsedMinutes} min`}</td><td className="p-3"><button onClick={()=>{setManage(item);setManagementDetail(item.managementDetail||'');}} className="text-[var(--cm-primary)]">Ver / gestionar</button></td></tr>)}</tbody></table>{!loading&&!visibleAlerts.length&&<p className="p-8 text-center text-sm text-[var(--cm-text-secondary)]">No hay alertas registradas.</p>}</div></section>
  <section className="cm-card overflow-hidden"><header className="border-b border-[var(--cm-border)] p-4"><h2 className="font-bold">Memorándums ({memorandums.length})</h2><p className="text-xs text-[var(--cm-text-secondary)]">Documentos emitidos desde alertas, conservados en el historial del asesor.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr>{['Número / fecha','Asesor','Alerta','Estado','Acción'].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{memorandums.map(memo=><tr key={memo.id} className="border-t border-[var(--cm-border)]"><td className="p-3"><b>{memo.number}</b><span className="block">{memo.createdAt.slice(0,10)}</span></td><td className="p-3">{memo.advisorName}</td><td className="p-3">{memo.alertTitle}</td><td className="p-3">{memo.status==='ANULADO'?'Anulado':'Emitido'}</td><td className="p-3"><button className="text-[var(--cm-primary)]" onClick={()=>setSelectedMemo(memo)}>Ver documento</button></td></tr>)}</tbody></table>{!memorandums.length&&<p className="p-5 text-sm text-[var(--cm-text-secondary)]">Aún no hay memorándums.</p>}</div></section></div>
  {createOpen&&<Modal title={editing?'Editar alerta de Calidad':'Nueva alerta de Calidad'} onClose={()=>{if(!busy){setCreateOpen(false);setEditing(null);setError('');setAudio(null);setAudioPreviewUrl('');}}}><form onSubmit={requestSave} className="grid gap-3 sm:grid-cols-2"><Field label="Título"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="cm-input w-full"/></Field><Field label="Número de gestión/contacto"><input value={form.contactNumber} onChange={e=>setForm({...form,contactNumber:e.target.value})} className="cm-input w-full"/></Field><Field label="Asesor *"><select required value={form.advisorId} onChange={e=>setForm({...form,advisorId:e.target.value})} className="cm-select w-full"><option value="">Seleccionar</option>{advisors.filter(a=>a.status==='ACTIVO').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Campaña"><div className="cm-input">{activeCampaigns.find(c=>c.id===advisor?.campaignId)?.name||'Se asigna según el asesor'}</div></Field><Field label="Vigencia"><input required type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})} className="cm-input w-full"/></Field><Field label="Criticidad"><select value={form.criticality} onChange={e=>setForm({...form,criticality:e.target.value as any})} className="cm-select w-full">{['BAJA','MEDIA','ALTA','CRITICA'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Detalle" wide><textarea required rows={4} value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})} className="cm-input w-full"/></Field><Field label="Audio de la alerta (opcional)" wide><AudioPlayer audioUrl={audioPreviewUrl} audioFileName={audioFileName} audioFileSize={audioFileSize} audioDurationSeconds={audioDurationSeconds||undefined} busy={busy} compact onAudioUpload={(file,url,duration)=>{setAudio(file);setAudioPreviewUrl(url);setAudioFileName(file.name);setAudioFileSize(file.size);setAudioDurationSeconds(duration);setAudioMimeType(file.type);setAudioRemoved(false);}} onRemoveAudio={()=>{setAudio(null);setAudioPreviewUrl('');setAudioFileName('');setAudioFileSize(0);setAudioDurationSeconds(0);setAudioMimeType('');setAudioRemoved(true);}}/></Field>{error&&<p role="alert" className="rounded-lg border border-rose-400/40 bg-rose-500/10 p-3 text-xs text-rose-300 sm:col-span-2">{error}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><button type="button" disabled={busy} onClick={()=>{setCreateOpen(false);setEditing(null);setError('');setAudio(null);setAudioPreviewUrl('')}} className="cm-button-secondary px-4 py-2">Cancelar</button><button disabled={busy} className="cm-button-primary px-4 py-2">{editing?'Revisar cambios':'Revisar y publicar'}</button></div></form></Modal>}
  {confirmSave&&<Modal title={editing?'Confirmar cambios':'Confirmar publicación'} onClose={()=>!busy&&setConfirmSave(false)}><div className="space-y-4"><p className="text-sm text-[var(--cm-text-secondary)]">¿Confirmas que deseas {editing?'guardar los cambios de':'publicar'} la alerta <b className="text-[var(--cm-text)]">{form.title}</b>?</p><div className="rounded-lg border border-[var(--cm-border)] bg-[var(--cm-surface-elevated)] p-3 text-xs"><b>{advisor?.name}</b><span className="mt-1 block text-[var(--cm-text-secondary)]">{activeCampaigns.find(c=>c.id===advisor?.campaignId)?.name||'Campaña'} · {form.criticality} · vence {form.validUntil}</span></div><div className="flex justify-end gap-2"><button disabled={busy} onClick={()=>setConfirmSave(false)} className="cm-button-secondary px-4 py-2">Volver</button><button disabled={busy} onClick={()=>void save()} className="cm-button-primary px-4 py-2">{busy?'Guardando…':editing?'Sí, guardar':'Sí, publicar'}</button></div></div></Modal>}
  {success&&<Modal title="Alerta guardada" onClose={()=>setSuccess('')}><div className="text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-400"/><p className="mt-3 text-sm">{success}</p><button autoFocus onClick={()=>setSuccess('')} className="cm-button-primary mt-5 px-5 py-2">Aceptar</button></div></Modal>}
  {manage&&<Modal title={manage.title} onClose={()=>{if(!busy){setManage(null);setEvidence(null);setError('');}}}><div className="space-y-4">
    <p className="text-sm">{manage.detail}</p>
    {manage.audioUrl&&<AudioPlayer audioUrl={`/api/quality-alerts/${manage.id}/audio`} audioFileName={manage.audioFileName||'Audio de alerta'} audioFileSize={manage.audioFileSize} audioDurationSeconds={manage.audioDurationSeconds} readOnly/>}
    <div className="grid gap-2 sm:grid-cols-2"><Info label="Asesor" value={advisors.find(a=>a.id===manage.advisorId)?.name||'—'}/><Info label="Supervisor" value={users.find(u=>u.id===manage.supervisorId)?.name||'—'}/><Info label="Estado" value={statusLabel[manage.status]}/><Info label="Tiempo" value={manage.elapsedMinutes===undefined?'Pendiente':`${manage.elapsedMinutes} min`}/></div>
    {manage.status==='CERRADA'&&manage.managementDetail&&<div className="rounded-lg border border-emerald-400/30 bg-emerald-500/10 p-3"><b className="text-xs text-emerald-300">Feedback de cierre</b><p className="mt-1 text-sm">{manage.managementDetail}</p>{manage.evidenceUrl&&<img src={manage.evidenceUrl} alt="Evidencia del feedback" className="mt-3 max-h-64 rounded-lg border border-[var(--cm-border)] object-contain"/>}</div>}
    {currentUser.role==='SUPERVISOR'&&(manage.supervisorIds||[manage.supervisorId]).includes(currentUser.id)&&manage.status!=='CERRADA'&&<><Field label="Texto del feedback *"><textarea required rows={4} value={managementDetail} onChange={e=>setManagementDetail(e.target.value)} placeholder="Describe el feedback realizado al asesor..." className="cm-input w-full"/></Field><Field label="Imagen de evidencia (opcional)"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setEvidence(e.target.files?.[0]||null)} className="text-xs"/>{evidence&&<span className="mt-1 block text-[10px] text-emerald-300">{evidence.name}</span>}</Field>{error&&<p role="alert" className="rounded-lg border border-rose-400/40 bg-rose-500/10 p-3 text-xs text-rose-300">{error}</p>}<div className="flex justify-end gap-2"><button disabled={busy} onClick={()=>void submitManagement('PENDIENTE_GESTION')} className="cm-button-secondary px-3 py-2">Dejar pendiente</button><button disabled={busy||!managementDetail.trim()} onClick={()=>setConfirmClose(true)} className="cm-button-primary px-3 py-2">Cerrar alerta</button></div></>}
    {canAdminister&&<div className="flex flex-wrap gap-2">{currentUser.role==='ADMINISTRADOR'&&(memorandums.find(item=>item.alertId===manage.id)?<button onClick={()=>{setSelectedMemo(memorandums.find(item=>item.alertId===manage.id)!);setManage(null);}} className="cm-button-primary px-3 py-2">Ver memorándum</button>:<button onClick={()=>{setMemoAlert(manage);setMemoDraft({subject:`Memorándum por alerta: ${manage.title}`,content:manage.detail,actionRequired:''});setError('');setManage(null);}} className="cm-button-primary px-3 py-2">Generar memorándum</button>)}<button onClick={()=>{setForm({title:manage.title,contactNumber:manage.contactNumber,detail:manage.detail,advisorId:manage.advisorId,validUntil:manage.validUntil,criticality:manage.criticality});setAudio(null);setAudioPreviewUrl(manage.audioUrl?`/api/quality-alerts/${manage.id}/audio`:'');setAudioFileName(manage.audioFileName||'Audio de alerta');setAudioFileSize(manage.audioFileSize||0);setAudioDurationSeconds(manage.audioDurationSeconds||0);setAudioMimeType(manage.audioMimeType||'');setAudioRemoved(false);setEditing(manage);setManage(null);setCreateOpen(true)}} className="cm-button-secondary px-3 py-2">Editar</button><button onClick={async()=>{if(confirm('¿Eliminar alerta?')){await qualityAlertsApi.remove(manage.id);setManage(null);await reload();}}} className="cm-button-secondary px-3 py-2 text-rose-400">Eliminar</button></div>}
  </div></Modal>}
  {confirmClose&&manage&&<Modal title="Confirmar cierre" onClose={()=>!busy&&setConfirmClose(false)}><div className="space-y-4"><p className="text-sm text-[var(--cm-text-secondary)]">¿Confirmas que realizaste el feedback al asesor y deseas cerrar esta alerta?</p><div className="rounded-lg border border-[var(--cm-border)] bg-[var(--cm-surface-elevated)] p-3 text-sm"><b>{advisors.find(a=>a.id===manage.advisorId)?.name||'Asesor'}</b><p className="mt-2 whitespace-pre-wrap text-xs">{managementDetail}</p>{evidence&&<span className="mt-2 block text-xs text-emerald-300">Imagen: {evidence.name}</span>}</div><div className="flex justify-end gap-2"><button disabled={busy} onClick={()=>setConfirmClose(false)} className="cm-button-secondary px-4 py-2">Volver</button><button disabled={busy||!managementDetail.trim()} onClick={()=>void submitManagement('CERRADA')} className="cm-button-primary px-4 py-2">{busy?'Cerrando…':'Sí, cerrar alerta'}</button></div></div></Modal>}
  {memoAlert&&<Modal title="Generar memorándum" onClose={()=>!busy&&setMemoAlert(null)}><form onSubmit={event=>{event.preventDefault();void createMemo();}} className="space-y-3 text-sm"><p>Asesor: <b>{advisors.find(item=>item.id===memoAlert.advisorId)?.name||'—'}</b></p><p className="text-xs text-[var(--cm-text-secondary)]">Alerta: {memoAlert.title}. El documento quedará en el historial del asesor.</p><Field label="Asunto"><input required maxLength={180} className="cm-input w-full" value={memoDraft.subject} onChange={event=>setMemoDraft({...memoDraft,subject:event.target.value})}/></Field><Field label="Hechos"><textarea required rows={5} maxLength={10000} className="cm-input w-full" value={memoDraft.content} onChange={event=>setMemoDraft({...memoDraft,content:event.target.value})}/></Field><Field label="Acción requerida"><textarea required rows={3} maxLength={3000} className="cm-input w-full" value={memoDraft.actionRequired} onChange={event=>setMemoDraft({...memoDraft,actionRequired:event.target.value})}/></Field>{error&&<p role="alert" className="text-rose-300">{error}</p>}<div className="flex justify-end gap-2"><button type="button" disabled={busy} onClick={()=>setMemoAlert(null)} className="cm-button-secondary px-4 py-2">Cancelar</button><button disabled={busy} className="cm-button-primary px-4 py-2">{busy?'Guardando…':'Emitir memorándum'}</button></div></form></Modal>}
  {selectedMemo&&<Modal title={selectedMemo.number} onClose={()=>setSelectedMemo(null)}><div className="space-y-3 text-sm"><p><b>Asesor:</b> {selectedMemo.advisorName} · DNI {selectedMemo.advisorDni}</p><p><b>Empresa / campaña:</b> {selectedMemo.companyName||'—'} / {selectedMemo.campaignName||'—'}</p><p><b>Fecha:</b> {selectedMemo.createdAt.slice(0,10)} · <b>Emitido por:</b> {selectedMemo.issuerName}</p><p><b>Asunto:</b> {selectedMemo.subject}</p><div><b>Hechos</b><p className="mt-1 whitespace-pre-wrap">{selectedMemo.content}</p></div><div><b>Acción requerida</b><p className="mt-1 whitespace-pre-wrap">{selectedMemo.actionRequired}</p></div>{selectedMemo.status==='ANULADO'&&<p className="rounded-lg border border-rose-400/40 p-3 text-rose-300">Anulado: {selectedMemo.annulReason}</p>}{error&&<p role="alert" className="text-rose-300">{error}</p>}<div className="flex flex-wrap justify-end gap-2"><button onClick={()=>printMemorandum(selectedMemo)} className="cm-button-secondary px-3 py-2">Imprimir / guardar PDF</button>{currentUser.role==='ADMINISTRADOR'&&selectedMemo.status==='EMITIDO'&&<button onClick={()=>setAnnulReason(' ')} className="cm-button-secondary px-3 py-2 text-rose-300">Anular</button>}</div>{annulReason&&selectedMemo.status==='EMITIDO'&&<form onSubmit={event=>{event.preventDefault();void annulMemo();}} className="space-y-2"><Field label="Motivo de anulación"><textarea required minLength={5} maxLength={1000} className="cm-input w-full" value={annulReason} onChange={event=>setAnnulReason(event.target.value)}/></Field><button disabled={busy} className="cm-button-secondary px-3 py-2 text-rose-300">Confirmar anulación</button></form>}</div></Modal>}
  </main>;
};
const printMemorandum=(memo:Memorandum)=>{const escape=(value:string)=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));const windowRef=window.open('','_blank');if(!windowRef)return;windowRef.document.write(`<!doctype html><html lang="es"><meta charset="utf-8"><title>${escape(memo.number)}</title><style>body{font:16px Arial,sans-serif;max-width:800px;margin:50px auto;line-height:1.6;color:#172437}header{border-bottom:2px solid #172437;padding-bottom:20px}h1{font-size:22px}.body{white-space:pre-wrap}section{margin-top:28px}.muted{color:#536476}footer{margin-top:70px;border-top:1px solid #aaa;padding-top:12px}@media print{body{margin:25mm}}</style><header><h1>MEMORÁNDUM ${escape(memo.number)}</h1><div class="muted">Fecha: ${escape(memo.createdAt.slice(0,10))} · ${escape(memo.companyName)} / ${escape(memo.campaignName)}</div></header><p><b>Para:</b> ${escape(memo.advisorName)} · DNI ${escape(memo.advisorDni)}<br><b>De:</b> ${escape(memo.issuerName)}<br><b>Asunto:</b> ${escape(memo.subject)}</p><section><b>Hechos</b><div class="body">${escape(memo.content)}</div></section><section><b>Acción requerida</b><div class="body">${escape(memo.actionRequired)}</div></section>${memo.status==='ANULADO'?`<section><b>ANULADO:</b> ${escape(memo.annulReason||'')}</section>`:''}<footer>Referencia: alerta ${escape(memo.alertTitle)} · ${escape(memo.number)}</footer></html>`);windowRef.document.close();windowRef.focus();windowRef.print();};
const Modal:React.FC<{title:string;onClose:()=>void;children:React.ReactNode}>=({title,onClose,children})=><BaseModal open title={title} onClose={onClose} size="md" tone="form">{children}</BaseModal>;
const Field:React.FC<{label:string;wide?:boolean;children:React.ReactNode}>=({label,wide,children})=><label className={`text-xs font-semibold ${wide?'sm:col-span-2':''}`}>{label}<div className="mt-1">{children}</div></label>;
const Info:React.FC<{label:string;value:string}>=({label,value})=><div className="rounded-lg border border-[var(--cm-border)] p-3"><span className="block text-[10px] text-[var(--cm-text-secondary)]">{label}</span><b className="text-xs">{value}</b></div>;
