import 'dotenv/config';
import { createHash } from 'node:crypto';
// @ts-ignore pg ships runtime types separately in this legacy project.
import { Pool } from 'pg';
import type { Advisor, Campaign, Company, Operation, OperationAssignment, OperationSupervisor, StaffingMovement, Team, User } from '../src/types';
import type { AuthUserRecord, SharedRepository } from './googleStorage';

const databaseUrl = () => String(process.env.SUPABASE_DATABASE_URL || '').trim();
const json = <T>(value: any, fallback: T): T => {
  if (value == null) return fallback;
  if (typeof value === 'object') return value as T;
  try { return JSON.parse(value) as T; } catch { return fallback; }
};
const uuid = (value: string) => {
  const hash = createHash('sha256').update(value).digest('hex').slice(0, 32).split('');
  hash[12] = '4'; hash[16] = ((parseInt(hash[16], 16) & 3) | 8).toString(16);
  const joined = hash.join('');
  return `${joined.slice(0,8)}-${joined.slice(8,12)}-${joined.slice(12,16)}-${joined.slice(16,20)}-${joined.slice(20)}`;
};
const tokenHash = (token: string) => createHash('sha256').update(token).digest('hex');
const driveId = (audioUrl: unknown) => String(audioUrl || '').match(/\/api\/files\/([^/]+)\/content/)?.[1] || null;

class SupabaseStorage {
  private pool?: any;
  get enabled() { return Boolean(databaseUrl()); }
  private db() {
    if (!this.enabled) throw new Error('SUPABASE_DATABASE_URL no está configurada.');
    return this.pool ||= new Pool({ connectionString: databaseUrl(), ssl: { rejectUnauthorized: false }, max: 8, idleTimeoutMillis: 30_000, statement_timeout: 30_000 });
  }
  async health() { const started=Date.now(); await this.db().query('select 1'); return { ok:true, durationMs:Date.now()-started }; }
  private async transaction<T>(run:(client:any)=>Promise<T>):Promise<T>{const client=await this.db().connect();try{await client.query('BEGIN');const result=await run(client);await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}

  async loadRepository():Promise<SharedRepository|null>{
    if(!this.enabled)return null;
    const [users,campaigns,teams,people,companies,operations,operationSupervisors,assignments,movements]=await Promise.all([
      this.db().query('SELECT * FROM users ORDER BY name'),this.db().query('SELECT * FROM campaign_definitions ORDER BY name'),this.db().query('SELECT * FROM teams ORDER BY name'),this.db().query('SELECT * FROM people ORDER BY display_name'),this.db().query('SELECT * FROM companies ORDER BY name'),this.db().query('SELECT * FROM operations ORDER BY name'),this.db().query('SELECT * FROM operation_supervisors ORDER BY start_at'),this.db().query('SELECT * FROM assignments ORDER BY start_at'),this.db().query('SELECT * FROM staffing_movements ORDER BY created_at')]);
    const operationRows=operations.rows.map((row:any)=>({id:row.id,companyId:row.company_id,campaignId:row.source_campaign_id,name:row.name,normalizedName:row.normalized_name,status:row.status,legacy:Boolean(row.legacy),createdAt:row.created_at?.toISOString?.()||row.created_at,updatedAt:row.updated_at?.toISOString?.()||row.updated_at,closedAt:row.closed_at?.toISOString?.()||row.closed_at||undefined,version:Number(row.version||1),metadata:json(row.metadata_json,{})} as Operation));
    const assignmentByPerson=new Map(assignments.rows.filter((row:any)=>row.active).map((row:any)=>[row.person_id,row]));
    return {
      users:users.rows.map((row:any)=>({id:row.id,name:row.name,email:row.email,username:row.username||undefined,role:row.role,status:row.status,teamId:row.source_team_id||undefined,advisorId:row.source_advisor_id||undefined,avatar:row.avatar||undefined,createdAt:row.created_at?.toISOString?.()||row.created_at,mustChangePassword:Boolean(row.must_change_password),accessScope:row.access_scope,companyIds:json(row.company_ids_json,[]),operationIds:json(row.operation_ids_json,[])} as User)),
      campaigns:campaigns.rows.map((row:any)=>({id:row.id,name:row.name,client:row.client||'',status:row.status,products:json(row.products_json,[]),description:row.description||undefined,backgroundImage:row.background_image||undefined,qualityGuidelines:json(row.quality_guidelines_json,[]),qualityCriterionWeights:json(row.quality_criterion_weights_json,null)||undefined,qualityCriticalErrors:json(row.quality_critical_errors_json,[])} as Campaign)),
      teams:teams.rows.map((row:any)=>({id:row.id,campaignId:row.source_campaign_id,supervisorId:row.supervisor_id,name:row.name} as Team)),
      advisors:people.rows.map((row:any)=>{const profile=json<any>(row.profile_json,{}),assignment=assignmentByPerson.get(row.id) as any;return{...profile,id:row.source_advisor_id||row.id,dni:row.dni||profile.dni||'',employeeCode:row.employee_code||profile.employeeCode||'',name:row.display_name,campaignId:profile.campaignId||operationRows.find(item=>item.id===assignment?.operation_id)?.campaignId||'',operationId:assignment?.operation_id||profile.operationId,teamId:assignment?.team_id||profile.teamId,supervisorId:assignment?.supervisor_id||profile.supervisorId,status:row.status||profile.status||'ACTIVO',active:row.active!==false};}),
      companies:companies.rows.map((row:any)=>({id:row.id,name:row.name,status:row.status,createdAt:row.created_at?.toISOString?.()||row.created_at,updatedAt:row.updated_at?.toISOString?.()||row.updated_at} as Company)),
      operations:operationRows,
      operationSupervisors:operationSupervisors.rows.map((row:any)=>({operationId:row.operation_id,supervisorId:row.supervisor_id,active:Boolean(row.active),startAt:String(row.start_at).slice(0,10),endAt:row.end_at?String(row.end_at).slice(0,10):undefined} as OperationSupervisor)),
      operationAssignments:assignments.rows.map((row:any)=>({id:row.id,advisorId:row.person_id,operationId:row.operation_id,teamId:row.team_id||undefined,supervisorId:row.supervisor_id||undefined,role:row.role,operationalStatus:row.operational_status,startDate:String(row.start_at).slice(0,10),endDate:row.end_at?String(row.end_at).slice(0,10):undefined,active:Boolean(row.active),source:row.source,actorId:row.actor_user_id||undefined,observation:row.observation||undefined} as OperationAssignment)),
      staffingMovements:movements.rows.map((row:any)=>({id:row.id,advisorId:row.person_id,assignmentId:row.assignment_id||undefined,type:row.type,effectiveAt:String(row.effective_at).slice(0,10),createdAt:row.created_at?.toISOString?.()||row.created_at,origin:json(row.origin_json,undefined),destination:json(row.destination_json,undefined),actorId:row.actor_user_id||undefined,observation:row.observation||undefined,reversedMovementId:row.reversed_movement_id||undefined} as StaffingMovement))
    };
  }

  async saveRepository(repository:SharedRepository,passwordHashes:Map<string,string>){if(!this.enabled)return;await this.transaction(async client=>{
    for(const company of repository.companies||[])await client.query(`INSERT INTO companies(id,name,normalized_name,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,normalized_name=EXCLUDED.normalized_name,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`,[company.id,company.name,company.name.toLocaleLowerCase(),company.status,company.createdAt||new Date().toISOString(),company.updatedAt||new Date().toISOString()]);
    for(const campaign of repository.campaigns)await client.query(`INSERT INTO campaign_definitions(id,name,normalized_name,client,status,products_json,description,quality_guidelines_json,quality_criterion_weights_json,quality_critical_errors_json,background_image) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,normalized_name=EXCLUDED.normalized_name,client=EXCLUDED.client,status=EXCLUDED.status,products_json=EXCLUDED.products_json,description=EXCLUDED.description,quality_guidelines_json=EXCLUDED.quality_guidelines_json,quality_criterion_weights_json=EXCLUDED.quality_criterion_weights_json,quality_critical_errors_json=EXCLUDED.quality_critical_errors_json,background_image=EXCLUDED.background_image`,[campaign.id,campaign.name,campaign.name.toLocaleLowerCase(),campaign.client,campaign.status,JSON.stringify(campaign.products||[]),campaign.description||null,JSON.stringify(campaign.qualityGuidelines||[]),JSON.stringify(campaign.qualityCriterionWeights||null),JSON.stringify(campaign.qualityCriticalErrors||[]),campaign.backgroundImage||null]);
    for(const operation of repository.operations||[])await client.query(`INSERT INTO operations(id,company_id,source_campaign_id,name,normalized_name,status,legacy,created_at,updated_at,closed_at,version,metadata_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET company_id=EXCLUDED.company_id,source_campaign_id=EXCLUDED.source_campaign_id,name=EXCLUDED.name,normalized_name=EXCLUDED.normalized_name,status=EXCLUDED.status,legacy=EXCLUDED.legacy,updated_at=EXCLUDED.updated_at,closed_at=EXCLUDED.closed_at,version=EXCLUDED.version,metadata_json=EXCLUDED.metadata_json`,[operation.id,operation.companyId,operation.campaignId,operation.name,operation.normalizedName||operation.name.toLocaleLowerCase(),operation.status,Boolean(operation.legacy),operation.createdAt||new Date().toISOString(),operation.updatedAt||new Date().toISOString(),operation.closedAt||null,String(operation.version||1),JSON.stringify(operation.metadata||{})]);
    for(const advisor of repository.advisors)await client.query(`INSERT INTO people(id,source_advisor_id,dni,employee_code,display_name,normalized_name,status,active,profile_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET dni=EXCLUDED.dni,employee_code=EXCLUDED.employee_code,display_name=EXCLUDED.display_name,normalized_name=EXCLUDED.normalized_name,status=EXCLUDED.status,active=EXCLUDED.active,profile_json=EXCLUDED.profile_json`,[advisor.id,advisor.id,advisor.dni||null,advisor.employeeCode||null,advisor.name,advisor.name.toLocaleLowerCase(),advisor.status||'ACTIVO',advisor.active!==false,JSON.stringify(advisor)]);
    for(const user of repository.users)await client.query(`INSERT INTO users(id,person_id,source_advisor_id,name,email,username,role,status,source_team_id,avatar,created_at,legacy_password_hash,must_change_password,access_scope,company_ids_json,operation_ids_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) ON CONFLICT(id) DO UPDATE SET person_id=EXCLUDED.person_id,source_advisor_id=EXCLUDED.source_advisor_id,name=EXCLUDED.name,email=EXCLUDED.email,username=EXCLUDED.username,role=EXCLUDED.role,status=EXCLUDED.status,source_team_id=EXCLUDED.source_team_id,avatar=EXCLUDED.avatar,legacy_password_hash=COALESCE(EXCLUDED.legacy_password_hash,users.legacy_password_hash),must_change_password=EXCLUDED.must_change_password,access_scope=EXCLUDED.access_scope,company_ids_json=EXCLUDED.company_ids_json,operation_ids_json=EXCLUDED.operation_ids_json`,[user.id,user.advisorId||null,user.advisorId||null,user.name,user.email,user.username||null,user.role,user.status,user.teamId||null,user.avatar||null,user.createdAt||new Date().toISOString(),passwordHashes.get(user.id)||null,user.mustChangePassword!==false,user.accessScope||(user.role==='ASESOR'?'SELF':user.role==='SUPERVISOR'?'TEAM':'GLOBAL'),JSON.stringify(user.companyIds||[]),JSON.stringify(user.operationIds||[])]);
    for(const team of repository.teams)await client.query(`INSERT INTO teams(id,operation_id,source_campaign_id,supervisor_id,name) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET operation_id=EXCLUDED.operation_id,source_campaign_id=EXCLUDED.source_campaign_id,supervisor_id=EXCLUDED.supervisor_id,name=EXCLUDED.name`,[team.id,(repository.operations||[]).find(item=>item.campaignId===team.campaignId)?.id||null,team.campaignId,team.supervisorId,team.name]);
    for(const item of repository.operationSupervisors||[])await client.query(`INSERT INTO operation_supervisors(id,operation_id,supervisor_id,active,start_at,end_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(operation_id,supervisor_id,start_at) DO UPDATE SET active=EXCLUDED.active,end_at=EXCLUDED.end_at`,[uuid(`${item.operationId}|${item.supervisorId}|${item.startAt}`),item.operationId,item.supervisorId,item.active,item.startAt,item.endAt||null]);
    for(const item of repository.operationAssignments||[])await client.query(`INSERT INTO assignments(id,person_id,operation_id,team_id,source_team_id,supervisor_id,role,operational_status,start_at,end_at,active,source,actor_user_id,source_actor_id,observation) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET operation_id=EXCLUDED.operation_id,team_id=EXCLUDED.team_id,supervisor_id=EXCLUDED.supervisor_id,operational_status=EXCLUDED.operational_status,end_at=EXCLUDED.end_at,active=EXCLUDED.active,actor_user_id=EXCLUDED.actor_user_id,observation=EXCLUDED.observation`,[item.id,item.advisorId,item.operationId,item.teamId||null,item.teamId||null,item.supervisorId||null,item.role,item.operationalStatus,item.startDate,item.endDate||null,item.active,item.source,item.actorId||null,item.actorId||null,item.observation||null]);
    for(const item of repository.staffingMovements||[])await client.query(`INSERT INTO staffing_movements(id,person_id,assignment_id,source_assignment_id,type,effective_at,created_at,origin_json,destination_json,actor_user_id,source_actor_id,observation,reversed_movement_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(id) DO NOTHING`,[item.id,item.advisorId,item.assignmentId||null,item.assignmentId||null,item.type,item.effectiveAt,item.createdAt||item.occurredAt||new Date().toISOString(),JSON.stringify(item.origin||null),JSON.stringify(item.destination||null),item.actorId||null,item.actorId||null,item.observation||null,item.reversedMovementId||null]);
  });}

  async loadUsersForAuthentication():Promise<AuthUserRecord[]>{const rows=(await this.db().query(`SELECT u.*,p.dni advisor_dni FROM users u LEFT JOIN people p ON p.id=u.person_id OR p.source_advisor_id=u.source_advisor_id`)).rows;return rows.map((row:any)=>({id:row.id,name:row.name,email:row.email,username:row.username||undefined,role:row.role,status:row.status,teamId:row.source_team_id||undefined,advisorId:row.source_advisor_id||undefined,advisorDni:row.advisor_dni||undefined,avatar:row.avatar||undefined,createdAt:row.created_at?.toISOString?.()||row.created_at,passwordHash:row.legacy_password_hash||'',mustChangePassword:Boolean(row.must_change_password),accessScope:row.access_scope,companyIds:json(row.company_ids_json,[]),operationIds:json(row.operation_ids_json,[])}));}
  async updateUserPasswordHash(id:string,passwordHash:string,mustChangePassword=false){await this.db().query('UPDATE users SET legacy_password_hash=$2,must_change_password=$3 WHERE id=$1',[id,passwordHash,mustChangePassword]);}
  async loadSession(token:string){return (await this.db().query('SELECT user_id,created_at FROM auth_sessions WHERE token_hash=$1 AND expires_at>now()',[tokenHash(token)])).rows[0]||null;}
  async saveSession(token:string,userId:string,createdAt:string){await this.db().query(`INSERT INTO auth_sessions(token_hash,user_id,created_at,expires_at) VALUES($1,$2,$3,$4) ON CONFLICT(token_hash) DO UPDATE SET user_id=EXCLUDED.user_id,expires_at=EXCLUDED.expires_at`,[tokenHash(token),userId,createdAt,new Date(Date.now()+12*60*60*1000).toISOString()]);}
  async deleteSession(token:string){await this.db().query('DELETE FROM auth_sessions WHERE token_hash=$1',[tokenHash(token)]);}
  async saveEvaluation(e:any){const evaluatedAt=`${e.date}T${e.time||'00:00'}:00Z`;await this.transaction(async client=>{await client.query(`INSERT INTO evaluations(id,person_id,evaluator_user_id,supervisor_user_id,operation_id,source_campaign_id,source_team_id,evaluation_type,evaluated_at,created_at,product,call_id,evaluation_subtype,quality_status,origin,validation_status,validated_at,sale,sale_result,comments,primary_gap,secondary_gap,strongest_pillar,recommendation,score_connect,score_clarify,score_convert,score_total,technical_score,quality_result,critical_reason,payload_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32) ON CONFLICT(id) DO UPDATE SET supervisor_user_id=EXCLUDED.supervisor_user_id,operation_id=EXCLUDED.operation_id,evaluated_at=EXCLUDED.evaluated_at,validation_status=EXCLUDED.validation_status,validated_at=EXCLUDED.validated_at,score_total=EXCLUDED.score_total,technical_score=EXCLUDED.technical_score,quality_result=EXCLUDED.quality_result,critical_reason=EXCLUDED.critical_reason,payload_json=EXCLUDED.payload_json`,[e.id,e.advisorId,e.evaluatorId,e.supervisorAtEvaluation||e.supervisorId||null,e.operationId||null,e.campaignId||null,e.teamId||null,e.evaluationType,evaluatedAt,e.createdAt||new Date().toISOString(),e.product||null,e.callId||e.recordingCode||null,e.type||null,e.qualityStatus||null,e.origin||'MANUAL',e.validationStatus||'VALIDATED',e.validatedAt||null,e.sale??null,e.saleResult||null,e.comments||null,e.primaryGap||null,e.secondaryGap||null,e.strongestPillar||null,e.recommendation||null,e.scoreConnect??null,e.scoreClarify??null,e.scoreConvert??null,e.scoreTotal??null,e.technicalScore??null,e.qualityResult||null,e.criticalReason||null,JSON.stringify(e)]);const fileId=driveId(e.audioUrl);if(fileId)await client.query(`INSERT INTO evaluation_media(id,evaluation_id,recording_code,audio_drive_file_id,audio_file_name,audio_mime_type,audio_size,metadata_json,source_file,source_sheet,source_row) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'runtime','runtime',0) ON CONFLICT(id) DO UPDATE SET audio_drive_file_id=EXCLUDED.audio_drive_file_id,audio_file_name=EXCLUDED.audio_file_name,audio_mime_type=EXCLUDED.audio_mime_type,audio_size=EXCLUDED.audio_size,metadata_json=EXCLUDED.metadata_json`,[uuid(`${e.id}|audio`),e.id,e.recordingCode||null,fileId,e.audioFileName||null,e.audioMimeType||null,e.audioFileSize||e.audioSize||null,JSON.stringify({durationSeconds:e.audioDurationSeconds||null})]);});}
  async loadEvaluations(){return (await this.db().query('SELECT payload_json FROM evaluations ORDER BY evaluated_at DESC')).rows.map((row:any)=>json(row.payload_json,{}));}
  async deleteEvaluation(id:string){return this.transaction(async client=>{const feedbacksDeleted=(await client.query('DELETE FROM feedback WHERE evaluation_id=$1',[id])).rowCount||0;await client.query('DELETE FROM evaluation_media WHERE evaluation_id=$1',[id]);await client.query('DELETE FROM evaluation_items WHERE evaluation_id=$1',[id]);const evaluationsDeleted=(await client.query('DELETE FROM evaluations WHERE id=$1',[id])).rowCount||0;return{evaluationsDeleted,feedbacksDeleted};});}
  async deduplicateEvaluations(){return 0;}
  async loadFeedbacks(){return (await this.db().query('SELECT id feedback_id,evaluation_id,person_id advisor_id,supervisor_user_id supervisor_id,evaluator_user_id evaluator_id,evaluation_type,feedback_text,advisor_response,advisor_evidence_url,supervisor_closure_comment,status,created_at,advisor_action_at,closed_at,updated_at FROM feedback ORDER BY updated_at DESC')).rows;}
  async saveFeedback(f:any){await this.db().query(`INSERT INTO feedback(id,evaluation_id,person_id,supervisor_user_id,evaluator_user_id,evaluation_type,feedback_text,advisor_response,advisor_evidence_url,supervisor_closure_comment,status,created_at,advisor_action_at,closed_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET feedback_text=EXCLUDED.feedback_text,advisor_response=EXCLUDED.advisor_response,advisor_evidence_url=EXCLUDED.advisor_evidence_url,supervisor_closure_comment=EXCLUDED.supervisor_closure_comment,status=EXCLUDED.status,advisor_action_at=EXCLUDED.advisor_action_at,closed_at=EXCLUDED.closed_at,updated_at=EXCLUDED.updated_at`,[f.feedback_id,f.evaluation_id,f.advisor_id,f.supervisor_id,f.evaluator_id,f.evaluation_type,f.feedback_text||'',f.advisor_response||null,f.advisor_evidence_url||null,f.supervisor_closure_comment||null,f.status,f.created_at||new Date().toISOString(),f.advisor_action_at||null,f.closed_at||null,f.updated_at||new Date().toISOString()]);}
  async loadPlatformState(){const state=json<any>((await this.db().query(`SELECT payload_json FROM runtime_state WHERE id='global'`)).rows[0]?.payload_json,{});return{...state,evaluations:await this.loadEvaluations()};}
  async savePlatformState(state:any){const {evaluations,...rest}=state||{};await this.db().query(`INSERT INTO runtime_state(id,payload_json,updated_at) VALUES('global',$1,now()) ON CONFLICT(id) DO UPDATE SET payload_json=EXCLUDED.payload_json,updated_at=now()`,[JSON.stringify(rest)]);if(Array.isArray(evaluations))for(const evaluation of evaluations)await this.saveEvaluation(evaluation);}
  async loadDevelopment(){const[capsules,assignments]=await Promise.all([this.db().query('SELECT data_json FROM development_capsules ORDER BY updated_at DESC'),this.db().query('SELECT data_json FROM development_assignments ORDER BY updated_at DESC')]);return{capsules:capsules.rows.map((r:any)=>json(r.data_json,{})),assignments:assignments.rows.map((r:any)=>json(r.data_json,{}))};}
  async saveDevelopment(capsules:any[],assignments:any[]){await this.transaction(async client=>{for(const item of capsules)await client.query(`INSERT INTO development_capsules(id,status,data_json,created_at,updated_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,data_json=EXCLUDED.data_json,updated_at=EXCLUDED.updated_at`,[item.id,item.status,JSON.stringify(item),item.createdAt||new Date().toISOString(),item.updatedAt||new Date().toISOString()]);for(const item of assignments)await client.query(`INSERT INTO development_assignments(id,capsule_id,person_id,status,data_json,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,data_json=EXCLUDED.data_json,updated_at=EXCLUDED.updated_at`,[item.id,item.capsuleId,item.advisorId,item.status,JSON.stringify(item),item.assignedAt||new Date().toISOString(),item.updatedAt||new Date().toISOString()]);});}
  async loadQualityAlerts(){return(await this.db().query('SELECT data_json FROM quality_alerts ORDER BY updated_at DESC')).rows.map((r:any)=>json(r.data_json,{}));}
  async saveQualityAlert(item:any){await this.db().query(`INSERT INTO quality_alerts(id,status,person_id,supervisor_user_id,operation_id,data_json,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,data_json=EXCLUDED.data_json,updated_at=EXCLUDED.updated_at`,[item.id,item.status,item.advisorId||null,item.supervisorId||null,item.operationId||null,JSON.stringify(item),item.publishedAt||new Date().toISOString(),item.updatedAt||new Date().toISOString()]);}
  async deleteQualityAlert(id:string){await this.db().query('DELETE FROM quality_alerts WHERE id=$1',[id]);}
  async loadCalibrations(){return(await this.db().query('SELECT data_json FROM calibrations ORDER BY updated_at DESC')).rows.map((r:any)=>json(r.data_json,{}));}
  async saveCalibration(item:any){await this.db().query(`INSERT INTO calibrations(id,status,evaluation_id,operation_id,data_json,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,data_json=EXCLUDED.data_json,updated_at=EXCLUDED.updated_at`,[item.id,item.status,item.evaluationId||null,item.operationId||null,JSON.stringify(item),item.createdAt||new Date().toISOString(),item.updatedAt||new Date().toISOString()]);}
  async deleteCalibration(id:string){await this.db().query('DELETE FROM calibrations WHERE id=$1',[id]);}
}

export const supabaseStorage = new SupabaseStorage();
