import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, CalendarDays, CheckCircle2, RefreshCw, UsersRound } from 'lucide-react';
import { Button, Card, KpiCard, Select } from '../ui';
import { SPEECH_TYPIFICATIONS } from '../../utils/speechTypification';

type PublicEvaluation={id:string;advisorId:string;advisorName:string;supervisorName:string;date:string;evaluationType:'QUALITY'|'D3C';origin:'MANUAL'|'SPEECH_ANALYTICS';speechTypification:string|null;score:number|null;validationStatus:string|null;qualityResult:string|null;primaryGap:string|null};
type PublicAdvisor={id:string;name:string;status:string;supervisorName:string};
type Snapshot={company:{id:string;name:string};campaign:{id:string;name:string};generatedAt:string;expiresAt:string;advisors:PublicAdvisor[];evaluations:PublicEvaluation[]};
const average=(values:number[])=>values.length?Math.round(values.reduce((sum,value)=>sum+value,0)/values.length):null;
const displayScore=(value:number|null)=>value===null?'Sin datos':`${value}%`;
const shortDate=(value:string)=>value?new Date(`${value}T00:00:00Z`).toLocaleDateString('es-PE',{timeZone:'UTC'}):'—';

export const PublicDashboardView:React.FC=()=>{
  const token=window.location.pathname.match(/^\/share\/dashboard\/([^/]+)\/?$/)?.[1]||'';
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [mode,setMode]=useState<'QUALITY'|'D3C'>('QUALITY');
  const [origin,setOrigin]=useState('ALL');
  const [typification,setTypification]=useState('ALL');
  const [advisorId,setAdvisorId]=useState('ALL');
  const [dateFrom,setDateFrom]=useState('');
  const [dateTo,setDateTo]=useState('');
  const [refreshKey,setRefreshKey]=useState(0);
  useEffect(()=>{let alive=true;setLoading(true);setError('');fetch(`/api/public/dashboard/${encodeURIComponent(token)}`,{cache:'no-store'}).then(async response=>{const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Enlace no disponible.');return data as Snapshot;}).then(data=>{if(alive)setSnapshot(data);}).catch(cause=>{if(alive)setError(cause instanceof Error?cause.message:'No se pudo cargar el dashboard.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[token,refreshKey]);
  const base=useMemo(()=>snapshot?.evaluations.filter(item=>item.evaluationType===mode&&(!dateFrom||item.date>=dateFrom)&&(!dateTo||item.date<=dateTo)&&(!advisorId||advisorId==='ALL'||item.advisorId===advisorId)&& (origin==='ALL'||item.origin===origin) && (origin!=='SPEECH_ANALYTICS'||typification==='ALL'||(typification==='SIN_TIPIFICACION'?!item.speechTypification:item.speechTypification===typification)))||[],[snapshot,mode,dateFrom,dateTo,advisorId,origin,typification]);
  const scored=useMemo(()=>base.filter(item=>!(mode==='QUALITY'&&item.origin==='SPEECH_ANALYTICS'&&item.speechTypification==='CORTA_LLAMADA')&&typeof item.score==='number'&&Number.isFinite(item.score)),[base,mode]);
  const summary=useMemo(()=>{
    const grouped=new Map<string,{name:string;supervisor:string;scores:number[];count:number}>();
    for(const item of scored){const current=grouped.get(item.advisorId)||{name:item.advisorName,supervisor:item.supervisorName,scores:[],count:0};current.scores.push(item.score!);current.count++;grouped.set(item.advisorId,current);}
    const advisors=[...grouped.entries()].map(([id,item])=>({id,...item,average:average(item.scores)})).sort((a,b)=>(a.average??101)-(b.average??101));
    const byMonth=new Map<string,number[]>();for(const item of scored){if(!item.date)continue;const key=item.date.slice(0,7);byMonth.set(key,[...(byMonth.get(key)||[]),item.score!]);}
    const trend=[...byMonth.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([month,scores])=>({month,score:average(scores)!,count:scores.length}));
    const manual=average(scored.filter(item=>item.origin==='MANUAL').map(item=>item.score!));
    const speech=average(scored.filter(item=>item.origin==='SPEECH_ANALYTICS').map(item=>item.score!));
    const bySupervisor=new Map<string,number[]>();for(const item of scored)bySupervisor.set(item.supervisorName,[...(bySupervisor.get(item.supervisorName)||[]),item.score!]);
    const supervisors=[...bySupervisor.entries()].map(([name,scores])=>({name,count:scores.length,score:average(scores)})).sort((a,b)=>(a.score??101)-(b.score??101));
    const byGap=new Map<string,number>();for(const item of base)if(item.primaryGap)byGap.set(item.primaryGap,(byGap.get(item.primaryGap)||0)+1);
    const gaps=[...byGap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6);
    return {advisors,trend,manual,speech,supervisors,gaps,global:average(scored.map(item=>item.score!))};
  },[base,scored]);
  const currentAdvisors=snapshot?.advisors.filter(item=>advisorId==='ALL'||item.id===advisorId)||[];
  const chartPoints=summary.trend.map((point,index)=>`${summary.trend.length===1?50:8+index*84/(summary.trend.length-1)},${88-point.score*.76}`).join(' ');
  return <div className="min-h-screen bg-[#0b1727] text-slate-100"><header className="border-b border-slate-700 bg-[#101f32] px-5 py-5 sm:px-9"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold tracking-[.2em] text-cyan-300">C&amp;M · CALIDAD Y MEJORA CONTINUA</p><h1 className="mt-1 text-2xl font-bold">Dashboard de {snapshot?.campaign.name||'campaña'}</h1><p className="text-sm text-slate-400">{snapshot?.company.name||'Vista compartida'} · Indicadores de calidad y desempeño</p></div><Button variant="secondary" size="sm" leadingIcon={<RefreshCw/>} onClick={()=>setRefreshKey(key=>key+1)}>Actualizar</Button></div></header>
    <main className="mx-auto max-w-7xl space-y-6 px-5 py-7 sm:px-9">
      {loading&&<p role="status">Cargando indicadores…</p>}{error&&<div role="alert" className="rounded-xl border border-red-700 bg-red-950/40 p-5">{error}</div>}
      {snapshot&&!loading&&<>
        <div className="flex flex-wrap gap-2"><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${mode==='QUALITY'?'bg-cyan-400 text-slate-950':'bg-slate-800'}`} onClick={()=>setMode('QUALITY')}>Calidad</button><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${mode==='D3C'?'bg-cyan-400 text-slate-950':'bg-slate-800'}`} onClick={()=>setMode('D3C')}>Mejora Continua · D+3C</button></div>
        <section className="grid gap-3 rounded-xl border border-slate-700 bg-[#102238] p-4 sm:grid-cols-2 lg:grid-cols-5" aria-label="Filtros de la vista pública">
          <label className="text-sm">Desde<input aria-label="Fecha desde" type="date" value={dateFrom} onChange={event=>setDateFrom(event.target.value)} className="cm-input mt-1 w-full"/></label>
          <label className="text-sm">Hasta<input aria-label="Fecha hasta" type="date" value={dateTo} onChange={event=>setDateTo(event.target.value)} className="cm-input mt-1 w-full"/></label>
          <label className="text-sm">Asesor<Select aria-label="Filtrar asesor" value={advisorId} onChange={event=>setAdvisorId(event.target.value)} className="mt-1"><option value="ALL">Todos los asesores</option>{snapshot.advisors.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></label>
          <label className="text-sm">Origen<Select aria-label="Filtrar origen" value={origin} onChange={event=>{setOrigin(event.target.value);setTypification('ALL');}} className="mt-1"><option value="ALL">Todos</option><option value="MANUAL">Manual</option><option value="SPEECH_ANALYTICS">Speech Analytics</option></Select></label>
          {mode==='QUALITY'&&origin==='SPEECH_ANALYTICS'&&<label className="text-sm">Tipificación<Select aria-label="Filtrar tipificación" value={typification} onChange={event=>setTypification(event.target.value)} className="mt-1"><option value="ALL">Todas</option>{SPEECH_TYPIFICATIONS.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}<option value="SIN_TIPIFICACION">Sin tipificar</option></Select></label>}
        </section>
        <section aria-label="Indicadores principales" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><KpiCard label="Nota promedio" value={displayScore(summary.global)} icon={<Activity/>} detail={`${scored.length} evaluaciones con nota`}/><KpiCard label="Evaluaciones" value={String(base.length)} icon={<BarChart3/>} detail={`${base.length-scored.length} sin nota evaluable`}/><KpiCard label="Asesores activos" value={String(currentAdvisors.filter(item=>item.status==='ACTIVO').length)} icon={<UsersRound/>} detail={`${currentAdvisors.length} en dotación`}/><KpiCard label="Periodo" value={dateFrom||dateTo?'Filtrado':'Histórico'} icon={<CalendarDays/>} detail={`${summary.trend.length} meses con nota`}/></section>
        <section className="grid gap-4 lg:grid-cols-[2fr_1fr]"><Card className="p-5"><h2 className="text-lg font-bold">Tendencia de nota promedio</h2><p className="text-sm text-slate-400">Evolución mensual de {mode==='QUALITY'?'Calidad':'Mejora Continua'}.</p>{summary.trend.length?<><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Línea de tendencia de notas promedio" className="mt-4 h-64 w-full overflow-visible"><line x1="8" y1="88" x2="92" y2="88" stroke="#475569" strokeWidth=".3"/><line x1="8" y1="50" x2="92" y2="50" stroke="#334155" strokeWidth=".3"/><polyline points={chartPoints} fill="none" stroke="#38bdf8" strokeWidth=".8" vectorEffect="non-scaling-stroke"/>{summary.trend.map((point,index)=><circle key={point.month} cx={summary.trend.length===1?50:8+index*84/(summary.trend.length-1)} cy={88-point.score*.76} r="1" fill="#22d3ee"><title>{point.month}: {point.score}% · {point.count} evaluaciones</title></circle>)}</svg><div className="flex justify-between gap-2 text-xs text-slate-400"><span>{summary.trend[0].month}</span><span>{summary.trend.at(-1)?.month}</span></div></>:<p className="py-20 text-center text-slate-400">Sin notas para graficar en este periodo.</p>}</Card><Card className="space-y-4 p-5"><h2 className="text-lg font-bold">Origen de la evaluación</h2><div className="rounded-lg border border-slate-700 p-4"><span>Evaluaciones manuales</span><strong className="block text-2xl">{displayScore(summary.manual)}</strong><small>{scored.filter(item=>item.origin==='MANUAL').length} con nota</small></div><div className="rounded-lg border border-slate-700 p-4"><span>Speech Analytics</span><strong className="block text-2xl">{displayScore(summary.speech)}</strong><small>{scored.filter(item=>item.origin==='SPEECH_ANALYTICS').length} con nota</small></div><p className="text-xs text-slate-400">Las llamadas tipificadas como «Corta llamada» no afectan el promedio de Calidad.</p></Card></section>
        <section className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="mb-3 text-lg font-bold">Resultado por asesor</h2><div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-700 text-slate-400"><th className="py-2">Asesor</th><th>Supervisor</th><th>Eval.</th><th>Nota</th></tr></thead><tbody>{summary.advisors.map(item=><tr key={item.id} className="border-b border-slate-800"><td className="py-2 font-medium">{item.name}</td><td>{item.supervisor}</td><td>{item.count}</td><td>{displayScore(item.average)}</td></tr>)}</tbody></table>{!summary.advisors.length&&<p className="py-6 text-sm text-slate-400">Sin evaluaciones para mostrar.</p>}</div></Card><Card className="p-5"><h2 className="mb-3 text-lg font-bold">Dotación de la campaña</h2><div className="mb-3 flex gap-3 text-sm"><span className="text-emerald-300"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Activos: {currentAdvisors.filter(item=>item.status==='ACTIVO').length}</span><span>Otros: {currentAdvisors.filter(item=>item.status!=='ACTIVO').length}</span></div><div className="max-h-72 overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-700 text-slate-400"><th className="py-2">Asesor</th><th>Supervisor</th><th>Estado</th></tr></thead><tbody>{currentAdvisors.map(item=><tr key={item.id} className="border-b border-slate-800"><td className="py-2 font-medium">{item.name}</td><td>{item.supervisorName}</td><td>{item.status}</td></tr>)}</tbody></table></div></Card></section>
        <section className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="mb-3 text-lg font-bold">Resultado por supervisor</h2>{summary.supervisors.length?summary.supervisors.map(item=><div key={item.name} className="flex justify-between gap-3 border-b border-slate-800 py-2 text-sm"><span>{item.name}</span><strong>{displayScore(item.score)} <small className="font-normal text-slate-400">· {item.count} eval.</small></strong></div>):<p className="text-sm text-slate-400">Sin datos.</p>}</Card><Card className="p-5"><h2 className="mb-3 text-lg font-bold">Brechas principales</h2>{summary.gaps.length?summary.gaps.map(([name,count])=><div key={name} className="flex justify-between gap-3 border-b border-slate-800 py-2 text-sm"><span>{name}</span><strong>{count}</strong></div>):<p className="text-sm text-slate-400">Sin brechas registradas.</p>}</Card></section>
        <Card className="p-5"><h2 className="mb-3 text-lg font-bold">Evaluaciones recientes</h2><div className="max-h-96 overflow-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-slate-700 text-slate-400"><th className="py-2">Fecha</th><th>Asesor</th><th>Supervisor</th><th>Origen</th><th>Tipificación</th><th>Nota</th><th>Resultado</th></tr></thead><tbody>{base.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,100).map(item=><tr key={item.id} className="border-b border-slate-800"><td className="py-2">{shortDate(item.date)}</td><td>{item.advisorName}</td><td>{item.supervisorName}</td><td>{item.origin==='SPEECH_ANALYTICS'?'Speech Analytics':'Manual'}</td><td>{SPEECH_TYPIFICATIONS.find(value=>value.value===item.speechTypification)?.label||'—'}</td><td>{mode==='QUALITY'&&item.speechTypification==='CORTA_LLAMADA'?'No evaluable':displayScore(item.score)}</td><td>{item.qualityResult||item.validationStatus||'—'}</td></tr>)}</tbody></table>{!base.length&&<p className="py-6 text-sm text-slate-400">Sin evaluaciones para mostrar.</p>}</div>{base.length>100&&<p className="mt-2 text-xs text-slate-400">Se muestran las 100 más recientes. Ajusta el periodo para ver otras.</p>}</Card>
        <p className="text-right text-xs text-slate-400">Información actualizada {new Date(snapshot.generatedAt).toLocaleString('es-PE')} · Enlace vigente hasta {new Date(snapshot.expiresAt).toLocaleDateString('es-PE')}</p>
      </>}
    </main>
  </div>;
};
