import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, CheckSquare, ClipboardCheck, Filter, ListChecks, RefreshCw, ShieldCheck, TrendingUp, UsersRound } from 'lucide-react';
import { Badge, Button, Card, CardHeader, EmptyState, KpiCard, PageHeader, Select } from '../ui';
import { CRITERIA_DEFINITIONS } from '../../data/criteriaData';
import { QUALITY_ATTRIBUTES } from '../../data/qualityPueData';
import { TECHCENTER_MOVISTAR_FIELDS, techcenterCriterionPresentation } from '../../data/techcenterMovistarForm';
import { EvaluationOriginFilter, type EvaluationOriginFilterValue } from './EvaluationOriginFilter';
import { SpeechTypificationFilter } from './SpeechTypificationFilter';
import { CompanyDistributionCard, EvaluationStatusCard, QualityTrendCard } from './ExecutiveCharts';
import type { StatusItem, TrendPoint } from './useExecutiveHome';
import type { SpeechTypificationFilter as SpeechFilterValue } from '../../utils/speechTypification';
import { normalizeMotive, type GeoCall } from '../../utils/movistarGeo';

const MovistarGeoCard=React.lazy(()=>import('./MovistarGeoCard').then(module=>({default:module.MovistarGeoCard})));

type Mode = 'QUALITY' | 'D3C';
type PublicItem = { criterionId:string; compliance:'CUMPLE'|'NO_CUMPLE'|'NO_APLICA' };
type PublicEvaluation = { id:string; advisorId:string; advisorName:string; supervisorName:string; date:string; evaluationType:Mode; origin:'MANUAL'|'SPEECH_ANALYTICS'; speechTypification:string|null; score:number|null; scoreConnect:number|null; scoreClarify:number|null; scoreConvert:number|null; items:PublicItem[]; validationStatus:string|null; qualityResult:string|null; primaryGap:string|null; typification?:string|null; sale?:boolean|null; criticalError?:boolean; geoAnalysis?:{department:string;province?:string;district?:string;primaryMotive?:string;mentionedMotives?:string[];fallResponsibility?:GeoCall['responsibility'];outcomeKnown?:boolean}|null };
type PublicAdvisor = { id:string; name:string; status:string; supervisorName:string };
type Snapshot = { dashboardType:Mode|'BOTH'; thresholds:{highGapMax:number;expectedMax:number}; company:{id:string;name:string}; campaign:{id:string;name:string}; generatedAt:string; expiresAt:string; advisors:PublicAdvisor[]; evaluations:PublicEvaluation[]; planStatuses?:{status:string;advisorIds:string[]}[] };
const EMPTY_SNAPSHOT:Snapshot={dashboardType:'QUALITY',thresholds:{highGapMax:60,expectedMax:90},company:{id:'',name:''},campaign:{id:'',name:''},generatedAt:'',expiresAt:'',advisors:[],evaluations:[],planStatuses:[]};
const movistarCriteria=new Map(TECHCENTER_MOVISTAR_FIELDS.map(field=>[`tc_mov_${field.id}`,{code:String(field.id),name:techcenterCriterionPresentation(field).criterion}]));
const average=(values:number[])=>values.length?Math.round(values.reduce((sum,value)=>sum+value,0)/values.length):null;
const scoreLabel=(value:number|null)=>value===null?'Sin datos':`${value}%`;
const scored=(item:PublicEvaluation)=>typeof item.score==='number'&&Number.isFinite(item.score);
const evaluable=(item:PublicEvaluation)=>item.evaluationType!=='QUALITY'||item.origin!=='SPEECH_ANALYTICS'||item.speechTypification!=='CORTA_LLAMADA';
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();
const periodKey=(date:string,granularity:'day'|'week'|'month')=>{
  if(granularity==='month')return date.slice(0,7);
  if(granularity==='day')return date;
  const day=new Date(`${date}T00:00:00Z`);day.setUTCDate(day.getUTCDate()-(day.getUTCDay()||7)+1);return day.toISOString().slice(0,10);
};
const trendLabel=(key:string,granularity:'day'|'week'|'month')=>granularity==='month'?new Date(`${key}-01T00:00:00Z`).toLocaleDateString('es-PE',{month:'short',year:'2-digit',timeZone:'UTC'}):`${granularity==='week'?'Sem. ':''}${new Date(`${key}T00:00:00Z`).toLocaleDateString('es-PE',{day:'2-digit',month:'short',timeZone:'UTC'})}`;
const validation=(status:string|null):Omit<StatusItem,'count'>=>{
  if(['VALIDATED','VALIDADO','AJUSTADO_VALIDADO'].includes(status||''))return{id:'validated',label:'Validada',tone:'success'};
  if(['AUTOMATIC_PENDING','PENDIENTE_AUTOMATICO'].includes(status||''))return{id:'pending',label:'Pendiente de validación',tone:'warning'};
  return{id:'unregistered',label:'Sin estado registrado',tone:'neutral'};
};

function buildSummary(snapshot:Snapshot,mode:Mode,origin:EvaluationOriginFilterValue,typification:SpeechFilterValue,advisorId:string,dateFrom:string,dateTo:string){
  const withinScope=(item:PublicEvaluation)=>item.evaluationType===mode&&(!dateFrom||item.date>=dateFrom)&&(!dateTo||item.date<=dateTo)&&(advisorId==='ALL'||item.advisorId===advisorId);
  const comparable=snapshot.evaluations.filter(item=>withinScope(item)&&evaluable(item));
  const selected=comparable.filter(item=>(origin==='ALL'||item.origin===origin)&&(origin!=='SPEECH_ANALYTICS'||typification==='ALL'||(typification==='SIN_TIPIFICACION'?!item.speechTypification:item.speechTypification===typification)));
  const scoredSelected=selected.filter(scored);
  const dateKeys=selected.map(item=>item.date).filter(Boolean).sort();
  const span=dateKeys.length>1?(Date.parse(dateKeys.at(-1)!)-Date.parse(dateKeys[0]))/86400000:0;
  const granularity:'day'|'week'|'month'=span<=31?'day':span<=180?'week':'month';
  const trends=new Map<string,number[]>();for(const item of scoredSelected){if(!item.date)continue;const key=periodKey(item.date,granularity);trends.set(key,[...(trends.get(key)||[]),item.score!]);}
  const trend:TrendPoint[]=[...trends.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,scores])=>({key,label:trendLabel(key,granularity),score:average(scores)!,count:scores.length}));
  const statuses=new Map<string,StatusItem>();for(const item of selected){const value=validation(item.validationStatus),prior=statuses.get(value.id);statuses.set(value.id,{...value,count:(prior?.count||0)+1});}
  const byAdvisor=new Map<string,{name:string;supervisor:string;scores:number[]}>();const bySupervisor=new Map<string,number[]>();
  for(const item of scoredSelected){const advisor=byAdvisor.get(item.advisorId)||{name:item.advisorName,supervisor:item.supervisorName,scores:[]};advisor.scores.push(item.score!);byAdvisor.set(item.advisorId,advisor);bySupervisor.set(item.supervisorName,[...(bySupervisor.get(item.supervisorName)||[]),item.score!]);}
  const advisors=[...byAdvisor.entries()].map(([id,item])=>({id,name:item.name,supervisor:item.supervisor,count:item.scores.length,score:average(item.scores)!})).sort((a,b)=>a.score-b.score||b.count-a.count);
  const supervisors=[...bySupervisor.entries()].map(([name,scores])=>({name,count:scores.length,score:average(scores)!})).sort((a,b)=>a.score-b.score);
  const criticalThreshold=snapshot.thresholds?.highGapMax||60;
  const criticalAdvisors=new Set(selected.filter(item=>scored(item)&&(item.score!<criticalThreshold||mode==='QUALITY'&&item.qualityResult==='REPROBADA')).map(item=>item.advisorId));
  const definitions=mode==='QUALITY'?QUALITY_ATTRIBUTES:CRITERIA_DEFINITIONS;
  const frequency=new Map<string,number>();for(const item of selected)for(const criterion of item.items)if(criterion.compliance==='NO_CUMPLE')frequency.set(criterion.criterionId,(frequency.get(criterion.criterionId)||0)+1);
  const totalFailures=[...frequency.values()].reduce((sum,count)=>sum+count,0);
  const pareto=[...frequency.entries()].map(([id,count])=>({id,name:movistarCriteria.get(id)?.name||definitions.find(definition=>definition.id===id)?.name||id,frequency:count,percentage:totalFailures?Math.round(count/totalFailures*1000)/10:0})).sort((a,b)=>b.frequency-a.frequency).slice(0,6);
  const movistarResults=new Map<string,{code:string;label:string;passed:number;total:number}>();
  if(mode==='QUALITY')for(const evaluation of selected)for(const item of evaluation.items){const criterion=movistarCriteria.get(item.criterionId);if(!criterion||(item.compliance!=='CUMPLE'&&item.compliance!=='NO_CUMPLE'))continue;const prior=movistarResults.get(item.criterionId)||{code:criterion.code,label:criterion.name,passed:0,total:0};prior.total++;if(item.compliance==='CUMPLE')prior.passed++;movistarResults.set(item.criterionId,prior);}
  const dimensions=mode==='D3C'?[{code:'D',label:'Dominio de Producto',value:null},{code:'C1',label:'Conectar',value:average(selected.flatMap(item=>item.scoreConnect===null?[]:[item.scoreConnect]))},{code:'C2',label:'Clarificar',value:average(selected.flatMap(item=>item.scoreClarify===null?[]:[item.scoreClarify]))},{code:'C3',label:'Convertir',value:average(selected.flatMap(item=>item.scoreConvert===null?[]:[item.scoreConvert]))}]:movistarResults.size?[...movistarResults.values()].sort((a,b)=>a.passed/a.total-b.passed/b.total||b.total-a.total).slice(0,4).map(item=>({code:item.code,label:item.label,value:Math.round(item.passed/item.total*100)})):(['C1','C2','C3','C4'] as const).map((code,index)=>{const ids=new Set(QUALITY_ATTRIBUTES.filter(attribute=>attribute.criterion===code).map(attribute=>attribute.id));const items=selected.flatMap(item=>item.items.filter(criterion=>ids.has(criterion.criterionId as typeof QUALITY_ATTRIBUTES[number]['id'])&&criterion.compliance!=='NO_APLICA'));return{code,label:['Conexión y diagnóstico','Oferta y condiciones','Cierre y formalización','Cumplimiento transversal'][index],value:items.length?Math.round(items.filter(item=>item.compliance==='CUMPLE').length/items.length*100):null};});
  const originAverage=(speech:boolean)=>average(comparable.filter(item=>(item.origin==='SPEECH_ANALYTICS')===speech&&scored(item)).map(item=>item.score!));
  const shortCalls=snapshot.evaluations.filter(item=>withinScope(item)&&item.origin==='SPEECH_ANALYTICS'&&item.speechTypification==='CORTA_LLAMADA').length;
  return{selected,scoredSelected,trend,granularity,statuses:[...statuses.values()].sort((a,b)=>b.count-a.count),advisors,supervisors,criticalThreshold,criticalAdvisors:criticalAdvisors.size,pareto,dimensions,hasMovistarCriteria:movistarResults.size>0,manual:originAverage(false),speech:originAverage(true),average:average(scoredSelected.map(item=>item.score!)),shortCalls};
}

export const PublicDashboardView:React.FC=()=>{
  const token=window.location.pathname.match(/^\/share\/dashboard\/([^/]+)\/?$/)?.[1]||'';
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [legacyMode,setLegacyMode]=useState<Mode>('QUALITY');
  const [origin,setOrigin]=useState<EvaluationOriginFilterValue>('ALL');
  const [typification,setTypification]=useState<SpeechFilterValue>('ALL');
  const [advisorId,setAdvisorId]=useState('ALL');
  const [dateFrom,setDateFrom]=useState('');
  const [dateTo,setDateTo]=useState('');
  const [filtersOpen,setFiltersOpen]=useState(false);
  const [refreshKey,setRefreshKey]=useState(0);
  useEffect(()=>{let alive=true;setLoading(true);setError('');fetch(`/api/public/dashboard/${encodeURIComponent(token)}`,{cache:'no-store'}).then(async response=>{const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Enlace no disponible.');return data as Snapshot;}).then(data=>{if(alive)setSnapshot(data);}).catch(cause=>{if(alive)setError(cause instanceof Error?cause.message:'No se pudo cargar el dashboard.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[token,refreshKey]);
  const mode:Mode=snapshot?.dashboardType==='D3C'||snapshot?.dashboardType==='QUALITY'?snapshot.dashboardType:legacyMode;
  const data=useMemo(()=>buildSummary(snapshot||EMPTY_SNAPSHOT,mode,origin,typification,advisorId,dateFrom,dateTo),[snapshot,mode,origin,typification,advisorId,dateFrom,dateTo]);
  const currentAdvisors=snapshot?.advisors.filter(item=>advisorId==='ALL'||item.id===advisorId)||[];
  const methodology=mode==='QUALITY'?'Calidad':'Mejora Continua · D+3C';
  const scoreKind=mode==='QUALITY'?'PUE':'D+3C';
  const maxPareto=Math.max(...data.pareto.map(item=>item.frequency),1);
  if(mode==='QUALITY')return <PublicQualityPage snapshot={snapshot} loading={loading} error={error} data={data} origin={origin} setOrigin={setOrigin} typification={typification} setTypification={setTypification} advisorId={advisorId} setAdvisorId={setAdvisorId} dateFrom={dateFrom} setDateFrom={setDateFrom} dateTo={dateTo} setDateTo={setDateTo} onRefresh={()=>setRefreshKey(key=>key+1)} onSelectLegacyMode={setLegacyMode}/>;
  return <div className="min-h-screen bg-[#0b1727] text-slate-100">
    <header className="border-b border-slate-700 bg-[#101f32] px-5 py-4 sm:px-9"><div className="mx-auto flex max-w-[1720px] items-center justify-between gap-3"><strong className="text-lg">C&amp;M <small className="ml-2 text-xs font-medium text-cyan-300">Calidad y Mejora Continua</small></strong><span className="rounded-full border border-emerald-800 px-3 py-1 text-xs text-emerald-300">Vista pública · solo lectura</span></div></header>
    <main className="cm-page cm-home-executive mx-auto max-w-[1720px] px-5 py-6 sm:px-9">
      <PageHeader breadcrumbs={['Dashboard compartido',snapshot?.company.name||'Empresa',snapshot?.campaign.name||'Campaña']} title={snapshot?`${methodology} · ${snapshot.campaign.name}`:'Dashboard compartido'} description={snapshot?`${snapshot.company.name} / ${snapshot.campaign.name} · Indicadores del alcance compartido`:'Cargando información de la campaña…'} actions={<Button variant="secondary" size="sm" leadingIcon={<RefreshCw/>} onClick={()=>setRefreshKey(key=>key+1)}>Actualizar</Button>} context={<div className="cm-home-dashboard-controls"><div className="flex flex-wrap items-center gap-2"><Badge variant="info">{methodology}</Badge>{snapshot?.dashboardType==='BOTH'&&<Select aria-label="Vista de enlace anterior" value={legacyMode} onChange={event=>setLegacyMode(event.target.value as Mode)}><option value="QUALITY">Calidad</option><option value="D3C">Mejora Continua · D+3C</option></Select>}</div><Button type="button" variant="secondary" size="sm" leadingIcon={<Filter/>} aria-expanded={filtersOpen} aria-controls="public-dashboard-filters" onClick={()=>setFiltersOpen(open=>!open)}>Filtros</Button></div>}/>
      {loading&&<p role="status">Cargando indicadores…</p>}{error&&<div role="alert" className="cm-data-warning">{error}</div>}
      {snapshot&&!loading&&<>
        <section className="cm-exec-filters-region" aria-label="Controles de filtrado"><div id="public-dashboard-filters" className={`cm-exec-filters-collapse ${filtersOpen?'is-open':''}`} aria-hidden={!filtersOpen} inert={!filtersOpen}><div><div className="cm-exec-filters"><div className="cm-exec-filters__grid"><label className="cm-field"><span className="cm-field__label">Empresa</span><span className="cm-input">{snapshot.company.name}</span></label><label className="cm-field"><span className="cm-field__label">Campaña / operación</span><span className="cm-input">{snapshot.campaign.name}</span></label><label className="cm-field"><span className="cm-field__label">Asesor</span><Select aria-label="Filtrar asesor" value={advisorId} onChange={event=>setAdvisorId(event.target.value)}><option value="ALL">Todos los asesores</option>{snapshot.advisors.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></label><label className="cm-field"><span className="cm-field__label">Desde</span><input className="cm-input" aria-label="Fecha desde" type="date" value={dateFrom} onChange={event=>setDateFrom(event.target.value)}/></label><label className="cm-field"><span className="cm-field__label">Hasta</span><input className="cm-input" aria-label="Fecha hasta" type="date" value={dateTo} onChange={event=>setDateTo(event.target.value)}/></label></div><div className="cm-exec-filters__context"><span>{data.selected.length} evaluaciones · {snapshot.company.name} · {snapshot.campaign.name}</span><button className="cm-link" onClick={()=>{setAdvisorId('ALL');setDateFrom('');setDateTo('');setOrigin('ALL');setTypification('ALL');}}>Limpiar filtros</button></div></div></div></div>{!filtersOpen&&<p className="cm-exec-filters-summary">{data.selected.length} evaluaciones · {snapshot.company.name} · {snapshot.campaign.name}</p>}</section>
        <section className="cm-kpi-grid" aria-label="Indicadores ejecutivos"><KpiCard label={`Resultado global ${scoreKind}`} value={scoreLabel(data.average)} detail={`${data.scoredSelected.length} evaluaciones con nota`} icon={<Activity/>} className={data.average===null?undefined:data.average<data.criticalThreshold?'is-danger':'is-success'}/><KpiCard label="Evaluaciones realizadas" value={String(data.selected.length)} detail="Registros del periodo" icon={<CheckSquare/>}/><KpiCard label="Asesores críticos" value={data.selected.length?String(data.criticalAdvisors):'Sin datos'} detail={`Resultado bajo ${data.criticalThreshold}%`} icon={<UsersRound/>} className={data.criticalAdvisors?'is-danger':undefined}/><KpiCard label="Nota evaluaciones manuales" value={scoreLabel(data.manual)} detail="Promedio del alcance" icon={<CheckSquare/>}/><KpiCard label="Nota Speech Analytics" value={origin==='SPEECH_ANALYTICS'&&typification==='CORTA_LLAMADA'?'No evaluable':scoreLabel(data.speech)} detail="Sin llamadas cortas" icon={<BarChart3/>}/></section>
        <section className="cm-exec-grid cm-exec-grid--overview"><QualityTrendCard data={data.trend} threshold={mode==='D3C'?snapshot.thresholds?.expectedMax||90:null} granularity={data.granularity}/><CompanyDistributionCard data={data.selected.length?[{id:snapshot.company.id,name:snapshot.company.name,count:data.selected.length,percentage:100}]:[]}/><EvaluationStatusCard data={data.statuses}/></section>
        <section aria-labelledby="public-priorities"><div className="cm-section-heading"><div><p>PRIORIDADES OPERATIVAS</p><h2 id="public-priorities">Dónde dirigir la atención</h2></div><span>Datos del alcance actual</span></div><div className="cm-exec-grid cm-exec-grid--priorities">
          <Card><CardHeader title="Ranking de campañas" description="Identidad por operación y empresa"/>{data.selected.length?<div className="cm-ranking-table" role="table" aria-label="Ranking de campañas"><div role="row"><span>#</span><span>Campaña</span><span>Eval.</span><span>Resultado</span><span>Tend.</span></div><div role="row"><span>1</span><b title={snapshot.campaign.name}>{snapshot.company.name} / {snapshot.campaign.name}</b><span>{data.selected.length}</span><strong>{scoreLabel(data.average)}</strong><span>{data.trend.length>1?`${Math.round((data.trend.at(-1)!.score-data.trend.at(-2)!.score)*10)/10} pp`:'—'}</span></div></div>:<EmptyState description="No hay evaluaciones de esta campaña en el periodo."/>}</Card>
          <Card><CardHeader title="Supervisores que requieren atención" description={`Resultado promedio bajo ${data.criticalThreshold}%`}/>{data.supervisors.filter(item=>item.score<data.criticalThreshold).length?<div className="cm-attention-list">{data.supervisors.filter(item=>item.score<data.criticalThreshold).slice(0,5).map(item=><div key={item.name}><span className="cm-avatar" aria-hidden="true">{initials(item.name)}</span><span><b title={item.name}>{item.name}</b><small>{snapshot.campaign.name}</small></span><strong>{item.score}%<small>{item.count} eval.</small></strong></div>)}</div>:<EmptyState description="No hay supervisores bajo el umbral crítico en este alcance."/>}</Card>
          <Card><CardHeader title="Asesores con menor resultado" description={`Ranking por nota promedio ${scoreKind}`}/>{data.advisors.length?<div className="cm-attention-list">{data.advisors.slice(0,5).map((item,index)=><div key={item.id}><span className="cm-avatar" aria-hidden="true">{initials(item.name)}</span><span><b title={item.name}>{index+1}. {item.name}</b><small>{snapshot.campaign.name} · {item.supervisor}</small></span><strong>{item.score}%<small>{item.count} eval.</small></strong></div>)}</div>:<EmptyState description={`No hay asesores con evaluaciones ${scoreKind} en este alcance.`}/>}</Card>
        </div></section>
        <section aria-labelledby="public-methodology"><div className="cm-section-heading"><div><p>{mode==='D3C'?'MEJORA CONTINUA':'CALIDAD'}</p><h2 id="public-methodology">Brechas y dominio</h2></div></div><div className="cm-exec-grid cm-exec-grid--methodology"><Card><CardHeader title={mode==='D3C'?'Pareto de brechas (80/20)':'Pareto de incumplimientos'} description="Top de oportunidades por frecuencia"/>{data.pareto.length?<div className="cm-ranked-list">{data.pareto.map(item=><div key={item.id} title={`${item.name}: ${item.frequency} casos, ${item.percentage}%`}><span>{item.name}</span><i><em style={{width:`${item.frequency/maxPareto*100}%`}}/></i><b>{item.frequency}<small>{item.percentage}%</small></b></div>)}</div>:<EmptyState description="Aún no hay brechas registradas en este alcance."/>}</Card><Card><CardHeader title={mode==='D3C'?'Dominio D+3C':data.hasMovistarCriteria?'Criterios de la ficha Movistar':'Criterios PUE'} description="Promedio por criterio"/><div className="cm-dimension-list">{data.dimensions.map(item=><div key={item.code}><span>{item.code}</span><i><b>{item.label}</b><em>{item.value!==null&&<u style={{width:`${item.value}%`}}/>}</em></i><strong>{scoreLabel(item.value)}</strong></div>)}</div></Card></div></section>
        <section className="cm-exec-grid cm-exec-grid--closing"><Card className="cm-feature-card cm-feature-card--improvement"><span><TrendingUp/></span><div><small>C&amp;M</small><h2>Mejora Continua</h2><p>Identifica brechas y prioriza acciones sobre la campaña compartida.</p></div></Card><Card className="cm-feature-card cm-feature-card--quality"><span><ShieldCheck/></span><div><small>C&amp;M</small><h2>Calidad</h2><p>Consulta cumplimiento, resultados y consistencia del alcance compartido.</p></div></Card><Card><CardHeader title="Evaluaciones recientes" description={`Últimos registros ${scoreKind}`}/>{data.selected.length?<div className="cm-recent-list">{data.selected.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(item=><div key={item.id} className="grid grid-cols-[30px_1fr_auto] items-center gap-2 p-2"><span className="cm-avatar" aria-hidden="true">{initials(item.advisorName)}</span><span className="min-w-0"><b className="block truncate text-[10px]" title={item.advisorName}>{item.advisorName}</b><small className="block truncate text-[9px] text-[var(--cm-text-muted)]">{item.date} · {snapshot.campaign.name}</small></span><span className="text-right"><strong className="block text-[10px]">{scoreLabel(item.score)}</strong><Badge variant={validation(item.validationStatus).tone}>{validation(item.validationStatus).label}</Badge></span></div>)}</div>:<EmptyState description="No hay evaluaciones recientes en este alcance."/>}</Card></section>
        <section className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><CardHeader title="Resultado por asesor" description="Nombres y promedios del alcance seleccionado"/><div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-700"><th className="py-2">Asesor</th><th>Supervisor</th><th>Eval.</th><th>Nota</th></tr></thead><tbody>{data.advisors.map(item=><tr key={item.id} className="border-b border-slate-800"><td className="py-2">{item.name}</td><td>{item.supervisor}</td><td>{item.count}</td><td>{item.score}%</td></tr>)}</tbody></table>{!data.advisors.length&&<EmptyState description="Sin resultados para mostrar."/>}</div></Card><Card className="p-5"><CardHeader title="Dotación de la campaña" description={`${currentAdvisors.filter(item=>item.status==='ACTIVO').length} activos de ${currentAdvisors.length} asesores`}/><div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-700"><th className="py-2">Asesor</th><th>Supervisor</th><th>Estado</th></tr></thead><tbody>{currentAdvisors.map(item=><tr key={item.id} className="border-b border-slate-800"><td className="py-2">{item.name}</td><td>{item.supervisorName}</td><td>{item.status}</td></tr>)}</tbody></table></div></Card></section>
        <p className="text-right text-xs text-[var(--cm-text-muted)]">Actualizado {new Date(snapshot.generatedAt).toLocaleString('es-PE')} · Enlace vigente hasta {new Date(snapshot.expiresAt).toLocaleDateString('es-PE')}</p>
      </>}
    </main>
  </div>;
};

type QualityPageProps={
  snapshot:Snapshot|null; loading:boolean; error:string; data:ReturnType<typeof buildSummary>;
  origin:EvaluationOriginFilterValue; setOrigin:(value:EvaluationOriginFilterValue)=>void;
  typification:SpeechFilterValue; setTypification:(value:SpeechFilterValue)=>void;
  advisorId:string; setAdvisorId:(value:string)=>void; dateFrom:string; setDateFrom:(value:string)=>void;
  dateTo:string; setDateTo:(value:string)=>void; onRefresh:()=>void; onSelectLegacyMode:(value:Mode)=>void;
};

const PublicQualityPage:React.FC<QualityPageProps>=({snapshot,loading,error,data,origin,setOrigin,typification,setTypification,advisorId,setAdvisorId,dateFrom,setDateFrom,dateTo,setDateTo,onRefresh,onSelectLegacyMode})=>{
  const [selectedDepartment,setSelectedDepartment]=useState('');
  const [filtersOpen,setFiltersOpen]=useState(false);
  const selected=data.selected;
  const activeAdvisors=snapshot?.advisors.filter(advisor=>advisor.status==='ACTIVO'&&(advisorId==='ALL'||advisor.id===advisorId))||[];
  const coverage=new Set(selected.map(item=>item.advisorId).filter(id=>activeAdvisors.some(advisor=>advisor.id===id))).size;
  const critical=selected.filter(item=>item.criticalError).length;
  const statuses=(snapshot?.planStatuses||[]).filter(plan=>advisorId==='ALL'||plan.advisorIds.includes(advisorId)).map(plan=>plan.status);
  const typifications=new Map<string,number>();
  for(const item of selected){const raw=item.typification?.trim()||item.geoAnalysis?.primaryMotive||item.speechTypification||'Sin tipificación';const label=normalizeMotive(raw)==='Cobertura / señal'?'Señal deficiente / No hay señal':raw;typifications.set(label,(typifications.get(label)||0)+1);}
  const geoCalls:GeoCall[]=selected.map(item=>({id:item.id,department:item.geoAnalysis?.department||'No identificado',province:item.geoAnalysis?.province,district:item.geoAnalysis?.district,sale:item.geoAnalysis?.outcomeKnown===false?null:item.sale??null,primaryMotive:item.geoAnalysis?.primaryMotive,mentionedMotives:item.geoAnalysis?.mentionedMotives,responsibility:item.geoAnalysis?.primaryMotive==='Cobertura / señal'?'NEGOCIO':item.geoAnalysis?.fallResponsibility||undefined,advisorId:item.advisorId,date:item.date,audioId:''}));
  const maxFailure=Math.max(1,...data.pareto.map(item=>item.frequency));
  const cards=[
    {label:'Resultado global PUE',value:scoreLabel(data.average),detail:`${data.scoredSelected.length} evaluaciones con nota`,icon:<ClipboardCheck/>},
    {label:'Cobertura de Calidad',value:`${coverage}/${activeAdvisors.length}`,detail:'Asesores activos evaluados del alcance',icon:<UsersRound/>},
    {label:'Errores críticos',value:selected.length?String(critical):'Sin datos',detail:critical?'Evaluaciones con error crítico':'Sin errores críticos',icon:<AlertTriangle/>},
    {label:'Evaluaciones PUE',value:selected.length?String(selected.length):'Sin datos',detail:'Registros del período',icon:<CheckSquare/>},
    {label:'Planes de acción',value:statuses.length?String(statuses.length):'Sin datos',detail:`${statuses.filter(status=>status==='EN_CURSO'||status==='PENDIENTE').length} en ejecución`,icon:<ListChecks/>},
  ];
  return <div className="cm-dashboard-legacy quality-dashboard min-h-screen bg-[#0b1727] text-slate-100">
    <header className="border-b border-slate-700 bg-[#101f32] px-5 py-4 sm:px-9"><div className="mx-auto flex max-w-[1720px] items-center justify-between gap-3"><strong className="text-lg">C&amp;M <small className="ml-2 text-xs font-medium text-cyan-300">Calidad y Mejora Continua</small></strong><span className="rounded-full border border-emerald-800 px-3 py-1 text-xs text-emerald-300">Vista pública · solo lectura</span></div></header>
    <main className="cm-page mx-auto max-w-[1720px] space-y-4 px-5 py-6 sm:px-9">
      <div className="cm-page-heading flex items-center justify-between gap-3"><div><span className="cm-eyebrow">CALIDAD · {snapshot?.campaign.name||'Campaña'}</span><h1 className="text-lg font-bold">Dashboard Calidad</h1><p className="text-xs text-[#b9c9dc]">{snapshot?`${snapshot.company.name} / ${snapshot.campaign.name} · Cumplimiento, cobertura y riesgos críticos`:'Cargando campaña…'}</p></div><div className="flex items-center gap-2">{snapshot?.dashboardType==='BOTH'&&<Select aria-label="Vista de enlace anterior" value="QUALITY" onChange={event=>onSelectLegacyMode(event.target.value as Mode)}><option value="QUALITY">Calidad</option><option value="D3C">Mejora Continua · D+3C</option></Select>}<Button variant="secondary" size="sm" leadingIcon={<RefreshCw/>} onClick={onRefresh}>Actualizar</Button></div></div>
      {loading&&<p role="status">Cargando indicadores…</p>}{error&&<div role="alert" className="cm-data-warning">{error}</div>}
      {snapshot&&!loading&&<>
        <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-3"><EvaluationOriginFilter value={origin} onChange={value=>{setOrigin(value);setTypification('ALL');}}/>{origin==='SPEECH_ANALYTICS'&&<SpeechTypificationFilter value={typification} onChange={setTypification}/>}</div><Button variant="secondary" size="sm" leadingIcon={<Filter/>} onClick={()=>setFiltersOpen(open=>!open)} aria-expanded={filtersOpen}>Filtros</Button></div>
        {filtersOpen&&<section className="grid gap-3 rounded-xl border border-slate-700 p-4 sm:grid-cols-3" aria-label="Filtros de Calidad"><label className="cm-field"><span className="cm-field__label">Asesor</span><Select value={advisorId} onChange={event=>setAdvisorId(event.target.value)}><option value="ALL">Todos los asesores</option>{snapshot.advisors.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(advisor=><option key={advisor.id} value={advisor.id}>{advisor.name}</option>)}</Select></label><label className="cm-field"><span className="cm-field__label">Desde</span><input className="cm-input" type="date" value={dateFrom} onChange={event=>setDateFrom(event.target.value)}/></label><label className="cm-field"><span className="cm-field__label">Hasta</span><input className="cm-input" type="date" value={dateTo} onChange={event=>setDateTo(event.target.value)}/></label></section>}
        <p className="text-xs text-slate-400">{selected.length} evaluaciones · {snapshot.company.name} · {snapshot.campaign.name}{data.shortCalls?` · ${data.shortCalls} llamadas cortas excluidas de la nota`:''}</p>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(card=><article key={card.label} className="rounded-2xl bg-white p-3.5 ring-1 ring-[#E2E9E9]"><div className="flex items-start justify-between"><span className="text-[10px] font-bold uppercase tracking-wide text-[#b9c9dc]">{card.label}</span><span className="rounded-xl bg-[#E8F5F4] p-1.5 text-cyan-400">{card.icon}</span></div><b className="mt-3 block text-2xl tracking-tight">{card.value}</b><p className="mt-1 text-[11px] text-[#b9c9dc]">{card.detail}</p></article>)}</div>
        <React.Suspense fallback={<p role="status">Cargando mapa de Perú…</p>}><MovistarGeoCard calls={geoCalls} demo={false} selectedDepartment={selectedDepartment} onDepartmentChange={setSelectedDepartment} dateFrom={dateFrom} dateTo={dateTo} advisorId={advisorId==='ALL'?'':advisorId}/></React.Suspense>
        <div className="grid gap-3 xl:grid-cols-[1.25fr_.85fr_.9fr]"><section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><h2 className="text-sm font-bold uppercase tracking-wide">Pareto de incumplimientos (80/20)</h2>{data.pareto.length?<div className="cm-quality-pareto">{data.pareto.map(item=><div className="cm-quality-pareto__column" key={item.id} title={`${item.name}: ${item.frequency} incumplimientos`}><div className="cm-quality-pareto__plot"><b>{item.frequency}</b><i style={{height:`${Math.max(10,item.frequency/maxFailure*100)}%`}}/></div><strong>{movistarCriteria.get(item.id)?.code||item.id}</strong><small>{item.name}</small></div>)}</div>:<p className="grid h-52 place-items-center text-sm text-slate-400">No hay incumplimientos registrados</p>}</section>
          <section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><h2 className="text-sm font-bold uppercase tracking-wide">{data.hasMovistarCriteria?'Criterios de la ficha Movistar':'Criterios PUE'}</h2><div className="mt-3 space-y-2">{data.dimensions.map(item=><div key={item.code} className="rounded-xl border border-[#E2E9E9] p-3"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-md bg-[#004F50] text-xs font-bold text-white">{item.code}</span><span className="flex-1 text-xs font-semibold">{item.label}</span><b className="text-xs">{scoreLabel(item.value)}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-[#E8EEEE]"><div className="h-full rounded bg-[#00B8B0]" style={{width:`${item.value||0}%`}}/></div></div>)}</div></section>
          <section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><h2 className="text-sm font-bold uppercase tracking-wide">Participación por tipificación</h2>{selected.length?<div className="mt-2 max-h-80 space-y-3 overflow-y-auto">{[...typifications].sort((a,b)=>b[1]-a[1]).map(([label,count])=><div key={label} className="border-b border-[#EAF0F0] pb-2 text-xs"><div className="flex justify-between gap-2"><span title={label}>{label}</span><b>{(count/selected.length*100).toFixed(1)}%</b></div><div className="mt-1 h-1.5 overflow-hidden rounded bg-[#E8EEEE]"><div className="h-full rounded bg-[#00B8B0]" style={{width:`${count/selected.length*100}%`}}/></div><small>{count} de {selected.length} evaluaciones</small></div>)}</div>:<p className="grid h-52 place-items-center text-sm text-slate-400">Sin datos</p>}</section></div>
        <section className="flex flex-wrap items-center gap-5 rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><b className="text-sm">Planes de acción</b>{([['En ejecución',statuses.filter(status=>status==='EN_CURSO'||status==='PENDIENTE').length],['Completados',statuses.filter(status=>status==='COMPLETADO').length],['Vencidos',statuses.filter(status=>status==='VENCIDO').length],['Total',statuses.length]] as const).map(([label,count])=><span key={label} className="text-xs"><b className="mr-2 text-cyan-400">{count}</b>{label}</span>)}</section>
        {data.supervisors.length>0&&<section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><h2 className="text-sm font-bold uppercase tracking-wide">Resultados por supervisor</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{data.supervisors.map(item=><div key={item.name} className="rounded-xl bg-[#F0F7F7] p-3"><b className="text-xs">{item.name}</b><span className="mt-1 block text-xl font-bold text-cyan-400">{item.score}%</span></div>)}</div></section>}
        <p className="text-right text-xs text-slate-400">Actualizado {new Date(snapshot.generatedAt).toLocaleString('es-PE')} · Enlace vigente hasta {new Date(snapshot.expiresAt).toLocaleDateString('es-PE')}</p>
      </>}
    </main>
  </div>;
};
