import React, { useEffect } from 'react';
import { AlertTriangle, BarChart3, CheckCircle2, ClipboardCheck, ListChecks, ShieldCheck, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { QUALITY_ATTRIBUTES } from '../../data/qualityPueData';
import { FiltersBar } from '../common/FiltersBar';

const value = (number: number | null, suffix = '%') => number === null ? 'Sin datos' : `${number}${suffix}`;
export const QualityDashboardView: React.FC = () => {
  const { filteredEvaluations, advisors, users, actionPlans, setCurrentSection, setFilters } = useApp();
  useEffect(() => { setFilters(previous => ({ ...previous, evaluationType: 'QUALITY' })); return () => setFilters(previous => previous.evaluationType === 'QUALITY' ? { ...previous, evaluationType: '' } : previous); }, [setFilters]);
  const quality = filteredEvaluations.filter(e => e.evaluationType === 'QUALITY');
  const scores = quality.map(e => e.scoreTotal).filter((score): score is number => score !== null);
  const average = scores.length ? Math.round(scores.reduce((sum, score) => sum + score, 0) / scores.length) : null;
  const coverage = quality.length ? new Set(quality.map(e => e.advisorId)).size : null;
  const critical = quality.length ? quality.filter(e => e.scoreTotal === 0 || e.qualityCriticalErrorIds?.length).length : null;
  const activePlans = actionPlans.filter(p => p.status === 'EN_CURSO' || p.status === 'PENDIENTE').length;
  const overdue = actionPlans.filter(p => p.status === 'VENCIDO').length;
  const criteria = ['C1', 'C2', 'C3', 'C4'].map((criterion, index) => {
    const items = QUALITY_ATTRIBUTES.filter(attribute => attribute.criterion === criterion);
    const results = quality.flatMap(evaluation => evaluation.items.filter(item => items.some(attribute => attribute.id === item.criterionId) && item.compliance !== 'NO_APLICA'));
    const score = results.length ? Math.round((results.filter(item => item.compliance === 'CUMPLE').length / results.length) * 100) : null;
    return { criterion, label: ['Conexión y diagnóstico', 'Oferta y condiciones', 'Cierre y formalización', 'Cumplimiento transversal'][index], score };
  });
  const failures = QUALITY_ATTRIBUTES.map(attribute => ({ ...attribute, count: quality.reduce((sum, evaluation) => sum + (evaluation.items.some(item => item.criterionId === attribute.id && item.compliance === 'NO_CUMPLE') ? 1 : 0), 0) })).sort((a, b) => b.count - a.count);
  const cards = [{ label: 'Resultado global PUE', display: value(average), detail: average === null ? 'Sin evaluaciones PUE' : `${quality.length} evaluaciones con score`, icon: <ClipboardCheck /> }, { label: 'Cobertura de Calidad', display: coverage === null ? 'Sin datos' : `${coverage}/${advisors.length}`, detail: coverage === null ? 'Sin asesores evaluados' : 'Asesores con PUE', icon: <Users /> }, { label: 'Errores críticos', display: critical === null ? 'Sin datos' : String(critical), detail: critical === null ? 'Sin evaluaciones PUE' : critical ? 'PUE anuladas por crítico' : 'Sin errores críticos', icon: <AlertTriangle /> }, { label: 'Evaluaciones PUE', display: quality.length || 'Sin datos', detail: quality.length ? 'Registros del período' : 'Sin registros del período', icon: <CheckCircle2 /> }, { label: 'Planes de acción', display: actionPlans.length || 'Sin datos', detail: activePlans ? `${activePlans} en ejecución` : 'Sin planes en ejecución', icon: <ListChecks /> }];
  return <div className="cm-workspace cm-dashboard-legacy quality-dashboard flex-1 overflow-y-auto bg-[#F7F9F9]"><FiltersBar /><div className="w-full space-y-4 px-5 py-5 sm:px-7"><div className="cm-page-heading flex items-center justify-between"><div><span className="cm-eyebrow">CALIDAD · PUE MIGRACIONES</span><h2 className="text-lg font-bold">Dashboard Calidad</h2><p className="text-xs text-[#66767A]">Cumplimiento, cobertura y riesgos críticos de Calidad.</p></div><button onClick={() => setCurrentSection('evaluations')} className="rounded-lg border border-[#00B8B0] px-3 py-1.5 text-xs font-bold text-[#006B6B] hover:bg-[#E8F5F4]">Ver evaluaciones →</button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(card => <article key={card.label} className="rounded-2xl bg-white p-3.5 ring-1 ring-[#E2E9E9]"><div className="flex items-start justify-between"><span className="text-[10px] font-bold uppercase tracking-wide text-[#66767A]">{card.label}</span><span className="rounded-xl bg-[#E8F5F4] p-1.5 text-[#008B88]">{card.icon}</span></div><b className="mt-3 block text-2xl tracking-tight">{card.display}</b><p className="mt-1 text-[11px] text-[#66767A]">{card.detail}</p></article>)}</div>
    <div className="grid gap-3 xl:grid-cols-[1.25fr_.85fr_.9fr]"><section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><PanelHeader title="Pareto de incumplimientos (80/20)" action="Ver detalle →" onClick={() => setCurrentSection('pareto')} />{quality.length ? <div className="mt-5 flex h-52 items-end gap-2 border-b border-[#E2E9E9] pb-1">{failures.map(item => <div className="flex min-w-0 flex-1 flex-col items-center gap-2" key={item.id}><span className="text-xs font-bold text-[#006B6B]">{item.count}</span><div className="w-full rounded-t-md bg-[#008B88]" style={{ height: `${Math.max(8, item.count / quality.length * 100)}%` }} /><span className="line-clamp-2 text-center text-[10px] text-[#66767A]">{item.code}</span></div>)}</div> : <Empty />}</section>
      <section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><PanelHeader title="Criterios PUE" action="Ver pauta →" onClick={() => setCurrentSection('methodology')} /><div className="mt-3 space-y-2">{criteria.map(item => <div key={item.criterion} className="rounded-xl border border-[#E2E9E9] p-3"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-md bg-[#004F50] text-xs font-bold text-white">{item.criterion}</span><span className="flex-1 text-xs font-semibold">{item.label}</span><b className="text-xs">{value(item.score)}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-[#E8EEEE]"><div className="h-full rounded bg-[#00B8B0]" style={{ width: `${item.score || 0}%` }} /></div></div>)}</div></section>
      <section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><PanelHeader title="Evaluaciones recientes" action="Ver todas →" onClick={() => setCurrentSection('evaluations')} />{quality.length ? <div className="mt-3 divide-y divide-[#EAF0F0]">{quality.slice(0, 5).map(evaluation => <div key={evaluation.id} className="flex items-center justify-between py-3 text-xs"><span className="font-semibold">{advisors.find(a => a.id === evaluation.advisorId)?.name || 'Asesor'}</span><span className="text-[#66767A]">PUE · {evaluation.date}</span><b className={evaluation.scoreTotal === 0 ? 'text-[#FF4D4F]' : 'text-[#16A085]'}>{value(evaluation.scoreTotal)}</b></div>)}</div> : <Empty />}</section></div>
    <section className="flex flex-wrap items-center gap-5 rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#008B88]" /><b className="text-sm">Planes de acción</b></div><Plan label="En ejecución" value={activePlans} /><Plan label="Completados" value={actionPlans.filter(p => p.status === 'COMPLETADO').length} /><Plan label="Vencidos" value={overdue} critical /><Plan label="Total" value={actionPlans.length} /><button onClick={() => setCurrentSection('action_plans')} className="ml-auto rounded-lg bg-[#004F50] px-4 py-2 text-xs font-bold text-white hover:bg-[#006B6B]">Ver planes de acción →</button></section>
    {quality.length > 0 && <section className="rounded-2xl bg-white p-4 ring-1 ring-[#E2E9E9]"><PanelHeader title="Resultados por supervisor" action="" onClick={() => {}} /><div className="mt-3 grid gap-2 md:grid-cols-3">{(Object.entries(quality.reduce((groups: Record<string, number[]>, evaluation) => { const key = users.find(user => user.id === evaluation.supervisorId)?.name || 'Sin supervisor'; (groups[key] ||= []).push(evaluation.scoreTotal || 0); return groups; }, {})) as Array<[string, number[]]>).map(([name, group]) => <div key={name} className="rounded-xl bg-[#F0F7F7] p-3"><b className="text-xs">{name}</b><span className="mt-1 block text-xl font-bold text-[#006B6B]">{Math.round(group.reduce((a,b) => a + b, 0) / group.length)}%</span></div>)}</div></section>}
  </div></div>;
};
const PanelHeader: React.FC<{ title: string; action: string; onClick: () => void }> = ({ title, action, onClick }) => <div className="flex items-center justify-between"><h3 className="text-sm font-bold uppercase tracking-wide">{title}</h3>{action && <button onClick={onClick} className="text-xs font-bold text-[#008B88]">{action}</button>}</div>;
const Empty = () => <p className="grid h-52 place-items-center text-sm text-[#66767A]">Sin datos</p>;
const Plan: React.FC<{ label: string; value: number; critical?: boolean }> = ({ label, value, critical }) => <div className="min-w-28"><b className={critical && value ? 'text-[#FF4D4F]' : 'text-[#004F50]'}>{value}</b><span className="ml-2 text-xs text-[#66767A]">{label}</span><div className="mt-1 h-1 rounded bg-[#E8EEEE]"><div className={`h-full rounded ${critical ? 'bg-[#FF4D4F]' : 'bg-[#00B8B0]'}`} style={{ width: `${value ? Math.min(100, value * 10) : 0}%` }} /></div></div>;
