import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ClipboardCheck, Clock3, MessageSquare, Scale, TrendingUp, Users } from 'lucide-react';
import { calibrationsApi, qualityAlertsApi } from '../../api/sharedRepository';
import { useApp } from '../../context/AppContext';
import type { Calibration, QualityAlert } from '../../types';

type Feedback={feedback_id:string;advisor_id:string;status:string}; const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('CONTACT_CENTER_AUTH_TOKEN')||''}`});
export const SupervisorHomeView:React.FC=()=>{
 const {currentUser,filteredEvaluations,filteredAdvisors,actionPlans,setCurrentSection}=useApp(); const [feedbacks,setFeedbacks]=useState<Feedback[]>([]);const [alerts,setAlerts]=useState<QualityAlert[]>([]);const [calibrations,setCalibrations]=useState<Calibration[]>([]);
 useEffect(()=>{void Promise.all([fetch('/api/feedbacks',{headers:auth()}).then(r=>r.ok?r.json():{feedbacks:[]}),qualityAlertsApi.list(),calibrationsApi.list()]).then(([f,a,c])=>{setFeedbacks((f.feedbacks||[]).filter((item:Feedback)=>item.status!=='CERRADO_SUPERVISOR'));setAlerts(a.alerts);setCalibrations(c.calibrations);});},[]);
 const teamIds=new Set(filteredAdvisors.map(item=>item.id));const plans=actionPlans.filter(item=>teamIds.has(item.advisorId));const quality=filteredEvaluations.filter(item=>item.evaluationType==='QUALITY');const avg=quality.length?Math.round(quality.reduce((s,e)=>s+(e.technicalScore??e.scoreTotal??0),0)/quality.length):null;
 const weeks=useMemo(()=>{const map:Record<string,number[]>={};for(const evaluation of quality){const date=new Date(`${evaluation.date}T00:00:00`);const monday=new Date(date);monday.setDate(date.getDate()-((date.getDay()+6)%7));const key=monday.toISOString().slice(0,10);(map[key]||=[]).push(evaluation.technicalScore??evaluation.scoreTotal??0);}return Object.entries(map).sort(([a],[b])=>a.localeCompare(b)).slice(-8).map(([week,scores])=>({week,score:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length)}));},[quality]);
 const advisorRows=filteredAdvisors.map(advisor=>{const rows=quality.filter(e=>e.advisorId===advisor.id).sort((a,b)=>b.date.localeCompare(a.date));const current=rows[0]?.technicalScore??rows[0]?.scoreTotal??null;const previous=rows[1]?.technicalScore??rows[1]?.scoreTotal??null;return{advisor,score:rows.length?Math.round(rows.reduce((s,e)=>s+(e.technicalScore??e.scoreTotal??0),0)/rows.length):null,last:rows[0]?.date||'—',count:rows.length,trend:current===null||previous===null?'—':current>previous?'↑':current<previous?'↓':'→'};});
 const pendingFeedbacks=feedbacks.filter(item=>item.status==='PENDIENTE').length;const observedFeedbacks=feedbacks.filter(item=>item.status==='OBSERVADO_ASESOR').length;const cards=[['Calidad promedio',avg===null?'—':`${avg}%`,<ClipboardCheck/>],['Feedback pendientes / observados',`${pendingFeedbacks} / ${observedFeedbacks}`,<MessageSquare/>],['Compromisos vencidos',plans.filter(p=>p.status==='VENCIDO'||(p.targetDate&&p.targetDate<new Date().toISOString().slice(0,10)&&p.status!=='COMPLETADO')).length,<Clock3/>],['Alertas activas',alerts.filter(a=>a.status!=='CERRADA').length,<AlertTriangle/>],['Calibraciones pendientes',calibrations.filter(c=>c.participants.some(p=>p.supervisorId===currentUser.id&&p.status==='PENDIENTE')).length,<Scale/>]];
 return <main className="cm-workspace flex-1 overflow-y-auto p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5"><header className="cm-page-heading"><p className="cm-eyebrow">GESTIÓN DE EQUIPO</p><h1 className="text-xl font-bold">Dashboard Supervisor</h1><p className="text-xs text-[var(--cm-text-secondary)]">Indicadores y pendientes exclusivos de tu equipo.</p></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([name,value,icon])=><article key={String(name)} className="cm-card p-4"><span className="text-[var(--cm-primary)]">{icon}</span><p className="mt-3 text-xs text-[var(--cm-text-secondary)]">{name}</p><b className="text-2xl">{value}</b></article>)}</section>
 <section className="cm-card p-4"><h2 className="flex items-center gap-2 font-bold"><TrendingUp className="h-4 w-4 text-[var(--cm-primary)]"/>Evolución semanal</h2><div className="mt-4 flex h-40 items-end gap-3">{weeks.length?weeks.map(row=><div key={row.week} className="flex flex-1 flex-col items-center gap-1"><b className="text-xs">{row.score}%</b><div className="w-full rounded-t bg-[var(--cm-primary)]" style={{height:`${Math.max(5,row.score)}%`}}/><span className="text-[9px] text-[var(--cm-text-secondary)]">{row.week.slice(5)}</span></div>):<p className="m-auto text-sm text-[var(--cm-text-secondary)]">Sin evaluaciones semanales.</p>}</div></section>
 <section className="cm-card overflow-hidden"><div className="border-b border-[var(--cm-border)] p-4"><h2 className="flex items-center gap-2 font-bold"><Users className="h-4 w-4 text-[var(--cm-primary)]"/>Asesores del equipo</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr>{['Asesor','Nota','Última evaluación','Cantidad','Estado','Tendencia'].map(v=><th key={v} className="p-3">{v}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{advisorRows.map(row=><tr key={row.advisor.id}><td className="p-3 font-semibold">{row.advisor.name}</td><td className="p-3">{row.score===null?'—':`${row.score}%`}</td><td className="p-3">{row.last}</td><td className="p-3">{row.count}</td><td className="p-3">{row.advisor.status}</td><td className="p-3 text-lg">{row.trend}</td></tr>)}</tbody></table></div></section>
 <section className="cm-card overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--cm-border)] p-4"><h2 className="font-bold">Seguimiento de compromisos</h2><button onClick={()=>setCurrentSection('action_plans')} className="text-xs text-[var(--cm-primary)]">Ver todos →</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead><tr>{['Asesor','Compromiso','Fecha','Estado'].map(v=><th key={v} className="p-3">{v}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{plans.map(plan=><tr key={plan.id}><td className="p-3">{filteredAdvisors.find(a=>a.id===plan.advisorId)?.name||'—'}</td><td className="p-3">{plan.action}</td><td className="p-3">{plan.targetDate||plan.dueDate||'—'}</td><td className="p-3">{plan.status==='COMPLETADO'?'Cumplido':plan.status==='VENCIDO'?'Vencido':'En curso'}</td></tr>)}</tbody></table>{!plans.length&&<p className="p-6 text-center text-sm text-[var(--cm-text-secondary)]">No hay compromisos registrados.</p>}</div></section></div></main>;
};
