import React,{useDeferredValue,useEffect,useState} from 'react';
import {AlertTriangle,ClipboardCheck,Clock3,MessageSquare,Users,X} from 'lucide-react';
const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('CONTACT_CENTER_AUTH_TOKEN')||''}`});
type Row={advisor:{id:string;name:string};score:number|null;lastEvaluation:string|null;feedbackState:string;evaluationCount:number};
type History={id:string;date:string;technicalScore?:number;scoreTotal?:number;qualityResult?:string};
type Data={metrics:{teamAverage:number|null;feedbackSignedPercent:number;feedbackPending:number;activeAlerts:number};advisors:Row[];ranking:Array<{advisorId:string;name:string;score:number}>;commitments:Array<{advisorId:string;text:string;date:string;status:string}>};
export const SupervisorHomeView:React.FC=()=>{
 const [data,setData]=useState<Data|null>(null),[advisor,setAdvisor]=useState(''),queryAdvisor=useDeferredValue(advisor),[feedback,setFeedback]=useState(''),[history,setHistory]=useState<History[]|null>(null),[historyLoading,setHistoryLoading]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();void(async()=>{setLoading(true);setError('');try{const query=new URLSearchParams();if(queryAdvisor)query.set('advisor',queryAdvisor);if(feedback)query.set('feedbackStatus',feedback);const response=await fetch(`/api/supervisor/dashboard?${query}`,{headers:auth(),signal:controller.signal}),body=await response.json();if(!response.ok)throw new Error(body.error||'No fue posible cargar el equipo.');setData(body);}catch(reason){if((reason as Error).name!=='AbortError')setError(reason instanceof Error?reason.message:'No fue posible cargar el equipo.');}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[queryAdvisor,feedback]);
 useEffect(()=>{if(!history)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setHistory(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[history]);
 const viewHistory=async(id:string)=>{setHistoryLoading(true);setError('');try{const response=await fetch(`/api/supervisor/advisors/${encodeURIComponent(id)}/evaluations`,{headers:auth()}),body=await response.json();if(!response.ok)throw new Error(body.error||'No fue posible cargar el historial.');setHistory(body.evaluations||[]);}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible cargar el historial.');}finally{setHistoryLoading(false);}};
 const cards=[['Nota promedio',data?.metrics.teamAverage==null?'—':`${data.metrics.teamAverage}%`,<ClipboardCheck key="score"/>],['Feedback firmado',`${data?.metrics.feedbackSignedPercent||0}%`,<MessageSquare key="feedback"/>],['Feedback pendiente',data?.metrics.feedbackPending||0,<Clock3 key="pending"/>],['Alertas activas',data?.metrics.activeAlerts||0,<AlertTriangle key="alerts"/>]];
 return <main className="cm-workspace flex-1 overflow-y-auto p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5">
  <header className="cm-page-heading"><p className="cm-eyebrow">GESTIÓN DE EQUIPO</p><h1 className="text-xl font-bold">Dashboard Supervisor</h1><p className="text-xs text-[var(--cm-text-secondary)]">Información autorizada de tu dotación.</p></header>
  {error&&<p className="cm-alert-error" role="alert">{error}</p>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-busy={loading}>{cards.map(([name,value,icon])=><article key={String(name)} className="cm-card p-4"><span className="text-[var(--cm-primary)]">{icon}</span><p className="mt-3 text-xs text-[var(--cm-text-secondary)]">{name}</p><b className="text-2xl">{loading&&!data?'…':value}</b></article>)}</section>
  <section className="cm-card p-4"><h2 className="flex items-center gap-2 font-bold"><Users className="h-4 w-4 text-[var(--cm-primary)]"/>Ranking de asesores</h2>{data?.ranking.length?<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{data.ranking.map((row,index)=><div key={row.advisorId} className="rounded border border-[var(--cm-border)] p-3 text-sm"><span className="text-[var(--cm-primary)]">#{index+1}</span><b className="ml-2">{row.name}</b><span className="float-right">{row.score}%</span></div>)}</div>:<p className="mt-3 text-sm text-[var(--cm-text-secondary)]">{loading?'Cargando ranking…':'Sin evaluaciones validadas para este alcance.'}</p>}</section>
  <section className="cm-card overflow-hidden"><div className="flex flex-wrap items-end gap-3 border-b border-[var(--cm-border)] p-4"><h2 className="mr-auto font-bold">Asesores del equipo</h2><label className="text-xs">Asesor<input value={advisor} onChange={event=>setAdvisor(event.target.value)} className="cm-input ml-2 w-40" placeholder="Buscar"/></label><label className="text-xs">Feedback<select value={feedback} onChange={event=>setFeedback(event.target.value)} className="cm-select ml-2"><option value="">Todos</option><option value="PENDIENTE">Pendiente</option><option value="FIRMADO">Firmado</option></select></label></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr>{['Asesor','Nota vigente','Última evaluación','Feedback','Acción'].map(value=><th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{data?.advisors.length?data.advisors.map(row=><tr key={row.advisor.id}><td className="p-3 font-semibold">{row.advisor.name}</td><td className="p-3">{row.score==null?'—':`${row.score}%`}</td><td className="p-3">{row.lastEvaluation||'—'}</td><td className="p-3">{row.feedbackState}</td><td className="p-3"><button disabled={historyLoading} onClick={()=>void viewHistory(row.advisor.id)} className="text-[var(--cm-primary)] disabled:opacity-50">Ver historial</button></td></tr>):<tr><td colSpan={5} className="p-6 text-center text-[var(--cm-text-secondary)]">{loading?'Cargando asesores…':'No hay asesores que coincidan con los filtros.'}</td></tr>}</tbody></table></div></section>
  <section className="cm-card overflow-hidden"><h2 className="border-b border-[var(--cm-border)] p-4 font-bold">Seguimiento de compromisos</h2><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead><tr>{['Asesor','Compromiso','Fecha','Estado'].map(value=><th key={value} className="p-3">{value}</th>)}</tr></thead><tbody className="divide-y divide-[var(--cm-border)]">{data?.commitments.length?data.commitments.map(item=><tr key={`${item.advisorId}-${item.date}-${item.text}`}><td className="p-3">{data.advisors.find(row=>row.advisor.id===item.advisorId)?.advisor.name||'Asesor del equipo'}</td><td className="p-3">{item.text}</td><td className="p-3">{item.date}</td><td className="p-3">{item.status}</td></tr>):<tr><td colSpan={4} className="p-6 text-center text-[var(--cm-text-secondary)]">{loading?'Cargando compromisos…':'No hay compromisos registrados.'}</td></tr>}</tbody></table></div></section>
  {history&&<div className="fixed inset-0 z-[210] flex items-center justify-center bg-slate-950/65 p-4" role="dialog" aria-modal="true" aria-labelledby="supervisor-history-title" onMouseDown={event=>{if(event.currentTarget===event.target)setHistory(null);}}><div className="cm-modal max-h-[80vh] w-full max-w-xl overflow-y-auto p-5"><div className="mb-3 flex items-center justify-between"><h2 id="supervisor-history-title" className="font-bold">Historial de evaluaciones</h2><button onClick={()=>setHistory(null)} aria-label="Cerrar historial"><X className="h-5 w-5"/></button></div>{history.length?history.map(item=><article className="mb-2 rounded border border-[var(--cm-border)] p-3 text-sm" key={item.id}><b>{item.date}</b><span className="ml-3">{item.technicalScore??item.scoreTotal??0}%</span><p className="mt-1 text-xs text-[var(--cm-text-secondary)]">{item.qualityResult||'Evaluación validada'} · Solo lectura</p></article>):<p className="rounded border border-dashed border-[var(--cm-border)] p-5 text-center text-sm text-[var(--cm-text-secondary)]">Este asesor aún no tiene evaluaciones validadas.</p>}</div></div>}
 </div></main>;
};
