import { DatabaseSync } from 'node:sqlite';
import { join } from 'node:path';
import { randomBytes, scryptSync } from 'node:crypto';

const db = new DatabaseSync(join(process.cwd(), 'data', 'contact-center.sqlite'));
const now = new Date().toISOString();
const passwordHash = (password) => { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(password, salt, 64).toString('hex')}`; };
const insert = (sql, values) => db.prepare(sql).run(...values);

const users = [
  ['usr_admin', 'Administrador Principal', 'admin@consultoria3c.com', 'admin', 'ADMINISTRADOR'],
  ['usr_sup_ana', 'Ana Ramírez', 'ana.ramirez@demo.local', 'ana.ramirez', 'SUPERVISOR'],
  ['usr_sup_carlos', 'Carlos Ruiz', 'carlos.ruiz@demo.local', 'carlos.ruiz', 'SUPERVISOR'],
  ['usr_eval_jose', 'José López', 'jose.lopez@demo.local', 'jose.lopez', 'CONSULTOR'],
  ['usr_eval_lucia', 'Lucía Medina', 'lucia.medina@demo.local', 'lucia.medina', 'CONSULTOR'],
];
const campaigns = [
  { id:'camp_mig', name:'Migraciones Premium', client:'Bitel Perú', products:['Portabilidad', 'Migraciones', 'BiPay'], description:'Operación de migraciones y retención.' },
  { id:'camp_post', name:'Postpago Digital', client:'Bitel Perú', products:['Plan Ilimitado', 'BiPay', 'Renovación'], description:'Venta consultiva de planes postpago.' },
];
const teams = [
  { id:'team_norte', campaignId:'camp_mig', supervisorId:'usr_sup_ana', name:'Equipo Norte' },
  { id:'team_sur', campaignId:'camp_post', supervisorId:'usr_sup_carlos', name:'Equipo Sur' },
];
const advisorNames = ['María Fernanda López','Juan Manuel Torres','Carla Sofía Ruiz','Daniel Gómez','Andrés Felipe Gómez','Laura Valentina Díaz','Esteban Sánchez','Paola Herrera','Ricardo Núñez','Valeria Castro','Miguel Ángel Rojas','Sofía Mendoza'];
const advisors = advisorNames.map((name, index) => {
  const team = teams[index % 2];
  return { id:`adv_demo_${index + 1}`, dni:`70${String(100001 + index).slice(-6)}`, employeeCode:`A-${10234 + index * 137}`, name, campaignId:team.campaignId, teamId:team.id, supervisorId:team.supervisorId, status:index === 10 ? 'EN_CAPACITACION' : 'ACTIVO', hireDate:`202${index % 3 + 3}-${String(index % 9 + 1).padStart(2,'0')}-15`, quartile:['Q1','Q2','Q3','Q4'][index % 4], active:index !== 10, schedule:index % 2 ? '08:00 - 17:00' : '09:00 - 18:00', baselineSph:Number((0.25 + index * .012).toFixed(2)), hasOperationalBaseline:true, baselineDate:'2026-06-30', baselinePeriod:'Línea Base Junio 2026' };
});
const criterionIds = ['fluidez_verbal','manejo_voz','seguridad_comunicativa','dominio_informacion','simplificacion_mensaje','traduccion_beneficio','argumentacion_comercial','manejo_objeciones','cierre_comercial'];
const qualityIds = ['q_1_1','q_1_2','q_2_1','q_3_1','q_3_2','q_4_1'];
const makeD3C = (advisor, index) => {
  const connect = 62 + (index * 7) % 33, clarify = 58 + (index * 9) % 37, convert = 55 + (index * 11) % 40;
  const total = Math.round(connect * .30 + clarify * .35 + convert * .35);
  return { id:`eval_d3c_${index + 1}`, advisorId:advisor.id, evaluatorId:index % 2 ? 'usr_eval_lucia' : 'usr_eval_jose', campaignId:advisor.campaignId, teamId:advisor.teamId, supervisorId:advisor.supervisorId, product:index % 2 ? 'Plan Ilimitado 59.90' : 'Migración con BiPay', date:`2026-08-${String(4 + index).padStart(2,'0')}`, time:`${String(9 + index % 7).padStart(2,'0')}:30`, callId:`LLAM-${71920 + index}`, recordingCode:`REC-D3C-${String(index + 1).padStart(3,'0')}`, type:index % 3 ? 'SEGUIMIENTO' : 'DIAGNOSTICO_INICIAL', evaluationType:'D3C', sale:index % 3 === 0, saleResult:index % 3 === 0 ? 'VENTA_CONCRETADA' : 'NO_VENTA', comments:'Evaluación de demostración con hallazgos y recomendaciones para el seguimiento.', scoreConnect:connect, scoreClarify:clarify, scoreConvert:convert, scoreTotal:total, primaryGap:index % 2 ? 'Manejo de objeciones' : 'Dominio de información', secondaryGap:'Fluidez verbal', strongestPillar:connect > clarify && connect > convert ? 'Conectar' : clarify > convert ? 'Clarificar' : 'Convertir', recommendation:'Realizar escucha guiada y práctica focalizada sobre la brecha principal.', items:criterionIds.map((criterionId, itemIndex) => ({ id:`${index}_${criterionId}`, criterionId, dimension:itemIndex < 3 ? 'CONECTAR' : itemIndex < 6 ? 'CLARIFICAR' : 'CONVERTIR', compliance:(itemIndex + index) % 5 === 0 ? 'NO_CUMPLE' : 'CUMPLE', level:(itemIndex + index) % 5 === 0 ? 1 : 4, percentage:(itemIndex + index) % 5 === 0 ? 0 : 100, finding:(itemIndex + index) % 5 === 0 ? 'Brecha observada durante la llamada.' : 'Evidencia de cumplimiento.' })), createdAt:`2026-08-${String(4 + index).padStart(2,'0')}T12:00:00.000Z` };
};
const makeQuality = (advisor, index) => {
  const critical = index === 7 ? ['ce_false_info'] : [];
  const answers = qualityIds.map((criterionId, itemIndex) => ({ id:`qitem_${index}_${criterionId}`, criterionId, dimension:itemIndex < 2 ? 'CONECTAR' : itemIndex < 4 ? 'CLARIFICAR' : 'CONVERTIR', compliance:critical.length ? (itemIndex === 2 ? 'NO_CUMPLE' : 'CUMPLE') : (itemIndex + index) % 6 === 0 ? 'NO_CUMPLE' : itemIndex === 4 && index % 3 === 0 ? 'NO_APLICA' : 'CUMPLE', percentage:0, level:4, finding:'Resultado registrado en pauta PUE.' }));
  const evaluated = answers.filter(item => item.compliance !== 'NO_APLICA'); const passed = evaluated.filter(item => item.compliance === 'CUMPLE').length;
  const score = critical.length ? 0 : Math.round(passed / evaluated.length * 100);
  return { id:`eval_quality_${index + 1}`, advisorId:advisor.id, evaluatorId:index % 2 ? 'usr_eval_jose' : 'usr_eval_lucia', campaignId:advisor.campaignId, teamId:advisor.teamId, supervisorId:advisor.supervisorId, product:'Migraciones y condiciones comerciales', date:`2026-08-${String(5 + index).padStart(2,'0')}`, time:`${String(10 + index % 6).padStart(2,'0')}:15`, callId:`PUE-${80200 + index}`, recordingCode:`REC-PUE-${String(index + 1).padStart(3,'0')}`, type:'SEGUIMIENTO', evaluationType:'QUALITY', qualityStatus:'FINALIZED', qualityCriticalErrorIds:critical, sale:false, saleResult:'NO_VENTA', comments:'Resultado de pauta PUE Migraciones. Se registraron hallazgos para retroalimentación.', scoreConnect:null, scoreClarify:null, scoreConvert:null, scoreTotal:score, primaryGap:critical.length ? 'Información falsa de la migración' : 'Ofrecimiento y condiciones', secondaryGap:'Consentimiento y validaciones', strongestPillar:'', recommendation:'Reforzar la validación, claridad de condiciones y cierre con el cliente.', items:answers, createdAt:`2026-08-${String(5 + index).padStart(2,'0')}T14:00:00.000Z` };
};
const evaluations = advisors.flatMap((advisor, index) => [makeD3C(advisor,index), makeQuality(advisor,index)]);
const actionPlans = evaluations.slice(0, 10).map((evaluation, index) => ({ id:`plan_demo_${index + 1}`, advisorId:evaluation.advisorId, evaluationId:evaluation.id, criterionId:index % 2 ? 'manejo_objeciones' : 'dominio_informacion', dimension:index % 2 ? 'CONVERTIR' : 'CLARIFICAR', objective:'Cerrar la brecha prioritaria identificada en la evaluación.', action:index % 2 ? 'Role play de manejo de objeciones y escucha de llamada modelo.' : 'Microentrenamiento de producto y validación de información.', responsibleId:evaluation.supervisorId, ownerId:evaluation.supervisorId, createdDate:evaluation.date, targetDate:`2026-09-${String(5 + index).padStart(2,'0')}`, status:['EN_CURSO','PENDIENTE','COMPLETADO','VENCIDO'][index % 4], notes:'Plan de demostración generado para seguimiento.', evidence:index % 3 === 0 ? 'Evidencia cargada por supervisor.' : '' }));
const operationalMeasurements = advisors.flatMap((advisor, index) => [
  { id:`op_base_${index + 1}`, advisorId:advisor.id, dni:advisor.dni, measurementDate:'2026-06-30', periodName:'Junio 2026', campaignId:advisor.campaignId, campaignName:campaigns.find(c => c.id === advisor.campaignId).name, connectionTime:'06:20', connectionMinutes:380, sph:advisor.baselineSph, quartile:advisor.quartile, source:'CARGA_EXCEL', createdAt:now },
  { id:`op_current_${index + 1}`, advisorId:advisor.id, dni:advisor.dni, measurementDate:'2026-08-31', periodName:'Agosto 2026', campaignId:advisor.campaignId, campaignName:campaigns.find(c => c.id === advisor.campaignId).name, connectionTime:'06:45', connectionMinutes:405, sph:Number((advisor.baselineSph + .05 + (index % 3) * .01).toFixed(2)), quartile:advisor.quartile, source:'CARGA_EXCEL', createdAt:now },
]);
const interventions = [
  { id:'int_demo_1', name:'Escucha guiada', title:'Escucha guiada: manejo de objeciones', dimension:'CONVERTIR', criterionId:'manejo_objeciones', type:'ESCUCHA_GUIADA', category:'Comercial', duration:'30 min', durationMins:30, description:'Escucha y análisis de una llamada modelo.', active:true },
  { id:'int_demo_2', name:'Microentrenamiento BiPay', title:'Claridad de beneficios BiPay', dimension:'CLARIFICAR', criterionId:'traduccion_beneficio', type:'MICROENTRENAMIENTO', category:'Producto', duration:'20 min', durationMins:20, description:'Práctica de beneficio y utilidad para el cliente.', active:true },
  { id:'int_demo_3', name:'Role play de cierre', title:'Cierre y consentimiento', dimension:'CONVERTIR', criterionId:'cierre_comercial', type:'ROLE_PLAY', category:'Cierre', duration:'45 min', durationMins:45, description:'Simulación con validaciones de calidad.', active:true },
];
const advisorInterventions = actionPlans.slice(0, 6).map((plan, index) => ({ id:`assign_demo_${index + 1}`, targetType:'INDIVIDUAL', advisorId:plan.advisorId, interventionId:interventions[index % interventions.length].id, title:interventions[index % interventions.length].title, dimension:interventions[index % interventions.length].dimension, type:interventions[index % interventions.length].type, duration:interventions[index % interventions.length].duration, evaluationId:plan.evaluationId, evaluationDate:plan.createdDate, assignedBy:'usr_sup_ana', assignedByName:'Ana Ramírez', assignedDate:plan.createdDate, scheduledDate:`2026-09-${String(4 + index).padStart(2,'0')}`, status:index % 3 === 0 ? 'COMPLETADA' : 'EN_PROGRESO', resultNotes:'Seguimiento de demostración registrado.' }));
const config = { weights:{ CONECTAR:30, CLARIFICAR:35, CONVERTIR:35, connect:30, clarify:35, convert:35 }, scaleValues:{1:25,2:50,3:75,4:100}, priorityThresholds:{highGapMax:60,mediumGapMax:80,expectedMax:90}, focusProductKey:'BiPay', tenureThresholdDays:90 };

db.exec('PRAGMA foreign_keys = ON; BEGIN IMMEDIATE; DELETE FROM feedbacks; DELETE FROM evaluations; DELETE FROM app_state; DELETE FROM sessions; DELETE FROM advisors; DELETE FROM teams; DELETE FROM campaigns; DELETE FROM users; COMMIT;');
for (const [id,name,email,username,role] of users) insert('INSERT INTO users (id,name,email,username,role,status,created_at,password_hash) VALUES (?,?,?,?,?,?,?,?)',[id,name,email,username,role,'ACTIVO',now,passwordHash(id === 'usr_admin' ? 'admin1234' : 'demo1234')]);
for (const campaign of campaigns) insert('INSERT INTO campaigns (id,name,client,status,products_json,description) VALUES (?,?,?,?,?,?)',[campaign.id,campaign.name,campaign.client,'ACTIVA',JSON.stringify(campaign.products),campaign.description]);
for (const team of teams) insert('INSERT INTO teams (id,campaign_id,supervisor_id,name) VALUES (?,?,?,?)',[team.id,team.campaignId,team.supervisorId,team.name]);
for (const advisor of advisors) insert('INSERT INTO advisors (id,dni,employee_code,name,campaign_id,team_id,supervisor_id,data_json) VALUES (?,?,?,?,?,?,?,?)',[advisor.id,advisor.dni,advisor.employeeCode,advisor.name,advisor.campaignId,advisor.teamId,advisor.supervisorId,JSON.stringify(advisor)]);
for (const evaluation of evaluations) insert('INSERT INTO evaluations (id,advisor_id,evaluator_id,evaluation_type,evaluated_at,payload_json,created_at) VALUES (?,?,?,?,?,?,?)',[evaluation.id,evaluation.advisorId,evaluation.evaluatorId,evaluation.evaluationType,`${evaluation.date}T${evaluation.time}:00`,JSON.stringify(evaluation),evaluation.createdAt]);
for (const [index,evaluation] of evaluations.slice(0, 12).entries()) { const status=['PENDIENTE','VALIDADO_ASESOR','OBSERVADO_ASESOR','CERRADO_SUPERVISOR'][index % 4]; insert('INSERT INTO feedbacks (feedback_id,evaluation_id,advisor_id,supervisor_id,evaluator_id,evaluation_type,feedback_text,advisor_response,supervisor_closure_comment,status,created_at,advisor_action_at,closed_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[`fb_demo_${index + 1}`,evaluation.id,evaluation.advisorId,evaluation.supervisorId,evaluation.evaluatorId,evaluation.evaluationType,'Feedback de demostración asociado a hallazgos de la evaluación.',status === 'PENDIENTE' ? null : 'Respuesta de demostración del asesor.',status === 'CERRADO_SUPERVISOR' ? 'Cierre y acuerdo registrado por el supervisor.' : null,status,evaluation.createdAt,status === 'PENDIENTE' ? null : now,status === 'CERRADO_SUPERVISOR' ? now : null,now]); }
insert('INSERT INTO app_state (id,payload_json,updated_at) VALUES (?,?,?)',['global',JSON.stringify({evaluations,actionPlans,interventions,advisorInterventions,operationalMeasurements,importHistory:[],config}),now]);
console.log(JSON.stringify({ users:users.length, campaigns:campaigns.length, teams:teams.length, advisors:advisors.length, evaluations:evaluations.length, feedbacks:12, actionPlans:actionPlans.length, interventions:interventions.length, operationalMeasurements:operationalMeasurements.length },null,2));
