import assert from 'node:assert/strict';
import { aggregateDepartments, geoHeatColor, matchesGeoMotive, normalizeDepartment, PERU_GEOJSON, resolveGeoAnalysis } from '../src/utils/movistarGeo';
import { MOVISTAR_GEO_DEMO } from '../src/data/movistarGeoDemo';
import { classificationError, classificationFromEvaluation, classificationPayload, DELIVERY_TYPIFICATION, PERU_DISTRICTS, requiresLocation, SECONDARY_SIGNAL_TYPIFICATION, SIGNAL_TYPIFICATION } from '../src/utils/evaluationTypification';
import type { Evaluation } from '../src/types';

assert.equal(normalizeDepartment('Áncash'),'ANCASH');
assert.equal(normalizeDepartment('Lima Provincia'),'LIMA');
assert.equal(normalizeDepartment('lugar imaginario'),'No identificado');
assert.equal(resolveGeoAnalysis({transcript:'Estoy en Pampa Chico, provincia de Recuay.'}).department,'ANCASH');
const classified=resolveGeoAnalysis({primaryMotive:'No hay delivery',secondaryMotive:'Cobertura',transcript:'Movistar anteriormente tenía mala señal.'});
assert.equal(classified.primaryMotive,'No hay delivery');
assert.ok(classified.mentionedMotives?.includes('Cobertura / señal'));
const coverageCall={...MOVISTAR_GEO_DEMO[0],sale:false,primaryMotive:'Cobertura / señal',mentionedMotives:['Cobertura / señal']};
assert.equal(matchesGeoMotive(coverageCall,'No hay delivery','PRIMARY'),false);
assert.equal(matchesGeoMotive(coverageCall,'No hay delivery','MENTIONED'),false);
assert.equal(matchesGeoMotive(coverageCall,'Cobertura / señal','PRIMARY'),true);
assert.equal(resolveGeoAnalysis({primaryMotive:'Cobertura',responsibility:'Cliente'}).fallResponsibility,'NEGOCIO');
const sampleDistrict=PERU_DISTRICTS.find(item=>item.department==='ANCASH');
assert.ok(sampleDistrict);
const manual=classificationPayload({typification:SIGNAL_TYPIFICATION,department:'ANCASH',districtCode:sampleDistrict.code});
assert.equal(manual.geoAnalysis?.district,sampleDistrict.district);
assert.equal(manual.geoAnalysis?.fallResponsibility,'NEGOCIO');
assert.equal(requiresLocation(DELIVERY_TYPIFICATION),true);
assert.ok(classificationError({typification:DELIVERY_TYPIFICATION,department:'ANCASH',districtCode:''}));
const delivery=classificationPayload({typification:DELIVERY_TYPIFICATION,department:'ANCASH',districtCode:sampleDistrict.code});
assert.equal(classificationError({typification:DELIVERY_TYPIFICATION,department:'ANCASH',districtCode:sampleDistrict.code}),'');
assert.equal(delivery.geoAnalysis?.district,sampleDistrict.district);
assert.equal(delivery.geoAnalysis?.primaryMotive,DELIVERY_TYPIFICATION);
assert.equal(delivery.geoAnalysis?.fallResponsibility,'NEGOCIO');
const experience={typification:'Mala experiencia Movistar',secondaryTypification:SECONDARY_SIGNAL_TYPIFICATION,department:'',province:'',districtCode:''};
assert.equal(classificationError(experience),'','El motivo 2 de mala señal no exige ubicación');
const optionalCoverage=classificationPayload(experience);
assert.equal(optionalCoverage.geoAnalysis?.primaryMotive,'Mala experiencia Movistar');
assert.equal(optionalCoverage.geoAnalysis?.secondaryMotive,'Cobertura / señal');
assert.ok(optionalCoverage.geoAnalysis?.mentionedMotives?.includes('Cobertura / señal'));
assert.equal(optionalCoverage.geoAnalysis?.district,undefined);
const withProvince=classificationPayload({...experience,department:'ANCASH',province:sampleDistrict.province});
assert.equal(classificationError({...experience,department:'ANCASH',province:sampleDistrict.province}),'');
assert.ok(classificationError({...experience,department:'ANCASH',province:'Provincia inexistente'}));
assert.equal(withProvince.geoAnalysis?.province,sampleDistrict.province);
assert.equal(classificationFromEvaluation({typification:withProvince.typification,geoAnalysis:withProvince.geoAnalysis} as Evaluation).secondaryTypification,SECONDARY_SIGNAL_TYPIFICATION);
const secondaryCall={...coverageCall,primaryMotive:withProvince.geoAnalysis?.primaryMotive,mentionedMotives:withProvince.geoAnalysis?.mentionedMotives};
assert.equal(matchesGeoMotive(secondaryCall,'Cobertura / señal','PRIMARY'),false);
assert.equal(matchesGeoMotive(secondaryCall,'Cobertura / señal','MENTIONED'),true);
assert.equal(aggregateDepartments(MOVISTAR_GEO_DEMO,'Cobertura / señal','PRIMARY').find(item=>item.department==='ANCASH')?.incidence,60);
assert.equal(aggregateDepartments(MOVISTAR_GEO_DEMO,'Cobertura / señal','PRIMARY').find(item=>item.department==='TUMBES')?.incidence,null);
assert.equal(aggregateDepartments([{...MOVISTAR_GEO_DEMO[0],sale:null}],'Cobertura / señal','PRIMARY').find(item=>item.department==='ANCASH')?.selectedCases,0);
const tenDepartments=PERU_GEOJSON.features.slice(0,10).map((feature,index)=>({...MOVISTAR_GEO_DEMO[0],id:`geo_${index}`,department:feature.properties.NM_DEPA,sale:false,primaryMotive:'Cobertura / señal'}));
const equalShares=aggregateDepartments(tenDepartments,'Cobertura / señal','PRIMARY');
assert.equal(equalShares.find(item=>item.department===normalizeDepartment(tenDepartments[0].department))?.participation,10);
const unequalShares=aggregateDepartments([...tenDepartments,{...tenDepartments[0],id:'extra'}],'Cobertura / señal','PRIMARY');
assert.ok(Math.abs((unequalShares.find(item=>item.department===normalizeDepartment(tenDepartments[0].department))?.participation||0)-200/11)<0.001);
assert.ok(Math.abs(unequalShares.reduce((sum,item)=>sum+(item.participation||0),0)-100)<0.001);
assert.equal(geoHeatColor(0,[1,2,3]),'#183046');
assert.equal(geoHeatColor(1,[1,2,3]),'#1769ae');
assert.equal(geoHeatColor(2,[1,2,3]),'#3997d7');
assert.equal(geoHeatColor(3,[1,2,3]),'#5bc4ff');
assert.notEqual(geoHeatColor(1,[1,2,3]),geoHeatColor(2,[1,2,3]));
assert.notEqual(geoHeatColor(2,[1,2,3]),geoHeatColor(3,[1,2,3]));
console.log('Movistar geo: verificaciones correctas');
