import assert from 'node:assert/strict';
import { aggregateDepartments, normalizeDepartment, PERU_GEOJSON, resolveGeoAnalysis } from '../src/utils/movistarGeo';
import { MOVISTAR_GEO_DEMO } from '../src/data/movistarGeoDemo';
import { classificationPayload, PERU_DISTRICTS, SIGNAL_TYPIFICATION } from '../src/utils/evaluationTypification';

assert.equal(normalizeDepartment('Áncash'),'ANCASH');
assert.equal(normalizeDepartment('Lima Provincia'),'LIMA');
assert.equal(normalizeDepartment('lugar imaginario'),'No identificado');
assert.equal(resolveGeoAnalysis({transcript:'Estoy en Pampa Chico, provincia de Recuay.'}).department,'ANCASH');
const classified=resolveGeoAnalysis({primaryMotive:'No hay delivery',secondaryMotive:'Cobertura',transcript:'Movistar anteriormente tenía mala señal.'});
assert.equal(classified.primaryMotive,'No hay delivery');
assert.ok(classified.mentionedMotives?.includes('Cobertura / señal'));
assert.equal(resolveGeoAnalysis({primaryMotive:'Cobertura',responsibility:'Cliente'}).fallResponsibility,'NEGOCIO');
const sampleDistrict=PERU_DISTRICTS.find(item=>item.department==='ANCASH');
assert.ok(sampleDistrict);
const manual=classificationPayload({typification:SIGNAL_TYPIFICATION,department:'ANCASH',districtCode:sampleDistrict.code});
assert.equal(manual.geoAnalysis?.district,sampleDistrict.district);
assert.equal(manual.geoAnalysis?.fallResponsibility,'NEGOCIO');
assert.equal(aggregateDepartments(MOVISTAR_GEO_DEMO,'Cobertura / señal','PRIMARY').find(item=>item.department==='ANCASH')?.incidence,60);
assert.equal(aggregateDepartments(MOVISTAR_GEO_DEMO,'Cobertura / señal','PRIMARY').find(item=>item.department==='TUMBES')?.incidence,null);
assert.equal(aggregateDepartments([{...MOVISTAR_GEO_DEMO[0],sale:null}],'Cobertura / señal','PRIMARY').find(item=>item.department==='ANCASH')?.selectedCases,0);
const tenDepartments=PERU_GEOJSON.features.slice(0,10).map((feature,index)=>({...MOVISTAR_GEO_DEMO[0],id:`geo_${index}`,department:feature.properties.NM_DEPA,sale:false,primaryMotive:'Cobertura / señal'}));
const equalShares=aggregateDepartments(tenDepartments,'Cobertura / señal','PRIMARY');
assert.equal(equalShares.find(item=>item.department===normalizeDepartment(tenDepartments[0].department))?.participation,10);
const unequalShares=aggregateDepartments([...tenDepartments,{...tenDepartments[0],id:'extra'}],'Cobertura / señal','PRIMARY');
assert.ok(Math.abs((unequalShares.find(item=>item.department===normalizeDepartment(tenDepartments[0].department))?.participation||0)-200/11)<0.001);
assert.ok(Math.abs(unequalShares.reduce((sum,item)=>sum+(item.participation||0),0)-100)<0.001);
console.log('Movistar geo: verificaciones correctas');
