import assert from 'node:assert/strict'; import {spawn} from 'node:child_process'; import {mkdtemp,rm} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path';
const dir=await mkdtemp(join(tmpdir(),'cm-p2-')),port=3400+Math.floor(Math.random()*500),base=`http://127.0.0.1:${port}`;
const app=spawn(process.execPath,['dist/server.cjs'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),SQLITE_PATH:join(dir,'db.sqlite'),INITIAL_ADMIN_PASSWORD:'Admin-test-2026',GOOGLE_SHEET_ID:'',GOOGLE_DRIVE_FOLDER_ID:'',GOOGLE_CLIENT_ID:'',GOOGLE_CLIENT_SECRET:'',GOOGLE_REFRESH_TOKEN:'',GMAIL_CLIENT_ID:'',GMAIL_CLIENT_SECRET:'',GMAIL_REFRESH_TOKEN:''}});
const api=async(path,{token,body,...options}={})=>{const r=await fetch(base+path,{...options,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json()}catch{}return{r,d}};
const login=async(i,p)=>{const x=await api('/api/auth/login',{method:'POST',body:{identity:i,password:p}});assert.equal(x.r.status,200);return x.d.token};
const evaluation=(id,advisorId,score)=>({id,advisorId,evaluatorId:'usr_admin',campaignId:'camp_1',teamId:'team_1',supervisorId:'usr_sup',product:'X',date:'2026-09-07',time:'10:00',callId:id,recordingCode:id,type:'MONITOREO_REGULAR',evaluationType:'QUALITY',qualityStatus:'FINALIZED',validationStatus:'VALIDATED',sale:false,comments:'x',scoreTotal:score,technicalScore:score,items:[],createdAt:new Date().toISOString()});
try{
 for(let i=0;i<80;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,80))}
 const admin=await login('admin','Admin-test-2026'),repo=(await api('/api/shared-repository',{token:admin})).d.repository,now=new Date().toISOString();
 const users=[...repo.users,{id:'usr_sup',name:'Supervisor',email:'sup@test',username:'sup',role:'SUPERVISOR',status:'ACTIVO',teamId:'team_1',createdAt:now,password:'Sup-test-2026'},{id:'usr_a1',name:'Asesor Uno',email:'a1@test',username:'a1',role:'ASESOR',status:'ACTIVO',advisorId:'adv_1',createdAt:now,password:'Agent-test-2026'},{id:'usr_a2',name:'Asesor Dos',email:'a2@test',username:'a2',role:'ASESOR',status:'ACTIVO',advisorId:'adv_2',createdAt:now,password:'Agent-test-2026'}];
 const advisors=[{id:'adv_1',dni:'1',name:'Asesor Uno',campaignId:'camp_1',teamId:'team_1',supervisorId:'usr_sup',status:'ACTIVO',active:true},{id:'adv_2',dni:'2',name:'Asesor Dos',campaignId:'camp_1',teamId:'team_1',supervisorId:'usr_sup',status:'ACTIVO',active:true}];
 assert.equal((await api('/api/shared-repository/sync',{method:'PUT',token:admin,body:{...repo,users,advisors}})).r.status,200);
 for(const e of [evaluation('e1','adv_1',80),evaluation('e2','adv_2',60)])assert.equal((await api('/api/evaluations',{method:'POST',token:admin,body:e})).r.status,201);
 const supervisor=await login('sup','Sup-test-2026'),agent=await login('a1','Agent-test-2026'),dashboard=await api('/api/supervisor/dashboard',{token:supervisor});
 assert.equal(dashboard.r.status,200);assert.equal(dashboard.d.metrics.teamAverage,70);assert.equal(dashboard.d.advisors.length,2);assert.equal((await api('/api/supervisor/advisors/nope/evaluations',{token:supervisor})).r.status,404);
 const created=await api('/api/quality-alerts',{method:'POST',token:admin,body:{title:'Alerta',detail:'Detalle',advisorId:'adv_1',supervisorId:'usr_sup',campaignId:'camp_1',validUntil:'2099-01-01',criticality:'ALTA'}});assert.equal(created.r.status,201);const alert=created.d.alert;
 assert.equal((await api('/api/quality-alerts',{method:'POST',token:agent,body:{title:'x'}})).r.status,403);assert.equal((await api('/api/quality-alerts',{token:agent})).d.alerts.length,1);assert.equal((await api(`/api/quality-alerts/${alert.id}`,{method:'PATCH',token:supervisor,body:{status:'GESTIONADA',feedbackPerformed:true,managementDetail:'Feedback realizado'}})).r.status,200);assert.equal((await api('/api/quality-alerts',{token:supervisor})).d.alerts[0].supervisorResponses.length,1);assert.equal((await api(`/api/quality-alerts/${alert.id}`,{method:'DELETE',token:agent})).r.status,403);assert.equal((await api(`/api/quality-alerts/${alert.id}`,{method:'DELETE',token:admin})).r.status,200);
 console.log('Fase 2: permisos, dashboard y alertas correctos.');
}finally{app.kill();await new Promise(resolve=>setTimeout(resolve,250));await rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:200})}

