import React, { useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const ForcePasswordChange: React.FC = () => {
  const { changePassword, logout } = useApp(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (password.length < 8) return setError('Usa al menos 8 caracteres.'); if (password !== confirm) return setError('Las contraseñas no coinciden.'); setSaving(true); setError(''); try { await changePassword(password); } catch (err) { setError(err instanceof Error ? err.message : 'No fue posible guardar la contraseña.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[200] grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><form onSubmit={submit} className="cm-modal w-full max-w-md p-6"><LockKeyhole className="h-7 w-7 text-[var(--cm-primary)]" /><h2 className="mt-3 text-xl font-bold">Cambia tu contraseña</h2><p className="mt-1 text-sm text-[var(--cm-text-secondary)]">Por seguridad, debes cambiar la clave inicial antes de continuar.</p><label className="mt-5 block text-sm font-semibold">Nueva contraseña<input type="password" value={password} onChange={event => setPassword(event.target.value)} className="cm-input mt-2 w-full p-3" autoFocus required /></label><label className="mt-4 block text-sm font-semibold">Confirmar contraseña<input type="password" value={confirm} onChange={event => setConfirm(event.target.value)} className="cm-input mt-2 w-full p-3" required /></label>{error && <p className="mt-3 text-sm text-[var(--cm-danger)]">{error}</p>}<div className="mt-6 flex gap-3"><button type="button" disabled={saving} onClick={()=>void logout()} className="cm-button-secondary flex-1 px-4 py-3">Cancelar</button><button disabled={saving} className="cm-button-primary flex-1 px-4 py-3">{saving ? 'Guardando…' : 'Guardar contraseña'}</button></div></form></div>;
};
